// Code generated by hack/gen-multiclient. DO NOT EDIT.

package multi

import (
	"context"

	svc "github.com/aws/aws-sdk-go-v2/service/batch"

	"github.com/konfig-io/konfig-konector/internal/aws/provider"
)

// Batch wraps *svc.Client and applies the provider.Scope from the context
// (Region and Credentials) as per-operation options on every call.
type Batch struct{ base *svc.Client }

// NewBatch wraps base.
func NewBatch(base *svc.Client) *Batch { return &Batch{base: base} }

// Base returns the underlying client.
func (m *Batch) Base() *svc.Client { return m.base }

func (m *Batch) opts(ctx context.Context, optFns []func(*svc.Options)) []func(*svc.Options) {
	s := provider.ScopeFrom(ctx)
	if s == nil || (s.Region == "" && s.Credentials == nil) {
		return optFns
	}
	out := make([]func(*svc.Options), 0, len(optFns)+1)
	out = append(out, func(o *svc.Options) {
		if s.Region != "" {
			o.Region = s.Region
		}
		if s.Credentials != nil {
			o.Credentials = s.Credentials
		}
	})
	return append(out, optFns...)
}

func (m *Batch) CancelJob(ctx context.Context, params *svc.CancelJobInput, optFns ...func(*svc.Options)) (*svc.CancelJobOutput, error) {
	return m.base.CancelJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) CreateComputeEnvironment(ctx context.Context, params *svc.CreateComputeEnvironmentInput, optFns ...func(*svc.Options)) (*svc.CreateComputeEnvironmentOutput, error) {
	return m.base.CreateComputeEnvironment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) CreateJobQueue(ctx context.Context, params *svc.CreateJobQueueInput, optFns ...func(*svc.Options)) (*svc.CreateJobQueueOutput, error) {
	return m.base.CreateJobQueue(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) CreateSchedulingPolicy(ctx context.Context, params *svc.CreateSchedulingPolicyInput, optFns ...func(*svc.Options)) (*svc.CreateSchedulingPolicyOutput, error) {
	return m.base.CreateSchedulingPolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DeleteComputeEnvironment(ctx context.Context, params *svc.DeleteComputeEnvironmentInput, optFns ...func(*svc.Options)) (*svc.DeleteComputeEnvironmentOutput, error) {
	return m.base.DeleteComputeEnvironment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DeleteJobQueue(ctx context.Context, params *svc.DeleteJobQueueInput, optFns ...func(*svc.Options)) (*svc.DeleteJobQueueOutput, error) {
	return m.base.DeleteJobQueue(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DeleteSchedulingPolicy(ctx context.Context, params *svc.DeleteSchedulingPolicyInput, optFns ...func(*svc.Options)) (*svc.DeleteSchedulingPolicyOutput, error) {
	return m.base.DeleteSchedulingPolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DeregisterJobDefinition(ctx context.Context, params *svc.DeregisterJobDefinitionInput, optFns ...func(*svc.Options)) (*svc.DeregisterJobDefinitionOutput, error) {
	return m.base.DeregisterJobDefinition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DescribeComputeEnvironments(ctx context.Context, params *svc.DescribeComputeEnvironmentsInput, optFns ...func(*svc.Options)) (*svc.DescribeComputeEnvironmentsOutput, error) {
	return m.base.DescribeComputeEnvironments(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DescribeJobDefinitions(ctx context.Context, params *svc.DescribeJobDefinitionsInput, optFns ...func(*svc.Options)) (*svc.DescribeJobDefinitionsOutput, error) {
	return m.base.DescribeJobDefinitions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DescribeJobQueues(ctx context.Context, params *svc.DescribeJobQueuesInput, optFns ...func(*svc.Options)) (*svc.DescribeJobQueuesOutput, error) {
	return m.base.DescribeJobQueues(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DescribeJobs(ctx context.Context, params *svc.DescribeJobsInput, optFns ...func(*svc.Options)) (*svc.DescribeJobsOutput, error) {
	return m.base.DescribeJobs(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) DescribeSchedulingPolicies(ctx context.Context, params *svc.DescribeSchedulingPoliciesInput, optFns ...func(*svc.Options)) (*svc.DescribeSchedulingPoliciesOutput, error) {
	return m.base.DescribeSchedulingPolicies(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) GetJobQueueSnapshot(ctx context.Context, params *svc.GetJobQueueSnapshotInput, optFns ...func(*svc.Options)) (*svc.GetJobQueueSnapshotOutput, error) {
	return m.base.GetJobQueueSnapshot(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) ListJobs(ctx context.Context, params *svc.ListJobsInput, optFns ...func(*svc.Options)) (*svc.ListJobsOutput, error) {
	return m.base.ListJobs(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) ListSchedulingPolicies(ctx context.Context, params *svc.ListSchedulingPoliciesInput, optFns ...func(*svc.Options)) (*svc.ListSchedulingPoliciesOutput, error) {
	return m.base.ListSchedulingPolicies(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) ListTagsForResource(ctx context.Context, params *svc.ListTagsForResourceInput, optFns ...func(*svc.Options)) (*svc.ListTagsForResourceOutput, error) {
	return m.base.ListTagsForResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) RegisterJobDefinition(ctx context.Context, params *svc.RegisterJobDefinitionInput, optFns ...func(*svc.Options)) (*svc.RegisterJobDefinitionOutput, error) {
	return m.base.RegisterJobDefinition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) SubmitJob(ctx context.Context, params *svc.SubmitJobInput, optFns ...func(*svc.Options)) (*svc.SubmitJobOutput, error) {
	return m.base.SubmitJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) TagResource(ctx context.Context, params *svc.TagResourceInput, optFns ...func(*svc.Options)) (*svc.TagResourceOutput, error) {
	return m.base.TagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) TerminateJob(ctx context.Context, params *svc.TerminateJobInput, optFns ...func(*svc.Options)) (*svc.TerminateJobOutput, error) {
	return m.base.TerminateJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) UntagResource(ctx context.Context, params *svc.UntagResourceInput, optFns ...func(*svc.Options)) (*svc.UntagResourceOutput, error) {
	return m.base.UntagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) UpdateComputeEnvironment(ctx context.Context, params *svc.UpdateComputeEnvironmentInput, optFns ...func(*svc.Options)) (*svc.UpdateComputeEnvironmentOutput, error) {
	return m.base.UpdateComputeEnvironment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) UpdateJobQueue(ctx context.Context, params *svc.UpdateJobQueueInput, optFns ...func(*svc.Options)) (*svc.UpdateJobQueueOutput, error) {
	return m.base.UpdateJobQueue(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Batch) UpdateSchedulingPolicy(ctx context.Context, params *svc.UpdateSchedulingPolicyInput, optFns ...func(*svc.Options)) (*svc.UpdateSchedulingPolicyOutput, error) {
	return m.base.UpdateSchedulingPolicy(ctx, params, m.opts(ctx, optFns)...)
}
