// Code generated by hack/gen-multiclient. DO NOT EDIT.

package multi

import (
	"context"

	svc "github.com/aws/aws-sdk-go-v2/service/codedeploy"

	"github.com/konfig-io/konfig-konector/internal/aws/provider"
)

// CodeDeploy wraps *svc.Client and applies the provider.Scope from the context
// (Region and Credentials) as per-operation options on every call.
type CodeDeploy struct{ base *svc.Client }

// NewCodeDeploy wraps base.
func NewCodeDeploy(base *svc.Client) *CodeDeploy { return &CodeDeploy{base: base} }

// Base returns the underlying client.
func (m *CodeDeploy) Base() *svc.Client { return m.base }

func (m *CodeDeploy) opts(ctx context.Context, optFns []func(*svc.Options)) []func(*svc.Options) {
	s := provider.ScopeFrom(ctx)
	if s == nil || (s.Region == "" && s.Credentials == nil) {
		return optFns
	}
	out := make([]func(*svc.Options), 0, len(optFns)+1)
	out = append(out, func(o *svc.Options) {
		if s.Region != "" {
			o.Region = s.Region
		}
		if s.Credentials != nil {
			o.Credentials = s.Credentials
		}
	})
	return append(out, optFns...)
}

func (m *CodeDeploy) AddTagsToOnPremisesInstances(ctx context.Context, params *svc.AddTagsToOnPremisesInstancesInput, optFns ...func(*svc.Options)) (*svc.AddTagsToOnPremisesInstancesOutput, error) {
	return m.base.AddTagsToOnPremisesInstances(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetApplicationRevisions(ctx context.Context, params *svc.BatchGetApplicationRevisionsInput, optFns ...func(*svc.Options)) (*svc.BatchGetApplicationRevisionsOutput, error) {
	return m.base.BatchGetApplicationRevisions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetApplications(ctx context.Context, params *svc.BatchGetApplicationsInput, optFns ...func(*svc.Options)) (*svc.BatchGetApplicationsOutput, error) {
	return m.base.BatchGetApplications(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetDeploymentGroups(ctx context.Context, params *svc.BatchGetDeploymentGroupsInput, optFns ...func(*svc.Options)) (*svc.BatchGetDeploymentGroupsOutput, error) {
	return m.base.BatchGetDeploymentGroups(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetDeploymentInstances(ctx context.Context, params *svc.BatchGetDeploymentInstancesInput, optFns ...func(*svc.Options)) (*svc.BatchGetDeploymentInstancesOutput, error) {
	return m.base.BatchGetDeploymentInstances(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetDeploymentTargets(ctx context.Context, params *svc.BatchGetDeploymentTargetsInput, optFns ...func(*svc.Options)) (*svc.BatchGetDeploymentTargetsOutput, error) {
	return m.base.BatchGetDeploymentTargets(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetDeployments(ctx context.Context, params *svc.BatchGetDeploymentsInput, optFns ...func(*svc.Options)) (*svc.BatchGetDeploymentsOutput, error) {
	return m.base.BatchGetDeployments(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) BatchGetOnPremisesInstances(ctx context.Context, params *svc.BatchGetOnPremisesInstancesInput, optFns ...func(*svc.Options)) (*svc.BatchGetOnPremisesInstancesOutput, error) {
	return m.base.BatchGetOnPremisesInstances(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ContinueDeployment(ctx context.Context, params *svc.ContinueDeploymentInput, optFns ...func(*svc.Options)) (*svc.ContinueDeploymentOutput, error) {
	return m.base.ContinueDeployment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) CreateApplication(ctx context.Context, params *svc.CreateApplicationInput, optFns ...func(*svc.Options)) (*svc.CreateApplicationOutput, error) {
	return m.base.CreateApplication(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) CreateDeployment(ctx context.Context, params *svc.CreateDeploymentInput, optFns ...func(*svc.Options)) (*svc.CreateDeploymentOutput, error) {
	return m.base.CreateDeployment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) CreateDeploymentConfig(ctx context.Context, params *svc.CreateDeploymentConfigInput, optFns ...func(*svc.Options)) (*svc.CreateDeploymentConfigOutput, error) {
	return m.base.CreateDeploymentConfig(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) CreateDeploymentGroup(ctx context.Context, params *svc.CreateDeploymentGroupInput, optFns ...func(*svc.Options)) (*svc.CreateDeploymentGroupOutput, error) {
	return m.base.CreateDeploymentGroup(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) DeleteApplication(ctx context.Context, params *svc.DeleteApplicationInput, optFns ...func(*svc.Options)) (*svc.DeleteApplicationOutput, error) {
	return m.base.DeleteApplication(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) DeleteDeploymentConfig(ctx context.Context, params *svc.DeleteDeploymentConfigInput, optFns ...func(*svc.Options)) (*svc.DeleteDeploymentConfigOutput, error) {
	return m.base.DeleteDeploymentConfig(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) DeleteDeploymentGroup(ctx context.Context, params *svc.DeleteDeploymentGroupInput, optFns ...func(*svc.Options)) (*svc.DeleteDeploymentGroupOutput, error) {
	return m.base.DeleteDeploymentGroup(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) DeleteGitHubAccountToken(ctx context.Context, params *svc.DeleteGitHubAccountTokenInput, optFns ...func(*svc.Options)) (*svc.DeleteGitHubAccountTokenOutput, error) {
	return m.base.DeleteGitHubAccountToken(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) DeleteResourcesByExternalId(ctx context.Context, params *svc.DeleteResourcesByExternalIdInput, optFns ...func(*svc.Options)) (*svc.DeleteResourcesByExternalIdOutput, error) {
	return m.base.DeleteResourcesByExternalId(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) DeregisterOnPremisesInstance(ctx context.Context, params *svc.DeregisterOnPremisesInstanceInput, optFns ...func(*svc.Options)) (*svc.DeregisterOnPremisesInstanceOutput, error) {
	return m.base.DeregisterOnPremisesInstance(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetApplication(ctx context.Context, params *svc.GetApplicationInput, optFns ...func(*svc.Options)) (*svc.GetApplicationOutput, error) {
	return m.base.GetApplication(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetApplicationRevision(ctx context.Context, params *svc.GetApplicationRevisionInput, optFns ...func(*svc.Options)) (*svc.GetApplicationRevisionOutput, error) {
	return m.base.GetApplicationRevision(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetDeployment(ctx context.Context, params *svc.GetDeploymentInput, optFns ...func(*svc.Options)) (*svc.GetDeploymentOutput, error) {
	return m.base.GetDeployment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetDeploymentConfig(ctx context.Context, params *svc.GetDeploymentConfigInput, optFns ...func(*svc.Options)) (*svc.GetDeploymentConfigOutput, error) {
	return m.base.GetDeploymentConfig(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetDeploymentGroup(ctx context.Context, params *svc.GetDeploymentGroupInput, optFns ...func(*svc.Options)) (*svc.GetDeploymentGroupOutput, error) {
	return m.base.GetDeploymentGroup(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetDeploymentInstance(ctx context.Context, params *svc.GetDeploymentInstanceInput, optFns ...func(*svc.Options)) (*svc.GetDeploymentInstanceOutput, error) {
	return m.base.GetDeploymentInstance(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetDeploymentTarget(ctx context.Context, params *svc.GetDeploymentTargetInput, optFns ...func(*svc.Options)) (*svc.GetDeploymentTargetOutput, error) {
	return m.base.GetDeploymentTarget(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) GetOnPremisesInstance(ctx context.Context, params *svc.GetOnPremisesInstanceInput, optFns ...func(*svc.Options)) (*svc.GetOnPremisesInstanceOutput, error) {
	return m.base.GetOnPremisesInstance(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListApplicationRevisions(ctx context.Context, params *svc.ListApplicationRevisionsInput, optFns ...func(*svc.Options)) (*svc.ListApplicationRevisionsOutput, error) {
	return m.base.ListApplicationRevisions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListApplications(ctx context.Context, params *svc.ListApplicationsInput, optFns ...func(*svc.Options)) (*svc.ListApplicationsOutput, error) {
	return m.base.ListApplications(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListDeploymentConfigs(ctx context.Context, params *svc.ListDeploymentConfigsInput, optFns ...func(*svc.Options)) (*svc.ListDeploymentConfigsOutput, error) {
	return m.base.ListDeploymentConfigs(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListDeploymentGroups(ctx context.Context, params *svc.ListDeploymentGroupsInput, optFns ...func(*svc.Options)) (*svc.ListDeploymentGroupsOutput, error) {
	return m.base.ListDeploymentGroups(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListDeploymentInstances(ctx context.Context, params *svc.ListDeploymentInstancesInput, optFns ...func(*svc.Options)) (*svc.ListDeploymentInstancesOutput, error) {
	return m.base.ListDeploymentInstances(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListDeploymentTargets(ctx context.Context, params *svc.ListDeploymentTargetsInput, optFns ...func(*svc.Options)) (*svc.ListDeploymentTargetsOutput, error) {
	return m.base.ListDeploymentTargets(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListDeployments(ctx context.Context, params *svc.ListDeploymentsInput, optFns ...func(*svc.Options)) (*svc.ListDeploymentsOutput, error) {
	return m.base.ListDeployments(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListGitHubAccountTokenNames(ctx context.Context, params *svc.ListGitHubAccountTokenNamesInput, optFns ...func(*svc.Options)) (*svc.ListGitHubAccountTokenNamesOutput, error) {
	return m.base.ListGitHubAccountTokenNames(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListOnPremisesInstances(ctx context.Context, params *svc.ListOnPremisesInstancesInput, optFns ...func(*svc.Options)) (*svc.ListOnPremisesInstancesOutput, error) {
	return m.base.ListOnPremisesInstances(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) ListTagsForResource(ctx context.Context, params *svc.ListTagsForResourceInput, optFns ...func(*svc.Options)) (*svc.ListTagsForResourceOutput, error) {
	return m.base.ListTagsForResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) PutLifecycleEventHookExecutionStatus(ctx context.Context, params *svc.PutLifecycleEventHookExecutionStatusInput, optFns ...func(*svc.Options)) (*svc.PutLifecycleEventHookExecutionStatusOutput, error) {
	return m.base.PutLifecycleEventHookExecutionStatus(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) RegisterApplicationRevision(ctx context.Context, params *svc.RegisterApplicationRevisionInput, optFns ...func(*svc.Options)) (*svc.RegisterApplicationRevisionOutput, error) {
	return m.base.RegisterApplicationRevision(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) RegisterOnPremisesInstance(ctx context.Context, params *svc.RegisterOnPremisesInstanceInput, optFns ...func(*svc.Options)) (*svc.RegisterOnPremisesInstanceOutput, error) {
	return m.base.RegisterOnPremisesInstance(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) RemoveTagsFromOnPremisesInstances(ctx context.Context, params *svc.RemoveTagsFromOnPremisesInstancesInput, optFns ...func(*svc.Options)) (*svc.RemoveTagsFromOnPremisesInstancesOutput, error) {
	return m.base.RemoveTagsFromOnPremisesInstances(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) SkipWaitTimeForInstanceTermination(ctx context.Context, params *svc.SkipWaitTimeForInstanceTerminationInput, optFns ...func(*svc.Options)) (*svc.SkipWaitTimeForInstanceTerminationOutput, error) {
	return m.base.SkipWaitTimeForInstanceTermination(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) StopDeployment(ctx context.Context, params *svc.StopDeploymentInput, optFns ...func(*svc.Options)) (*svc.StopDeploymentOutput, error) {
	return m.base.StopDeployment(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) TagResource(ctx context.Context, params *svc.TagResourceInput, optFns ...func(*svc.Options)) (*svc.TagResourceOutput, error) {
	return m.base.TagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) UntagResource(ctx context.Context, params *svc.UntagResourceInput, optFns ...func(*svc.Options)) (*svc.UntagResourceOutput, error) {
	return m.base.UntagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) UpdateApplication(ctx context.Context, params *svc.UpdateApplicationInput, optFns ...func(*svc.Options)) (*svc.UpdateApplicationOutput, error) {
	return m.base.UpdateApplication(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CodeDeploy) UpdateDeploymentGroup(ctx context.Context, params *svc.UpdateDeploymentGroupInput, optFns ...func(*svc.Options)) (*svc.UpdateDeploymentGroupOutput, error) {
	return m.base.UpdateDeploymentGroup(ctx, params, m.opts(ctx, optFns)...)
}
