// Code generated by hack/gen-multiclient. DO NOT EDIT.

package multi

import (
	"context"

	svc "github.com/aws/aws-sdk-go-v2/service/cloudcontrol"

	"github.com/konfig-io/konfig-konector/internal/aws/provider"
)

// CloudControl wraps *svc.Client and applies the provider.Scope from the context
// (Region and Credentials) as per-operation options on every call.
type CloudControl struct{ base *svc.Client }

// NewCloudControl wraps base.
func NewCloudControl(base *svc.Client) *CloudControl { return &CloudControl{base: base} }

// Base returns the underlying client.
func (m *CloudControl) Base() *svc.Client { return m.base }

func (m *CloudControl) opts(ctx context.Context, optFns []func(*svc.Options)) []func(*svc.Options) {
	s := provider.ScopeFrom(ctx)
	if s == nil || (s.Region == "" && s.Credentials == nil) {
		return optFns
	}
	out := make([]func(*svc.Options), 0, len(optFns)+1)
	out = append(out, func(o *svc.Options) {
		if s.Region != "" {
			o.Region = s.Region
		}
		if s.Credentials != nil {
			o.Credentials = s.Credentials
		}
	})
	return append(out, optFns...)
}

func (m *CloudControl) CancelResourceRequest(ctx context.Context, params *svc.CancelResourceRequestInput, optFns ...func(*svc.Options)) (*svc.CancelResourceRequestOutput, error) {
	return m.base.CancelResourceRequest(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) CreateResource(ctx context.Context, params *svc.CreateResourceInput, optFns ...func(*svc.Options)) (*svc.CreateResourceOutput, error) {
	return m.base.CreateResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) DeleteResource(ctx context.Context, params *svc.DeleteResourceInput, optFns ...func(*svc.Options)) (*svc.DeleteResourceOutput, error) {
	return m.base.DeleteResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) GetResource(ctx context.Context, params *svc.GetResourceInput, optFns ...func(*svc.Options)) (*svc.GetResourceOutput, error) {
	return m.base.GetResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) GetResourceRequestStatus(ctx context.Context, params *svc.GetResourceRequestStatusInput, optFns ...func(*svc.Options)) (*svc.GetResourceRequestStatusOutput, error) {
	return m.base.GetResourceRequestStatus(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) ListResourceRequests(ctx context.Context, params *svc.ListResourceRequestsInput, optFns ...func(*svc.Options)) (*svc.ListResourceRequestsOutput, error) {
	return m.base.ListResourceRequests(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) ListResources(ctx context.Context, params *svc.ListResourcesInput, optFns ...func(*svc.Options)) (*svc.ListResourcesOutput, error) {
	return m.base.ListResources(ctx, params, m.opts(ctx, optFns)...)
}

func (m *CloudControl) UpdateResource(ctx context.Context, params *svc.UpdateResourceInput, optFns ...func(*svc.Options)) (*svc.UpdateResourceOutput, error) {
	return m.base.UpdateResource(ctx, params, m.opts(ctx, optFns)...)
}
