// Code generated by hack/gen-multiclient. DO NOT EDIT.

package multi

import (
	"context"

	svc "github.com/aws/aws-sdk-go-v2/service/glue"

	"github.com/konfig-io/konfig-konector/internal/aws/provider"
)

// Glue wraps *svc.Client and applies the provider.Scope from the context
// (Region and Credentials) as per-operation options on every call.
type Glue struct{ base *svc.Client }

// NewGlue wraps base.
func NewGlue(base *svc.Client) *Glue { return &Glue{base: base} }

// Base returns the underlying client.
func (m *Glue) Base() *svc.Client { return m.base }

func (m *Glue) opts(ctx context.Context, optFns []func(*svc.Options)) []func(*svc.Options) {
	s := provider.ScopeFrom(ctx)
	if s == nil || (s.Region == "" && s.Credentials == nil) {
		return optFns
	}
	out := make([]func(*svc.Options), 0, len(optFns)+1)
	out = append(out, func(o *svc.Options) {
		if s.Region != "" {
			o.Region = s.Region
		}
		if s.Credentials != nil {
			o.Credentials = s.Credentials
		}
	})
	return append(out, optFns...)
}

func (m *Glue) BatchCreatePartition(ctx context.Context, params *svc.BatchCreatePartitionInput, optFns ...func(*svc.Options)) (*svc.BatchCreatePartitionOutput, error) {
	return m.base.BatchCreatePartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchDeleteConnection(ctx context.Context, params *svc.BatchDeleteConnectionInput, optFns ...func(*svc.Options)) (*svc.BatchDeleteConnectionOutput, error) {
	return m.base.BatchDeleteConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchDeletePartition(ctx context.Context, params *svc.BatchDeletePartitionInput, optFns ...func(*svc.Options)) (*svc.BatchDeletePartitionOutput, error) {
	return m.base.BatchDeletePartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchDeleteTable(ctx context.Context, params *svc.BatchDeleteTableInput, optFns ...func(*svc.Options)) (*svc.BatchDeleteTableOutput, error) {
	return m.base.BatchDeleteTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchDeleteTableVersion(ctx context.Context, params *svc.BatchDeleteTableVersionInput, optFns ...func(*svc.Options)) (*svc.BatchDeleteTableVersionOutput, error) {
	return m.base.BatchDeleteTableVersion(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetBlueprints(ctx context.Context, params *svc.BatchGetBlueprintsInput, optFns ...func(*svc.Options)) (*svc.BatchGetBlueprintsOutput, error) {
	return m.base.BatchGetBlueprints(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetCrawlers(ctx context.Context, params *svc.BatchGetCrawlersInput, optFns ...func(*svc.Options)) (*svc.BatchGetCrawlersOutput, error) {
	return m.base.BatchGetCrawlers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetCustomEntityTypes(ctx context.Context, params *svc.BatchGetCustomEntityTypesInput, optFns ...func(*svc.Options)) (*svc.BatchGetCustomEntityTypesOutput, error) {
	return m.base.BatchGetCustomEntityTypes(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetDataQualityResult(ctx context.Context, params *svc.BatchGetDataQualityResultInput, optFns ...func(*svc.Options)) (*svc.BatchGetDataQualityResultOutput, error) {
	return m.base.BatchGetDataQualityResult(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetDevEndpoints(ctx context.Context, params *svc.BatchGetDevEndpointsInput, optFns ...func(*svc.Options)) (*svc.BatchGetDevEndpointsOutput, error) {
	return m.base.BatchGetDevEndpoints(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetJobs(ctx context.Context, params *svc.BatchGetJobsInput, optFns ...func(*svc.Options)) (*svc.BatchGetJobsOutput, error) {
	return m.base.BatchGetJobs(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetPartition(ctx context.Context, params *svc.BatchGetPartitionInput, optFns ...func(*svc.Options)) (*svc.BatchGetPartitionOutput, error) {
	return m.base.BatchGetPartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetTriggers(ctx context.Context, params *svc.BatchGetTriggersInput, optFns ...func(*svc.Options)) (*svc.BatchGetTriggersOutput, error) {
	return m.base.BatchGetTriggers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchGetWorkflows(ctx context.Context, params *svc.BatchGetWorkflowsInput, optFns ...func(*svc.Options)) (*svc.BatchGetWorkflowsOutput, error) {
	return m.base.BatchGetWorkflows(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchStopJobRun(ctx context.Context, params *svc.BatchStopJobRunInput, optFns ...func(*svc.Options)) (*svc.BatchStopJobRunOutput, error) {
	return m.base.BatchStopJobRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) BatchUpdatePartition(ctx context.Context, params *svc.BatchUpdatePartitionInput, optFns ...func(*svc.Options)) (*svc.BatchUpdatePartitionOutput, error) {
	return m.base.BatchUpdatePartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CancelDataQualityRuleRecommendationRun(ctx context.Context, params *svc.CancelDataQualityRuleRecommendationRunInput, optFns ...func(*svc.Options)) (*svc.CancelDataQualityRuleRecommendationRunOutput, error) {
	return m.base.CancelDataQualityRuleRecommendationRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CancelDataQualityRulesetEvaluationRun(ctx context.Context, params *svc.CancelDataQualityRulesetEvaluationRunInput, optFns ...func(*svc.Options)) (*svc.CancelDataQualityRulesetEvaluationRunOutput, error) {
	return m.base.CancelDataQualityRulesetEvaluationRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CancelMLTaskRun(ctx context.Context, params *svc.CancelMLTaskRunInput, optFns ...func(*svc.Options)) (*svc.CancelMLTaskRunOutput, error) {
	return m.base.CancelMLTaskRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CancelStatement(ctx context.Context, params *svc.CancelStatementInput, optFns ...func(*svc.Options)) (*svc.CancelStatementOutput, error) {
	return m.base.CancelStatement(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CheckSchemaVersionValidity(ctx context.Context, params *svc.CheckSchemaVersionValidityInput, optFns ...func(*svc.Options)) (*svc.CheckSchemaVersionValidityOutput, error) {
	return m.base.CheckSchemaVersionValidity(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateBlueprint(ctx context.Context, params *svc.CreateBlueprintInput, optFns ...func(*svc.Options)) (*svc.CreateBlueprintOutput, error) {
	return m.base.CreateBlueprint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateClassifier(ctx context.Context, params *svc.CreateClassifierInput, optFns ...func(*svc.Options)) (*svc.CreateClassifierOutput, error) {
	return m.base.CreateClassifier(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateConnection(ctx context.Context, params *svc.CreateConnectionInput, optFns ...func(*svc.Options)) (*svc.CreateConnectionOutput, error) {
	return m.base.CreateConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateCrawler(ctx context.Context, params *svc.CreateCrawlerInput, optFns ...func(*svc.Options)) (*svc.CreateCrawlerOutput, error) {
	return m.base.CreateCrawler(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateCustomEntityType(ctx context.Context, params *svc.CreateCustomEntityTypeInput, optFns ...func(*svc.Options)) (*svc.CreateCustomEntityTypeOutput, error) {
	return m.base.CreateCustomEntityType(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateDataQualityRuleset(ctx context.Context, params *svc.CreateDataQualityRulesetInput, optFns ...func(*svc.Options)) (*svc.CreateDataQualityRulesetOutput, error) {
	return m.base.CreateDataQualityRuleset(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateDatabase(ctx context.Context, params *svc.CreateDatabaseInput, optFns ...func(*svc.Options)) (*svc.CreateDatabaseOutput, error) {
	return m.base.CreateDatabase(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateDevEndpoint(ctx context.Context, params *svc.CreateDevEndpointInput, optFns ...func(*svc.Options)) (*svc.CreateDevEndpointOutput, error) {
	return m.base.CreateDevEndpoint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateJob(ctx context.Context, params *svc.CreateJobInput, optFns ...func(*svc.Options)) (*svc.CreateJobOutput, error) {
	return m.base.CreateJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateMLTransform(ctx context.Context, params *svc.CreateMLTransformInput, optFns ...func(*svc.Options)) (*svc.CreateMLTransformOutput, error) {
	return m.base.CreateMLTransform(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreatePartition(ctx context.Context, params *svc.CreatePartitionInput, optFns ...func(*svc.Options)) (*svc.CreatePartitionOutput, error) {
	return m.base.CreatePartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreatePartitionIndex(ctx context.Context, params *svc.CreatePartitionIndexInput, optFns ...func(*svc.Options)) (*svc.CreatePartitionIndexOutput, error) {
	return m.base.CreatePartitionIndex(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateRegistry(ctx context.Context, params *svc.CreateRegistryInput, optFns ...func(*svc.Options)) (*svc.CreateRegistryOutput, error) {
	return m.base.CreateRegistry(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateSchema(ctx context.Context, params *svc.CreateSchemaInput, optFns ...func(*svc.Options)) (*svc.CreateSchemaOutput, error) {
	return m.base.CreateSchema(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateScript(ctx context.Context, params *svc.CreateScriptInput, optFns ...func(*svc.Options)) (*svc.CreateScriptOutput, error) {
	return m.base.CreateScript(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateSecurityConfiguration(ctx context.Context, params *svc.CreateSecurityConfigurationInput, optFns ...func(*svc.Options)) (*svc.CreateSecurityConfigurationOutput, error) {
	return m.base.CreateSecurityConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateSession(ctx context.Context, params *svc.CreateSessionInput, optFns ...func(*svc.Options)) (*svc.CreateSessionOutput, error) {
	return m.base.CreateSession(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateTable(ctx context.Context, params *svc.CreateTableInput, optFns ...func(*svc.Options)) (*svc.CreateTableOutput, error) {
	return m.base.CreateTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateTrigger(ctx context.Context, params *svc.CreateTriggerInput, optFns ...func(*svc.Options)) (*svc.CreateTriggerOutput, error) {
	return m.base.CreateTrigger(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateUserDefinedFunction(ctx context.Context, params *svc.CreateUserDefinedFunctionInput, optFns ...func(*svc.Options)) (*svc.CreateUserDefinedFunctionOutput, error) {
	return m.base.CreateUserDefinedFunction(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) CreateWorkflow(ctx context.Context, params *svc.CreateWorkflowInput, optFns ...func(*svc.Options)) (*svc.CreateWorkflowOutput, error) {
	return m.base.CreateWorkflow(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteBlueprint(ctx context.Context, params *svc.DeleteBlueprintInput, optFns ...func(*svc.Options)) (*svc.DeleteBlueprintOutput, error) {
	return m.base.DeleteBlueprint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteClassifier(ctx context.Context, params *svc.DeleteClassifierInput, optFns ...func(*svc.Options)) (*svc.DeleteClassifierOutput, error) {
	return m.base.DeleteClassifier(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteColumnStatisticsForPartition(ctx context.Context, params *svc.DeleteColumnStatisticsForPartitionInput, optFns ...func(*svc.Options)) (*svc.DeleteColumnStatisticsForPartitionOutput, error) {
	return m.base.DeleteColumnStatisticsForPartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteColumnStatisticsForTable(ctx context.Context, params *svc.DeleteColumnStatisticsForTableInput, optFns ...func(*svc.Options)) (*svc.DeleteColumnStatisticsForTableOutput, error) {
	return m.base.DeleteColumnStatisticsForTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteConnection(ctx context.Context, params *svc.DeleteConnectionInput, optFns ...func(*svc.Options)) (*svc.DeleteConnectionOutput, error) {
	return m.base.DeleteConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteCrawler(ctx context.Context, params *svc.DeleteCrawlerInput, optFns ...func(*svc.Options)) (*svc.DeleteCrawlerOutput, error) {
	return m.base.DeleteCrawler(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteCustomEntityType(ctx context.Context, params *svc.DeleteCustomEntityTypeInput, optFns ...func(*svc.Options)) (*svc.DeleteCustomEntityTypeOutput, error) {
	return m.base.DeleteCustomEntityType(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteDataQualityRuleset(ctx context.Context, params *svc.DeleteDataQualityRulesetInput, optFns ...func(*svc.Options)) (*svc.DeleteDataQualityRulesetOutput, error) {
	return m.base.DeleteDataQualityRuleset(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteDatabase(ctx context.Context, params *svc.DeleteDatabaseInput, optFns ...func(*svc.Options)) (*svc.DeleteDatabaseOutput, error) {
	return m.base.DeleteDatabase(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteDevEndpoint(ctx context.Context, params *svc.DeleteDevEndpointInput, optFns ...func(*svc.Options)) (*svc.DeleteDevEndpointOutput, error) {
	return m.base.DeleteDevEndpoint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteJob(ctx context.Context, params *svc.DeleteJobInput, optFns ...func(*svc.Options)) (*svc.DeleteJobOutput, error) {
	return m.base.DeleteJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteMLTransform(ctx context.Context, params *svc.DeleteMLTransformInput, optFns ...func(*svc.Options)) (*svc.DeleteMLTransformOutput, error) {
	return m.base.DeleteMLTransform(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeletePartition(ctx context.Context, params *svc.DeletePartitionInput, optFns ...func(*svc.Options)) (*svc.DeletePartitionOutput, error) {
	return m.base.DeletePartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeletePartitionIndex(ctx context.Context, params *svc.DeletePartitionIndexInput, optFns ...func(*svc.Options)) (*svc.DeletePartitionIndexOutput, error) {
	return m.base.DeletePartitionIndex(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteRegistry(ctx context.Context, params *svc.DeleteRegistryInput, optFns ...func(*svc.Options)) (*svc.DeleteRegistryOutput, error) {
	return m.base.DeleteRegistry(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteResourcePolicy(ctx context.Context, params *svc.DeleteResourcePolicyInput, optFns ...func(*svc.Options)) (*svc.DeleteResourcePolicyOutput, error) {
	return m.base.DeleteResourcePolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteSchema(ctx context.Context, params *svc.DeleteSchemaInput, optFns ...func(*svc.Options)) (*svc.DeleteSchemaOutput, error) {
	return m.base.DeleteSchema(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteSchemaVersions(ctx context.Context, params *svc.DeleteSchemaVersionsInput, optFns ...func(*svc.Options)) (*svc.DeleteSchemaVersionsOutput, error) {
	return m.base.DeleteSchemaVersions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteSecurityConfiguration(ctx context.Context, params *svc.DeleteSecurityConfigurationInput, optFns ...func(*svc.Options)) (*svc.DeleteSecurityConfigurationOutput, error) {
	return m.base.DeleteSecurityConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteSession(ctx context.Context, params *svc.DeleteSessionInput, optFns ...func(*svc.Options)) (*svc.DeleteSessionOutput, error) {
	return m.base.DeleteSession(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteTable(ctx context.Context, params *svc.DeleteTableInput, optFns ...func(*svc.Options)) (*svc.DeleteTableOutput, error) {
	return m.base.DeleteTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteTableVersion(ctx context.Context, params *svc.DeleteTableVersionInput, optFns ...func(*svc.Options)) (*svc.DeleteTableVersionOutput, error) {
	return m.base.DeleteTableVersion(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteTrigger(ctx context.Context, params *svc.DeleteTriggerInput, optFns ...func(*svc.Options)) (*svc.DeleteTriggerOutput, error) {
	return m.base.DeleteTrigger(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteUserDefinedFunction(ctx context.Context, params *svc.DeleteUserDefinedFunctionInput, optFns ...func(*svc.Options)) (*svc.DeleteUserDefinedFunctionOutput, error) {
	return m.base.DeleteUserDefinedFunction(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) DeleteWorkflow(ctx context.Context, params *svc.DeleteWorkflowInput, optFns ...func(*svc.Options)) (*svc.DeleteWorkflowOutput, error) {
	return m.base.DeleteWorkflow(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetBlueprint(ctx context.Context, params *svc.GetBlueprintInput, optFns ...func(*svc.Options)) (*svc.GetBlueprintOutput, error) {
	return m.base.GetBlueprint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetBlueprintRun(ctx context.Context, params *svc.GetBlueprintRunInput, optFns ...func(*svc.Options)) (*svc.GetBlueprintRunOutput, error) {
	return m.base.GetBlueprintRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetBlueprintRuns(ctx context.Context, params *svc.GetBlueprintRunsInput, optFns ...func(*svc.Options)) (*svc.GetBlueprintRunsOutput, error) {
	return m.base.GetBlueprintRuns(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetCatalogImportStatus(ctx context.Context, params *svc.GetCatalogImportStatusInput, optFns ...func(*svc.Options)) (*svc.GetCatalogImportStatusOutput, error) {
	return m.base.GetCatalogImportStatus(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetClassifier(ctx context.Context, params *svc.GetClassifierInput, optFns ...func(*svc.Options)) (*svc.GetClassifierOutput, error) {
	return m.base.GetClassifier(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetClassifiers(ctx context.Context, params *svc.GetClassifiersInput, optFns ...func(*svc.Options)) (*svc.GetClassifiersOutput, error) {
	return m.base.GetClassifiers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetColumnStatisticsForPartition(ctx context.Context, params *svc.GetColumnStatisticsForPartitionInput, optFns ...func(*svc.Options)) (*svc.GetColumnStatisticsForPartitionOutput, error) {
	return m.base.GetColumnStatisticsForPartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetColumnStatisticsForTable(ctx context.Context, params *svc.GetColumnStatisticsForTableInput, optFns ...func(*svc.Options)) (*svc.GetColumnStatisticsForTableOutput, error) {
	return m.base.GetColumnStatisticsForTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetConnection(ctx context.Context, params *svc.GetConnectionInput, optFns ...func(*svc.Options)) (*svc.GetConnectionOutput, error) {
	return m.base.GetConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetConnections(ctx context.Context, params *svc.GetConnectionsInput, optFns ...func(*svc.Options)) (*svc.GetConnectionsOutput, error) {
	return m.base.GetConnections(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetCrawler(ctx context.Context, params *svc.GetCrawlerInput, optFns ...func(*svc.Options)) (*svc.GetCrawlerOutput, error) {
	return m.base.GetCrawler(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetCrawlerMetrics(ctx context.Context, params *svc.GetCrawlerMetricsInput, optFns ...func(*svc.Options)) (*svc.GetCrawlerMetricsOutput, error) {
	return m.base.GetCrawlerMetrics(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetCrawlers(ctx context.Context, params *svc.GetCrawlersInput, optFns ...func(*svc.Options)) (*svc.GetCrawlersOutput, error) {
	return m.base.GetCrawlers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetCustomEntityType(ctx context.Context, params *svc.GetCustomEntityTypeInput, optFns ...func(*svc.Options)) (*svc.GetCustomEntityTypeOutput, error) {
	return m.base.GetCustomEntityType(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDataCatalogEncryptionSettings(ctx context.Context, params *svc.GetDataCatalogEncryptionSettingsInput, optFns ...func(*svc.Options)) (*svc.GetDataCatalogEncryptionSettingsOutput, error) {
	return m.base.GetDataCatalogEncryptionSettings(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDataQualityResult(ctx context.Context, params *svc.GetDataQualityResultInput, optFns ...func(*svc.Options)) (*svc.GetDataQualityResultOutput, error) {
	return m.base.GetDataQualityResult(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDataQualityRuleRecommendationRun(ctx context.Context, params *svc.GetDataQualityRuleRecommendationRunInput, optFns ...func(*svc.Options)) (*svc.GetDataQualityRuleRecommendationRunOutput, error) {
	return m.base.GetDataQualityRuleRecommendationRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDataQualityRuleset(ctx context.Context, params *svc.GetDataQualityRulesetInput, optFns ...func(*svc.Options)) (*svc.GetDataQualityRulesetOutput, error) {
	return m.base.GetDataQualityRuleset(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDataQualityRulesetEvaluationRun(ctx context.Context, params *svc.GetDataQualityRulesetEvaluationRunInput, optFns ...func(*svc.Options)) (*svc.GetDataQualityRulesetEvaluationRunOutput, error) {
	return m.base.GetDataQualityRulesetEvaluationRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDatabase(ctx context.Context, params *svc.GetDatabaseInput, optFns ...func(*svc.Options)) (*svc.GetDatabaseOutput, error) {
	return m.base.GetDatabase(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDatabases(ctx context.Context, params *svc.GetDatabasesInput, optFns ...func(*svc.Options)) (*svc.GetDatabasesOutput, error) {
	return m.base.GetDatabases(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDataflowGraph(ctx context.Context, params *svc.GetDataflowGraphInput, optFns ...func(*svc.Options)) (*svc.GetDataflowGraphOutput, error) {
	return m.base.GetDataflowGraph(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDevEndpoint(ctx context.Context, params *svc.GetDevEndpointInput, optFns ...func(*svc.Options)) (*svc.GetDevEndpointOutput, error) {
	return m.base.GetDevEndpoint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetDevEndpoints(ctx context.Context, params *svc.GetDevEndpointsInput, optFns ...func(*svc.Options)) (*svc.GetDevEndpointsOutput, error) {
	return m.base.GetDevEndpoints(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetJob(ctx context.Context, params *svc.GetJobInput, optFns ...func(*svc.Options)) (*svc.GetJobOutput, error) {
	return m.base.GetJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetJobBookmark(ctx context.Context, params *svc.GetJobBookmarkInput, optFns ...func(*svc.Options)) (*svc.GetJobBookmarkOutput, error) {
	return m.base.GetJobBookmark(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetJobRun(ctx context.Context, params *svc.GetJobRunInput, optFns ...func(*svc.Options)) (*svc.GetJobRunOutput, error) {
	return m.base.GetJobRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetJobRuns(ctx context.Context, params *svc.GetJobRunsInput, optFns ...func(*svc.Options)) (*svc.GetJobRunsOutput, error) {
	return m.base.GetJobRuns(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetJobs(ctx context.Context, params *svc.GetJobsInput, optFns ...func(*svc.Options)) (*svc.GetJobsOutput, error) {
	return m.base.GetJobs(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetMLTaskRun(ctx context.Context, params *svc.GetMLTaskRunInput, optFns ...func(*svc.Options)) (*svc.GetMLTaskRunOutput, error) {
	return m.base.GetMLTaskRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetMLTaskRuns(ctx context.Context, params *svc.GetMLTaskRunsInput, optFns ...func(*svc.Options)) (*svc.GetMLTaskRunsOutput, error) {
	return m.base.GetMLTaskRuns(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetMLTransform(ctx context.Context, params *svc.GetMLTransformInput, optFns ...func(*svc.Options)) (*svc.GetMLTransformOutput, error) {
	return m.base.GetMLTransform(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetMLTransforms(ctx context.Context, params *svc.GetMLTransformsInput, optFns ...func(*svc.Options)) (*svc.GetMLTransformsOutput, error) {
	return m.base.GetMLTransforms(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetMapping(ctx context.Context, params *svc.GetMappingInput, optFns ...func(*svc.Options)) (*svc.GetMappingOutput, error) {
	return m.base.GetMapping(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetPartition(ctx context.Context, params *svc.GetPartitionInput, optFns ...func(*svc.Options)) (*svc.GetPartitionOutput, error) {
	return m.base.GetPartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetPartitionIndexes(ctx context.Context, params *svc.GetPartitionIndexesInput, optFns ...func(*svc.Options)) (*svc.GetPartitionIndexesOutput, error) {
	return m.base.GetPartitionIndexes(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetPartitions(ctx context.Context, params *svc.GetPartitionsInput, optFns ...func(*svc.Options)) (*svc.GetPartitionsOutput, error) {
	return m.base.GetPartitions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetPlan(ctx context.Context, params *svc.GetPlanInput, optFns ...func(*svc.Options)) (*svc.GetPlanOutput, error) {
	return m.base.GetPlan(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetRegistry(ctx context.Context, params *svc.GetRegistryInput, optFns ...func(*svc.Options)) (*svc.GetRegistryOutput, error) {
	return m.base.GetRegistry(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetResourcePolicies(ctx context.Context, params *svc.GetResourcePoliciesInput, optFns ...func(*svc.Options)) (*svc.GetResourcePoliciesOutput, error) {
	return m.base.GetResourcePolicies(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetResourcePolicy(ctx context.Context, params *svc.GetResourcePolicyInput, optFns ...func(*svc.Options)) (*svc.GetResourcePolicyOutput, error) {
	return m.base.GetResourcePolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSchema(ctx context.Context, params *svc.GetSchemaInput, optFns ...func(*svc.Options)) (*svc.GetSchemaOutput, error) {
	return m.base.GetSchema(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSchemaByDefinition(ctx context.Context, params *svc.GetSchemaByDefinitionInput, optFns ...func(*svc.Options)) (*svc.GetSchemaByDefinitionOutput, error) {
	return m.base.GetSchemaByDefinition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSchemaVersion(ctx context.Context, params *svc.GetSchemaVersionInput, optFns ...func(*svc.Options)) (*svc.GetSchemaVersionOutput, error) {
	return m.base.GetSchemaVersion(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSchemaVersionsDiff(ctx context.Context, params *svc.GetSchemaVersionsDiffInput, optFns ...func(*svc.Options)) (*svc.GetSchemaVersionsDiffOutput, error) {
	return m.base.GetSchemaVersionsDiff(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSecurityConfiguration(ctx context.Context, params *svc.GetSecurityConfigurationInput, optFns ...func(*svc.Options)) (*svc.GetSecurityConfigurationOutput, error) {
	return m.base.GetSecurityConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSecurityConfigurations(ctx context.Context, params *svc.GetSecurityConfigurationsInput, optFns ...func(*svc.Options)) (*svc.GetSecurityConfigurationsOutput, error) {
	return m.base.GetSecurityConfigurations(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetSession(ctx context.Context, params *svc.GetSessionInput, optFns ...func(*svc.Options)) (*svc.GetSessionOutput, error) {
	return m.base.GetSession(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetStatement(ctx context.Context, params *svc.GetStatementInput, optFns ...func(*svc.Options)) (*svc.GetStatementOutput, error) {
	return m.base.GetStatement(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTable(ctx context.Context, params *svc.GetTableInput, optFns ...func(*svc.Options)) (*svc.GetTableOutput, error) {
	return m.base.GetTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTableVersion(ctx context.Context, params *svc.GetTableVersionInput, optFns ...func(*svc.Options)) (*svc.GetTableVersionOutput, error) {
	return m.base.GetTableVersion(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTableVersions(ctx context.Context, params *svc.GetTableVersionsInput, optFns ...func(*svc.Options)) (*svc.GetTableVersionsOutput, error) {
	return m.base.GetTableVersions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTables(ctx context.Context, params *svc.GetTablesInput, optFns ...func(*svc.Options)) (*svc.GetTablesOutput, error) {
	return m.base.GetTables(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTags(ctx context.Context, params *svc.GetTagsInput, optFns ...func(*svc.Options)) (*svc.GetTagsOutput, error) {
	return m.base.GetTags(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTrigger(ctx context.Context, params *svc.GetTriggerInput, optFns ...func(*svc.Options)) (*svc.GetTriggerOutput, error) {
	return m.base.GetTrigger(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetTriggers(ctx context.Context, params *svc.GetTriggersInput, optFns ...func(*svc.Options)) (*svc.GetTriggersOutput, error) {
	return m.base.GetTriggers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetUnfilteredPartitionMetadata(ctx context.Context, params *svc.GetUnfilteredPartitionMetadataInput, optFns ...func(*svc.Options)) (*svc.GetUnfilteredPartitionMetadataOutput, error) {
	return m.base.GetUnfilteredPartitionMetadata(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetUnfilteredPartitionsMetadata(ctx context.Context, params *svc.GetUnfilteredPartitionsMetadataInput, optFns ...func(*svc.Options)) (*svc.GetUnfilteredPartitionsMetadataOutput, error) {
	return m.base.GetUnfilteredPartitionsMetadata(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetUnfilteredTableMetadata(ctx context.Context, params *svc.GetUnfilteredTableMetadataInput, optFns ...func(*svc.Options)) (*svc.GetUnfilteredTableMetadataOutput, error) {
	return m.base.GetUnfilteredTableMetadata(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetUserDefinedFunction(ctx context.Context, params *svc.GetUserDefinedFunctionInput, optFns ...func(*svc.Options)) (*svc.GetUserDefinedFunctionOutput, error) {
	return m.base.GetUserDefinedFunction(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetUserDefinedFunctions(ctx context.Context, params *svc.GetUserDefinedFunctionsInput, optFns ...func(*svc.Options)) (*svc.GetUserDefinedFunctionsOutput, error) {
	return m.base.GetUserDefinedFunctions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetWorkflow(ctx context.Context, params *svc.GetWorkflowInput, optFns ...func(*svc.Options)) (*svc.GetWorkflowOutput, error) {
	return m.base.GetWorkflow(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetWorkflowRun(ctx context.Context, params *svc.GetWorkflowRunInput, optFns ...func(*svc.Options)) (*svc.GetWorkflowRunOutput, error) {
	return m.base.GetWorkflowRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetWorkflowRunProperties(ctx context.Context, params *svc.GetWorkflowRunPropertiesInput, optFns ...func(*svc.Options)) (*svc.GetWorkflowRunPropertiesOutput, error) {
	return m.base.GetWorkflowRunProperties(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) GetWorkflowRuns(ctx context.Context, params *svc.GetWorkflowRunsInput, optFns ...func(*svc.Options)) (*svc.GetWorkflowRunsOutput, error) {
	return m.base.GetWorkflowRuns(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ImportCatalogToGlue(ctx context.Context, params *svc.ImportCatalogToGlueInput, optFns ...func(*svc.Options)) (*svc.ImportCatalogToGlueOutput, error) {
	return m.base.ImportCatalogToGlue(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListBlueprints(ctx context.Context, params *svc.ListBlueprintsInput, optFns ...func(*svc.Options)) (*svc.ListBlueprintsOutput, error) {
	return m.base.ListBlueprints(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListCrawlers(ctx context.Context, params *svc.ListCrawlersInput, optFns ...func(*svc.Options)) (*svc.ListCrawlersOutput, error) {
	return m.base.ListCrawlers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListCrawls(ctx context.Context, params *svc.ListCrawlsInput, optFns ...func(*svc.Options)) (*svc.ListCrawlsOutput, error) {
	return m.base.ListCrawls(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListCustomEntityTypes(ctx context.Context, params *svc.ListCustomEntityTypesInput, optFns ...func(*svc.Options)) (*svc.ListCustomEntityTypesOutput, error) {
	return m.base.ListCustomEntityTypes(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListDataQualityResults(ctx context.Context, params *svc.ListDataQualityResultsInput, optFns ...func(*svc.Options)) (*svc.ListDataQualityResultsOutput, error) {
	return m.base.ListDataQualityResults(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListDataQualityRuleRecommendationRuns(ctx context.Context, params *svc.ListDataQualityRuleRecommendationRunsInput, optFns ...func(*svc.Options)) (*svc.ListDataQualityRuleRecommendationRunsOutput, error) {
	return m.base.ListDataQualityRuleRecommendationRuns(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListDataQualityRulesetEvaluationRuns(ctx context.Context, params *svc.ListDataQualityRulesetEvaluationRunsInput, optFns ...func(*svc.Options)) (*svc.ListDataQualityRulesetEvaluationRunsOutput, error) {
	return m.base.ListDataQualityRulesetEvaluationRuns(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListDataQualityRulesets(ctx context.Context, params *svc.ListDataQualityRulesetsInput, optFns ...func(*svc.Options)) (*svc.ListDataQualityRulesetsOutput, error) {
	return m.base.ListDataQualityRulesets(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListDevEndpoints(ctx context.Context, params *svc.ListDevEndpointsInput, optFns ...func(*svc.Options)) (*svc.ListDevEndpointsOutput, error) {
	return m.base.ListDevEndpoints(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListJobs(ctx context.Context, params *svc.ListJobsInput, optFns ...func(*svc.Options)) (*svc.ListJobsOutput, error) {
	return m.base.ListJobs(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListMLTransforms(ctx context.Context, params *svc.ListMLTransformsInput, optFns ...func(*svc.Options)) (*svc.ListMLTransformsOutput, error) {
	return m.base.ListMLTransforms(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListRegistries(ctx context.Context, params *svc.ListRegistriesInput, optFns ...func(*svc.Options)) (*svc.ListRegistriesOutput, error) {
	return m.base.ListRegistries(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListSchemaVersions(ctx context.Context, params *svc.ListSchemaVersionsInput, optFns ...func(*svc.Options)) (*svc.ListSchemaVersionsOutput, error) {
	return m.base.ListSchemaVersions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListSchemas(ctx context.Context, params *svc.ListSchemasInput, optFns ...func(*svc.Options)) (*svc.ListSchemasOutput, error) {
	return m.base.ListSchemas(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListSessions(ctx context.Context, params *svc.ListSessionsInput, optFns ...func(*svc.Options)) (*svc.ListSessionsOutput, error) {
	return m.base.ListSessions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListStatements(ctx context.Context, params *svc.ListStatementsInput, optFns ...func(*svc.Options)) (*svc.ListStatementsOutput, error) {
	return m.base.ListStatements(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListTriggers(ctx context.Context, params *svc.ListTriggersInput, optFns ...func(*svc.Options)) (*svc.ListTriggersOutput, error) {
	return m.base.ListTriggers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ListWorkflows(ctx context.Context, params *svc.ListWorkflowsInput, optFns ...func(*svc.Options)) (*svc.ListWorkflowsOutput, error) {
	return m.base.ListWorkflows(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) PutDataCatalogEncryptionSettings(ctx context.Context, params *svc.PutDataCatalogEncryptionSettingsInput, optFns ...func(*svc.Options)) (*svc.PutDataCatalogEncryptionSettingsOutput, error) {
	return m.base.PutDataCatalogEncryptionSettings(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) PutResourcePolicy(ctx context.Context, params *svc.PutResourcePolicyInput, optFns ...func(*svc.Options)) (*svc.PutResourcePolicyOutput, error) {
	return m.base.PutResourcePolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) PutSchemaVersionMetadata(ctx context.Context, params *svc.PutSchemaVersionMetadataInput, optFns ...func(*svc.Options)) (*svc.PutSchemaVersionMetadataOutput, error) {
	return m.base.PutSchemaVersionMetadata(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) PutWorkflowRunProperties(ctx context.Context, params *svc.PutWorkflowRunPropertiesInput, optFns ...func(*svc.Options)) (*svc.PutWorkflowRunPropertiesOutput, error) {
	return m.base.PutWorkflowRunProperties(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) QuerySchemaVersionMetadata(ctx context.Context, params *svc.QuerySchemaVersionMetadataInput, optFns ...func(*svc.Options)) (*svc.QuerySchemaVersionMetadataOutput, error) {
	return m.base.QuerySchemaVersionMetadata(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) RegisterSchemaVersion(ctx context.Context, params *svc.RegisterSchemaVersionInput, optFns ...func(*svc.Options)) (*svc.RegisterSchemaVersionOutput, error) {
	return m.base.RegisterSchemaVersion(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) RemoveSchemaVersionMetadata(ctx context.Context, params *svc.RemoveSchemaVersionMetadataInput, optFns ...func(*svc.Options)) (*svc.RemoveSchemaVersionMetadataOutput, error) {
	return m.base.RemoveSchemaVersionMetadata(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ResetJobBookmark(ctx context.Context, params *svc.ResetJobBookmarkInput, optFns ...func(*svc.Options)) (*svc.ResetJobBookmarkOutput, error) {
	return m.base.ResetJobBookmark(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) ResumeWorkflowRun(ctx context.Context, params *svc.ResumeWorkflowRunInput, optFns ...func(*svc.Options)) (*svc.ResumeWorkflowRunOutput, error) {
	return m.base.ResumeWorkflowRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) RunStatement(ctx context.Context, params *svc.RunStatementInput, optFns ...func(*svc.Options)) (*svc.RunStatementOutput, error) {
	return m.base.RunStatement(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) SearchTables(ctx context.Context, params *svc.SearchTablesInput, optFns ...func(*svc.Options)) (*svc.SearchTablesOutput, error) {
	return m.base.SearchTables(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartBlueprintRun(ctx context.Context, params *svc.StartBlueprintRunInput, optFns ...func(*svc.Options)) (*svc.StartBlueprintRunOutput, error) {
	return m.base.StartBlueprintRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartCrawler(ctx context.Context, params *svc.StartCrawlerInput, optFns ...func(*svc.Options)) (*svc.StartCrawlerOutput, error) {
	return m.base.StartCrawler(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartCrawlerSchedule(ctx context.Context, params *svc.StartCrawlerScheduleInput, optFns ...func(*svc.Options)) (*svc.StartCrawlerScheduleOutput, error) {
	return m.base.StartCrawlerSchedule(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartDataQualityRuleRecommendationRun(ctx context.Context, params *svc.StartDataQualityRuleRecommendationRunInput, optFns ...func(*svc.Options)) (*svc.StartDataQualityRuleRecommendationRunOutput, error) {
	return m.base.StartDataQualityRuleRecommendationRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartDataQualityRulesetEvaluationRun(ctx context.Context, params *svc.StartDataQualityRulesetEvaluationRunInput, optFns ...func(*svc.Options)) (*svc.StartDataQualityRulesetEvaluationRunOutput, error) {
	return m.base.StartDataQualityRulesetEvaluationRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartExportLabelsTaskRun(ctx context.Context, params *svc.StartExportLabelsTaskRunInput, optFns ...func(*svc.Options)) (*svc.StartExportLabelsTaskRunOutput, error) {
	return m.base.StartExportLabelsTaskRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartImportLabelsTaskRun(ctx context.Context, params *svc.StartImportLabelsTaskRunInput, optFns ...func(*svc.Options)) (*svc.StartImportLabelsTaskRunOutput, error) {
	return m.base.StartImportLabelsTaskRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartJobRun(ctx context.Context, params *svc.StartJobRunInput, optFns ...func(*svc.Options)) (*svc.StartJobRunOutput, error) {
	return m.base.StartJobRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartMLEvaluationTaskRun(ctx context.Context, params *svc.StartMLEvaluationTaskRunInput, optFns ...func(*svc.Options)) (*svc.StartMLEvaluationTaskRunOutput, error) {
	return m.base.StartMLEvaluationTaskRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartMLLabelingSetGenerationTaskRun(ctx context.Context, params *svc.StartMLLabelingSetGenerationTaskRunInput, optFns ...func(*svc.Options)) (*svc.StartMLLabelingSetGenerationTaskRunOutput, error) {
	return m.base.StartMLLabelingSetGenerationTaskRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartTrigger(ctx context.Context, params *svc.StartTriggerInput, optFns ...func(*svc.Options)) (*svc.StartTriggerOutput, error) {
	return m.base.StartTrigger(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StartWorkflowRun(ctx context.Context, params *svc.StartWorkflowRunInput, optFns ...func(*svc.Options)) (*svc.StartWorkflowRunOutput, error) {
	return m.base.StartWorkflowRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StopCrawler(ctx context.Context, params *svc.StopCrawlerInput, optFns ...func(*svc.Options)) (*svc.StopCrawlerOutput, error) {
	return m.base.StopCrawler(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StopCrawlerSchedule(ctx context.Context, params *svc.StopCrawlerScheduleInput, optFns ...func(*svc.Options)) (*svc.StopCrawlerScheduleOutput, error) {
	return m.base.StopCrawlerSchedule(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StopSession(ctx context.Context, params *svc.StopSessionInput, optFns ...func(*svc.Options)) (*svc.StopSessionOutput, error) {
	return m.base.StopSession(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StopTrigger(ctx context.Context, params *svc.StopTriggerInput, optFns ...func(*svc.Options)) (*svc.StopTriggerOutput, error) {
	return m.base.StopTrigger(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) StopWorkflowRun(ctx context.Context, params *svc.StopWorkflowRunInput, optFns ...func(*svc.Options)) (*svc.StopWorkflowRunOutput, error) {
	return m.base.StopWorkflowRun(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) TagResource(ctx context.Context, params *svc.TagResourceInput, optFns ...func(*svc.Options)) (*svc.TagResourceOutput, error) {
	return m.base.TagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UntagResource(ctx context.Context, params *svc.UntagResourceInput, optFns ...func(*svc.Options)) (*svc.UntagResourceOutput, error) {
	return m.base.UntagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateBlueprint(ctx context.Context, params *svc.UpdateBlueprintInput, optFns ...func(*svc.Options)) (*svc.UpdateBlueprintOutput, error) {
	return m.base.UpdateBlueprint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateClassifier(ctx context.Context, params *svc.UpdateClassifierInput, optFns ...func(*svc.Options)) (*svc.UpdateClassifierOutput, error) {
	return m.base.UpdateClassifier(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateColumnStatisticsForPartition(ctx context.Context, params *svc.UpdateColumnStatisticsForPartitionInput, optFns ...func(*svc.Options)) (*svc.UpdateColumnStatisticsForPartitionOutput, error) {
	return m.base.UpdateColumnStatisticsForPartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateColumnStatisticsForTable(ctx context.Context, params *svc.UpdateColumnStatisticsForTableInput, optFns ...func(*svc.Options)) (*svc.UpdateColumnStatisticsForTableOutput, error) {
	return m.base.UpdateColumnStatisticsForTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateConnection(ctx context.Context, params *svc.UpdateConnectionInput, optFns ...func(*svc.Options)) (*svc.UpdateConnectionOutput, error) {
	return m.base.UpdateConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateCrawler(ctx context.Context, params *svc.UpdateCrawlerInput, optFns ...func(*svc.Options)) (*svc.UpdateCrawlerOutput, error) {
	return m.base.UpdateCrawler(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateCrawlerSchedule(ctx context.Context, params *svc.UpdateCrawlerScheduleInput, optFns ...func(*svc.Options)) (*svc.UpdateCrawlerScheduleOutput, error) {
	return m.base.UpdateCrawlerSchedule(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateDataQualityRuleset(ctx context.Context, params *svc.UpdateDataQualityRulesetInput, optFns ...func(*svc.Options)) (*svc.UpdateDataQualityRulesetOutput, error) {
	return m.base.UpdateDataQualityRuleset(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateDatabase(ctx context.Context, params *svc.UpdateDatabaseInput, optFns ...func(*svc.Options)) (*svc.UpdateDatabaseOutput, error) {
	return m.base.UpdateDatabase(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateDevEndpoint(ctx context.Context, params *svc.UpdateDevEndpointInput, optFns ...func(*svc.Options)) (*svc.UpdateDevEndpointOutput, error) {
	return m.base.UpdateDevEndpoint(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateJob(ctx context.Context, params *svc.UpdateJobInput, optFns ...func(*svc.Options)) (*svc.UpdateJobOutput, error) {
	return m.base.UpdateJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateJobFromSourceControl(ctx context.Context, params *svc.UpdateJobFromSourceControlInput, optFns ...func(*svc.Options)) (*svc.UpdateJobFromSourceControlOutput, error) {
	return m.base.UpdateJobFromSourceControl(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateMLTransform(ctx context.Context, params *svc.UpdateMLTransformInput, optFns ...func(*svc.Options)) (*svc.UpdateMLTransformOutput, error) {
	return m.base.UpdateMLTransform(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdatePartition(ctx context.Context, params *svc.UpdatePartitionInput, optFns ...func(*svc.Options)) (*svc.UpdatePartitionOutput, error) {
	return m.base.UpdatePartition(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateRegistry(ctx context.Context, params *svc.UpdateRegistryInput, optFns ...func(*svc.Options)) (*svc.UpdateRegistryOutput, error) {
	return m.base.UpdateRegistry(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateSchema(ctx context.Context, params *svc.UpdateSchemaInput, optFns ...func(*svc.Options)) (*svc.UpdateSchemaOutput, error) {
	return m.base.UpdateSchema(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateSourceControlFromJob(ctx context.Context, params *svc.UpdateSourceControlFromJobInput, optFns ...func(*svc.Options)) (*svc.UpdateSourceControlFromJobOutput, error) {
	return m.base.UpdateSourceControlFromJob(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateTable(ctx context.Context, params *svc.UpdateTableInput, optFns ...func(*svc.Options)) (*svc.UpdateTableOutput, error) {
	return m.base.UpdateTable(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateTrigger(ctx context.Context, params *svc.UpdateTriggerInput, optFns ...func(*svc.Options)) (*svc.UpdateTriggerOutput, error) {
	return m.base.UpdateTrigger(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateUserDefinedFunction(ctx context.Context, params *svc.UpdateUserDefinedFunctionInput, optFns ...func(*svc.Options)) (*svc.UpdateUserDefinedFunctionOutput, error) {
	return m.base.UpdateUserDefinedFunction(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Glue) UpdateWorkflow(ctx context.Context, params *svc.UpdateWorkflowInput, optFns ...func(*svc.Options)) (*svc.UpdateWorkflowOutput, error) {
	return m.base.UpdateWorkflow(ctx, params, m.opts(ctx, optFns)...)
}
