// Code generated by hack/gen-multiclient. DO NOT EDIT.

package multi

import (
	"context"

	svc "github.com/aws/aws-sdk-go-v2/service/kafka"

	"github.com/konfig-io/konfig-konector/internal/aws/provider"
)

// Kafka wraps *svc.Client and applies the provider.Scope from the context
// (Region and Credentials) as per-operation options on every call.
type Kafka struct{ base *svc.Client }

// NewKafka wraps base.
func NewKafka(base *svc.Client) *Kafka { return &Kafka{base: base} }

// Base returns the underlying client.
func (m *Kafka) Base() *svc.Client { return m.base }

func (m *Kafka) opts(ctx context.Context, optFns []func(*svc.Options)) []func(*svc.Options) {
	s := provider.ScopeFrom(ctx)
	if s == nil || (s.Region == "" && s.Credentials == nil) {
		return optFns
	}
	out := make([]func(*svc.Options), 0, len(optFns)+1)
	out = append(out, func(o *svc.Options) {
		if s.Region != "" {
			o.Region = s.Region
		}
		if s.Credentials != nil {
			o.Credentials = s.Credentials
		}
	})
	return append(out, optFns...)
}

func (m *Kafka) BatchAssociateScramSecret(ctx context.Context, params *svc.BatchAssociateScramSecretInput, optFns ...func(*svc.Options)) (*svc.BatchAssociateScramSecretOutput, error) {
	return m.base.BatchAssociateScramSecret(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) BatchDisassociateScramSecret(ctx context.Context, params *svc.BatchDisassociateScramSecretInput, optFns ...func(*svc.Options)) (*svc.BatchDisassociateScramSecretOutput, error) {
	return m.base.BatchDisassociateScramSecret(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) CreateCluster(ctx context.Context, params *svc.CreateClusterInput, optFns ...func(*svc.Options)) (*svc.CreateClusterOutput, error) {
	return m.base.CreateCluster(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) CreateClusterV2(ctx context.Context, params *svc.CreateClusterV2Input, optFns ...func(*svc.Options)) (*svc.CreateClusterV2Output, error) {
	return m.base.CreateClusterV2(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) CreateConfiguration(ctx context.Context, params *svc.CreateConfigurationInput, optFns ...func(*svc.Options)) (*svc.CreateConfigurationOutput, error) {
	return m.base.CreateConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) CreateReplicator(ctx context.Context, params *svc.CreateReplicatorInput, optFns ...func(*svc.Options)) (*svc.CreateReplicatorOutput, error) {
	return m.base.CreateReplicator(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) CreateVpcConnection(ctx context.Context, params *svc.CreateVpcConnectionInput, optFns ...func(*svc.Options)) (*svc.CreateVpcConnectionOutput, error) {
	return m.base.CreateVpcConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DeleteCluster(ctx context.Context, params *svc.DeleteClusterInput, optFns ...func(*svc.Options)) (*svc.DeleteClusterOutput, error) {
	return m.base.DeleteCluster(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DeleteClusterPolicy(ctx context.Context, params *svc.DeleteClusterPolicyInput, optFns ...func(*svc.Options)) (*svc.DeleteClusterPolicyOutput, error) {
	return m.base.DeleteClusterPolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DeleteConfiguration(ctx context.Context, params *svc.DeleteConfigurationInput, optFns ...func(*svc.Options)) (*svc.DeleteConfigurationOutput, error) {
	return m.base.DeleteConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DeleteReplicator(ctx context.Context, params *svc.DeleteReplicatorInput, optFns ...func(*svc.Options)) (*svc.DeleteReplicatorOutput, error) {
	return m.base.DeleteReplicator(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DeleteVpcConnection(ctx context.Context, params *svc.DeleteVpcConnectionInput, optFns ...func(*svc.Options)) (*svc.DeleteVpcConnectionOutput, error) {
	return m.base.DeleteVpcConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeCluster(ctx context.Context, params *svc.DescribeClusterInput, optFns ...func(*svc.Options)) (*svc.DescribeClusterOutput, error) {
	return m.base.DescribeCluster(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeClusterOperation(ctx context.Context, params *svc.DescribeClusterOperationInput, optFns ...func(*svc.Options)) (*svc.DescribeClusterOperationOutput, error) {
	return m.base.DescribeClusterOperation(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeClusterOperationV2(ctx context.Context, params *svc.DescribeClusterOperationV2Input, optFns ...func(*svc.Options)) (*svc.DescribeClusterOperationV2Output, error) {
	return m.base.DescribeClusterOperationV2(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeClusterV2(ctx context.Context, params *svc.DescribeClusterV2Input, optFns ...func(*svc.Options)) (*svc.DescribeClusterV2Output, error) {
	return m.base.DescribeClusterV2(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeConfiguration(ctx context.Context, params *svc.DescribeConfigurationInput, optFns ...func(*svc.Options)) (*svc.DescribeConfigurationOutput, error) {
	return m.base.DescribeConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeConfigurationRevision(ctx context.Context, params *svc.DescribeConfigurationRevisionInput, optFns ...func(*svc.Options)) (*svc.DescribeConfigurationRevisionOutput, error) {
	return m.base.DescribeConfigurationRevision(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeReplicator(ctx context.Context, params *svc.DescribeReplicatorInput, optFns ...func(*svc.Options)) (*svc.DescribeReplicatorOutput, error) {
	return m.base.DescribeReplicator(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) DescribeVpcConnection(ctx context.Context, params *svc.DescribeVpcConnectionInput, optFns ...func(*svc.Options)) (*svc.DescribeVpcConnectionOutput, error) {
	return m.base.DescribeVpcConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) GetBootstrapBrokers(ctx context.Context, params *svc.GetBootstrapBrokersInput, optFns ...func(*svc.Options)) (*svc.GetBootstrapBrokersOutput, error) {
	return m.base.GetBootstrapBrokers(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) GetClusterPolicy(ctx context.Context, params *svc.GetClusterPolicyInput, optFns ...func(*svc.Options)) (*svc.GetClusterPolicyOutput, error) {
	return m.base.GetClusterPolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) GetCompatibleKafkaVersions(ctx context.Context, params *svc.GetCompatibleKafkaVersionsInput, optFns ...func(*svc.Options)) (*svc.GetCompatibleKafkaVersionsOutput, error) {
	return m.base.GetCompatibleKafkaVersions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListClientVpcConnections(ctx context.Context, params *svc.ListClientVpcConnectionsInput, optFns ...func(*svc.Options)) (*svc.ListClientVpcConnectionsOutput, error) {
	return m.base.ListClientVpcConnections(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListClusterOperations(ctx context.Context, params *svc.ListClusterOperationsInput, optFns ...func(*svc.Options)) (*svc.ListClusterOperationsOutput, error) {
	return m.base.ListClusterOperations(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListClusterOperationsV2(ctx context.Context, params *svc.ListClusterOperationsV2Input, optFns ...func(*svc.Options)) (*svc.ListClusterOperationsV2Output, error) {
	return m.base.ListClusterOperationsV2(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListClusters(ctx context.Context, params *svc.ListClustersInput, optFns ...func(*svc.Options)) (*svc.ListClustersOutput, error) {
	return m.base.ListClusters(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListClustersV2(ctx context.Context, params *svc.ListClustersV2Input, optFns ...func(*svc.Options)) (*svc.ListClustersV2Output, error) {
	return m.base.ListClustersV2(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListConfigurationRevisions(ctx context.Context, params *svc.ListConfigurationRevisionsInput, optFns ...func(*svc.Options)) (*svc.ListConfigurationRevisionsOutput, error) {
	return m.base.ListConfigurationRevisions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListConfigurations(ctx context.Context, params *svc.ListConfigurationsInput, optFns ...func(*svc.Options)) (*svc.ListConfigurationsOutput, error) {
	return m.base.ListConfigurations(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListKafkaVersions(ctx context.Context, params *svc.ListKafkaVersionsInput, optFns ...func(*svc.Options)) (*svc.ListKafkaVersionsOutput, error) {
	return m.base.ListKafkaVersions(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListNodes(ctx context.Context, params *svc.ListNodesInput, optFns ...func(*svc.Options)) (*svc.ListNodesOutput, error) {
	return m.base.ListNodes(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListReplicators(ctx context.Context, params *svc.ListReplicatorsInput, optFns ...func(*svc.Options)) (*svc.ListReplicatorsOutput, error) {
	return m.base.ListReplicators(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListScramSecrets(ctx context.Context, params *svc.ListScramSecretsInput, optFns ...func(*svc.Options)) (*svc.ListScramSecretsOutput, error) {
	return m.base.ListScramSecrets(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListTagsForResource(ctx context.Context, params *svc.ListTagsForResourceInput, optFns ...func(*svc.Options)) (*svc.ListTagsForResourceOutput, error) {
	return m.base.ListTagsForResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) ListVpcConnections(ctx context.Context, params *svc.ListVpcConnectionsInput, optFns ...func(*svc.Options)) (*svc.ListVpcConnectionsOutput, error) {
	return m.base.ListVpcConnections(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) PutClusterPolicy(ctx context.Context, params *svc.PutClusterPolicyInput, optFns ...func(*svc.Options)) (*svc.PutClusterPolicyOutput, error) {
	return m.base.PutClusterPolicy(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) RebootBroker(ctx context.Context, params *svc.RebootBrokerInput, optFns ...func(*svc.Options)) (*svc.RebootBrokerOutput, error) {
	return m.base.RebootBroker(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) RejectClientVpcConnection(ctx context.Context, params *svc.RejectClientVpcConnectionInput, optFns ...func(*svc.Options)) (*svc.RejectClientVpcConnectionOutput, error) {
	return m.base.RejectClientVpcConnection(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) TagResource(ctx context.Context, params *svc.TagResourceInput, optFns ...func(*svc.Options)) (*svc.TagResourceOutput, error) {
	return m.base.TagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UntagResource(ctx context.Context, params *svc.UntagResourceInput, optFns ...func(*svc.Options)) (*svc.UntagResourceOutput, error) {
	return m.base.UntagResource(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateBrokerCount(ctx context.Context, params *svc.UpdateBrokerCountInput, optFns ...func(*svc.Options)) (*svc.UpdateBrokerCountOutput, error) {
	return m.base.UpdateBrokerCount(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateBrokerStorage(ctx context.Context, params *svc.UpdateBrokerStorageInput, optFns ...func(*svc.Options)) (*svc.UpdateBrokerStorageOutput, error) {
	return m.base.UpdateBrokerStorage(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateBrokerType(ctx context.Context, params *svc.UpdateBrokerTypeInput, optFns ...func(*svc.Options)) (*svc.UpdateBrokerTypeOutput, error) {
	return m.base.UpdateBrokerType(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateClusterConfiguration(ctx context.Context, params *svc.UpdateClusterConfigurationInput, optFns ...func(*svc.Options)) (*svc.UpdateClusterConfigurationOutput, error) {
	return m.base.UpdateClusterConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateClusterKafkaVersion(ctx context.Context, params *svc.UpdateClusterKafkaVersionInput, optFns ...func(*svc.Options)) (*svc.UpdateClusterKafkaVersionOutput, error) {
	return m.base.UpdateClusterKafkaVersion(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateConfiguration(ctx context.Context, params *svc.UpdateConfigurationInput, optFns ...func(*svc.Options)) (*svc.UpdateConfigurationOutput, error) {
	return m.base.UpdateConfiguration(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateConnectivity(ctx context.Context, params *svc.UpdateConnectivityInput, optFns ...func(*svc.Options)) (*svc.UpdateConnectivityOutput, error) {
	return m.base.UpdateConnectivity(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateMonitoring(ctx context.Context, params *svc.UpdateMonitoringInput, optFns ...func(*svc.Options)) (*svc.UpdateMonitoringOutput, error) {
	return m.base.UpdateMonitoring(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateReplicationInfo(ctx context.Context, params *svc.UpdateReplicationInfoInput, optFns ...func(*svc.Options)) (*svc.UpdateReplicationInfoOutput, error) {
	return m.base.UpdateReplicationInfo(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateSecurity(ctx context.Context, params *svc.UpdateSecurityInput, optFns ...func(*svc.Options)) (*svc.UpdateSecurityOutput, error) {
	return m.base.UpdateSecurity(ctx, params, m.opts(ctx, optFns)...)
}

func (m *Kafka) UpdateStorage(ctx context.Context, params *svc.UpdateStorageInput, optFns ...func(*svc.Options)) (*svc.UpdateStorageOutput, error) {
	return m.base.UpdateStorage(ctx, params, m.opts(ctx, optFns)...)
}
