# permissions for end users to edit hostedzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hostedzone-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: konfig-konector
    app.kubernetes.io/part-of: konfig-konector
    app.kubernetes.io/managed-by: kustomize
  name: hostedzone-editor-role
rules:
- apiGroups:
  - aws.konfig.io
  resources:
  - hostedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.konfig.io
  resources:
  - hostedzones/status
  verbs:
  - get
