apiVersion: aws.konfig.io/v1alpha1
kind: IAMPolicy
metadata:
  labels:
    app.kubernetes.io/name: iampolicy
    app.kubernetes.io/instance: iampolicy-sample
    app.kubernetes.io/part-of: konfig-konector
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: konfig-konector
  name: iampolicy-sample
spec:
  # TODO(user): Add fields here
