apiVersion: aws.konfig.io/v1alpha1
kind: IAMPolicyAttachment
metadata:
  labels:
    app.kubernetes.io/name: iampolicyattachment
    app.kubernetes.io/instance: iampolicyattachment-sample
    app.kubernetes.io/part-of: konfig-konector
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: konfig-konector
  name: iampolicyattachment-sample
spec:
  # TODO(user): Add fields here
