## Append samples of your project ##
resources:
- aws_v1alpha1_iamrole.yaml
- aws_v1alpha1_iampolicy.yaml
- aws_v1alpha1_iampolicyattachment.yaml
- aws_v1alpha1_iamrolepolicy.yaml
- aws_v1alpha1_podidentityassociation.yaml
- aws_v1alpha1_hostedzone.yaml
- aws_v1alpha1_recordset.yaml
- aws_v1alpha1_healthcheck.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
