/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// SSMQuickSetupConfigurationManagerSpec is the desired state of AWS::SSMQuickSetup::ConfigurationManager.
type SSMQuickSetupConfigurationManagerSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	ConfigurationDefinitions []SSMQuickSetupConfigurationManagerConfigurationDefinition `json:"configurationDefinitions" cfn:"ConfigurationDefinitions"`

	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// +optional
	Name string `json:"name,omitempty" cfn:"Name"`

	// +optional
	Tags map[string]string `json:"tags,omitempty" cfn:"Tags"`
}

// SSMQuickSetupConfigurationManagerStatus is the observed state of AWS::SSMQuickSetup::ConfigurationManager.
type SSMQuickSetupConfigurationManagerStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Read-only: reported by AWS after creation.
	// +optional
	LastModifiedAt string `json:"lastModifiedAt,omitempty" cfn:"LastModifiedAt"`

	// Read-only: reported by AWS after creation.
	// +optional
	ManagerArn string `json:"managerArn,omitempty" cfn:"ManagerArn"`

	// Read-only: reported by AWS after creation.
	// +optional
	StatusSummaries []SSMQuickSetupConfigurationManagerStatusSummary `json:"statusSummaries,omitempty" cfn:"StatusSummaries"`
}

// SSMQuickSetupConfigurationManager manages AWS::SSMQuickSetup::ConfigurationManager through the AWS Cloud
// Control API. Definition of AWS::SSMQuickSetup::ConfigurationManager Resource Type
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type SSMQuickSetupConfigurationManager struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SSMQuickSetupConfigurationManagerSpec   `json:"spec,omitempty"`
	Status SSMQuickSetupConfigurationManagerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SSMQuickSetupConfigurationManagerList contains a list of SSMQuickSetupConfigurationManager.
type SSMQuickSetupConfigurationManagerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SSMQuickSetupConfigurationManager `json:"items"`
}

func (o *SSMQuickSetupConfigurationManager) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *SSMQuickSetupConfigurationManager) CloudControlTypeName() string {
	return "AWS::SSMQuickSetup::ConfigurationManager"
}
func (o *SSMQuickSetupConfigurationManager) CloudControlSpec() interface{} { return &o.Spec }
func (o *SSMQuickSetupConfigurationManager) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *SSMQuickSetupConfigurationManager) CloudControlObserved() interface{} { return &o.Status }
func (o *SSMQuickSetupConfigurationManager) SetProviderStatus(p *ProviderStatus) {
	o.Status.AWSProvider = p
}

// SSMQuickSetupConfigurationManagerConfigurationDefinition is a nested property type of AWS::SSMQuickSetup::ConfigurationManager.
type SSMQuickSetupConfigurationManagerConfigurationDefinition struct {
	Type string `json:"type" cfn:"Type"`

	Parameters map[string]string `json:"parameters" cfn:"Parameters"`

	// +kubebuilder:validation:MaxLength=128
	// +optional
	TypeVersion string `json:"typeVersion,omitempty" cfn:"TypeVersion"`

	// +kubebuilder:validation:MaxLength=256
	// +optional
	LocalDeploymentExecutionRoleName string `json:"localDeploymentExecutionRoleName,omitempty" cfn:"LocalDeploymentExecutionRoleName"`

	// +optional
	LocalDeploymentAdministrationRoleArn string `json:"localDeploymentAdministrationRoleArn,omitempty" cfn:"LocalDeploymentAdministrationRoleArn"`

	// +optional
	Id string `json:"id,omitempty" cfn:"id"`
}

// SSMQuickSetupConfigurationManagerStatusSummary is a nested property type of AWS::SSMQuickSetup::ConfigurationManager.
type SSMQuickSetupConfigurationManagerStatusSummary struct {
	// +kubebuilder:validation:Enum=Deployment;AsyncExecutions
	StatusType string `json:"statusType" cfn:"StatusType"`

	// +kubebuilder:validation:Enum=INITIALIZING;DEPLOYING;SUCCEEDED;DELETING;STOPPING;FAILED;STOPPED;DELETE_FAILED;STOP_FAILED;NONE
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// +optional
	StatusMessage string `json:"statusMessage,omitempty" cfn:"StatusMessage"`

	LastUpdatedAt string `json:"lastUpdatedAt" cfn:"LastUpdatedAt"`

	// +optional
	StatusDetails map[string]string `json:"statusDetails,omitempty" cfn:"StatusDetails"`
}

// SSMQuickSetupLifecycleAutomationSpec is the desired state of AWS::SSMQuickSetup::LifecycleAutomation.
type SSMQuickSetupLifecycleAutomationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The name of the Automation document to execute
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=500
	AutomationDocument string `json:"automationDocument" cfn:"AutomationDocument"`

	AutomationParameters map[string][]string `json:"automationParameters" cfn:"AutomationParameters"`

	// A unique identifier used for generating a unique logical ID for the custom resource
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=64
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="resourceKey is immutable"
	ResourceKey string `json:"resourceKey" cfn:"ResourceKey"`

	// +optional
	Tags map[string]string `json:"tags,omitempty" cfn:"Tags"`
}

// SSMQuickSetupLifecycleAutomationStatus is the observed state of AWS::SSMQuickSetup::LifecycleAutomation.
type SSMQuickSetupLifecycleAutomationStatus struct {
	CloudControlStatus `json:",inline"`

	// The id from the association that is returned when creating the association
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=64
	// +optional
	AssociationId string `json:"associationId,omitempty" cfn:"AssociationId"`
}

// SSMQuickSetupLifecycleAutomation manages AWS::SSMQuickSetup::LifecycleAutomation through the AWS Cloud Control
// API. Resource Type definition for AWS::SSMQuickSetup::LifecycleAutomation that executes SSM Automation
// documents in response to CloudFormation lifecycle events.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type SSMQuickSetupLifecycleAutomation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SSMQuickSetupLifecycleAutomationSpec   `json:"spec,omitempty"`
	Status SSMQuickSetupLifecycleAutomationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SSMQuickSetupLifecycleAutomationList contains a list of SSMQuickSetupLifecycleAutomation.
type SSMQuickSetupLifecycleAutomationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SSMQuickSetupLifecycleAutomation `json:"items"`
}

func (o *SSMQuickSetupLifecycleAutomation) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *SSMQuickSetupLifecycleAutomation) CloudControlTypeName() string {
	return "AWS::SSMQuickSetup::LifecycleAutomation"
}
func (o *SSMQuickSetupLifecycleAutomation) CloudControlSpec() interface{} { return &o.Spec }
func (o *SSMQuickSetupLifecycleAutomation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *SSMQuickSetupLifecycleAutomation) CloudControlObserved() interface{} { return &o.Status }
func (o *SSMQuickSetupLifecycleAutomation) SetProviderStatus(p *ProviderStatus) {
	o.Status.AWSProvider = p
}

func init() {
	SchemeBuilder.Register(&SSMQuickSetupConfigurationManager{}, &SSMQuickSetupConfigurationManagerList{})
	SchemeBuilder.Register(&SSMQuickSetupLifecycleAutomation{}, &SSMQuickSetupLifecycleAutomationList{})
}
