/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// RedshiftEndpointAccessSpec is the desired state of AWS::Redshift::EndpointAccess.
type RedshiftEndpointAccessSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The name of the endpoint.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="endpointName is immutable"
	EndpointName string `json:"endpointName" cfn:"EndpointName"`

	// A list of vpc security group ids to apply to the created endpoint access.
	VpcSecurityGroupIds []string `json:"vpcSecurityGroupIds" cfn:"VpcSecurityGroupIds"`

	// The AWS account ID of the owner of the cluster.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ResourceOwner string `json:"resourceOwner,omitempty" cfn:"ResourceOwner"`

	// The subnet group name where Amazon Redshift chooses to deploy the endpoint.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="subnetGroupName is immutable"
	SubnetGroupName string `json:"subnetGroupName" cfn:"SubnetGroupName"`

	// A unique identifier for the cluster. You use this identifier to refer to the cluster for any subsequent
	// cluster operations such as deleting or modifying. All alphabetical characters must be lower case, no hypens at
	// the end, no two consecutive hyphens. Cluster name should be unique for all clusters within an AWS account
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clusterIdentifier is immutable"
	ClusterIdentifier string `json:"clusterIdentifier" cfn:"ClusterIdentifier"`
}

// RedshiftEndpointAccessStatus is the observed state of AWS::Redshift::EndpointAccess.
type RedshiftEndpointAccessStatus struct {
	CloudControlStatus `json:",inline"`

	// The status of the endpoint.
	// Read-only: reported by AWS after creation.
	// +optional
	EndpointStatus string `json:"endpointStatus,omitempty" cfn:"EndpointStatus"`

	// The connection endpoint for connecting to an Amazon Redshift cluster through the proxy.
	// Read-only: reported by AWS after creation.
	// +optional
	VpcEndpoint *RedshiftEndpointAccessVpcEndpoint `json:"vpcEndpoint,omitempty" cfn:"VpcEndpoint"`

	// The DNS address of the endpoint.
	// Read-only: reported by AWS after creation.
	// +optional
	Address string `json:"address,omitempty" cfn:"Address"`

	// The port number on which the cluster accepts incoming connections.
	// Read-only: reported by AWS after creation.
	// +optional
	Port *int64 `json:"port,omitempty" cfn:"Port"`

	// The time (UTC) that the endpoint was created.
	// Read-only: reported by AWS after creation.
	// +optional
	EndpointCreateTime string `json:"endpointCreateTime,omitempty" cfn:"EndpointCreateTime"`

	// A list of Virtual Private Cloud (VPC) security groups to be associated with the endpoint.
	// Read-only: reported by AWS after creation.
	// +optional
	VpcSecurityGroups []RedshiftEndpointAccessVpcSecurityGroup `json:"vpcSecurityGroups,omitempty" cfn:"VpcSecurityGroups"`
}

// RedshiftEndpointAccess manages AWS::Redshift::EndpointAccess through the AWS Cloud Control API. Resource
// schema for a Redshift-managed VPC endpoint.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type RedshiftEndpointAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedshiftEndpointAccessSpec   `json:"spec,omitempty"`
	Status RedshiftEndpointAccessStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedshiftEndpointAccessList contains a list of RedshiftEndpointAccess.
type RedshiftEndpointAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedshiftEndpointAccess `json:"items"`
}

func (o *RedshiftEndpointAccess) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *RedshiftEndpointAccess) CloudControlTypeName() string {
	return "AWS::Redshift::EndpointAccess"
}
func (o *RedshiftEndpointAccess) CloudControlSpec() interface{} { return &o.Spec }
func (o *RedshiftEndpointAccess) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *RedshiftEndpointAccess) CloudControlObserved() interface{} { return &o.Status }

// RedshiftEndpointAccessVpcEndpoint is a nested property type of AWS::Redshift::EndpointAccess.
type RedshiftEndpointAccessVpcEndpoint struct {
	// The VPC identifier that the endpoint is associated.
	// +optional
	VpcId string `json:"vpcId,omitempty" cfn:"VpcId"`

	// One or more network interfaces of the endpoint. Also known as an interface endpoint.
	// +optional
	NetworkInterfaces []RedshiftEndpointAccessNetworkInterface `json:"networkInterfaces,omitempty" cfn:"NetworkInterfaces"`

	// The connection endpoint ID for connecting an Amazon Redshift cluster through the proxy.
	// +optional
	VpcEndpointId string `json:"vpcEndpointId,omitempty" cfn:"VpcEndpointId"`
}

// RedshiftEndpointAccessNetworkInterface is a nested property type of AWS::Redshift::EndpointAccess.
type RedshiftEndpointAccessNetworkInterface struct {
	// The IPv4 address of the network interface within the subnet.
	// +optional
	PrivateIpAddress string `json:"privateIpAddress,omitempty" cfn:"PrivateIpAddress"`

	// The Availability Zone.
	// +optional
	AvailabilityZone string `json:"availabilityZone,omitempty" cfn:"AvailabilityZone"`

	// The subnet identifier.
	// +optional
	SubnetId string `json:"subnetId,omitempty" cfn:"SubnetId"`

	// The network interface identifier.
	// +optional
	NetworkInterfaceId string `json:"networkInterfaceId,omitempty" cfn:"NetworkInterfaceId"`
}

// RedshiftEndpointAccessVpcSecurityGroup is a nested property type of AWS::Redshift::EndpointAccess.
type RedshiftEndpointAccessVpcSecurityGroup struct {
	// The status of the VPC security group.
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// The identifier of the VPC security group.
	// +optional
	VpcSecurityGroupId string `json:"vpcSecurityGroupId,omitempty" cfn:"VpcSecurityGroupId"`
}

// RedshiftEndpointAuthorizationSpec is the desired state of AWS::Redshift::EndpointAuthorization.
type RedshiftEndpointAuthorizationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The target AWS account ID to grant or revoke access for.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="account is immutable"
	Account string `json:"account" cfn:"Account"`

	// Indicates whether to force the revoke action. If true, the Redshift-managed VPC endpoints associated with the
	// endpoint authorization are also deleted.
	// +optional
	Force *bool `json:"force,omitempty" cfn:"Force"`

	// The virtual private cloud (VPC) identifiers to grant or revoke access to.
	// +optional
	VpcIds []string `json:"vpcIds,omitempty" cfn:"VpcIds"`

	// The cluster identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clusterIdentifier is immutable"
	ClusterIdentifier string `json:"clusterIdentifier" cfn:"ClusterIdentifier"`
}

// RedshiftEndpointAuthorizationStatus is the observed state of AWS::Redshift::EndpointAuthorization.
type RedshiftEndpointAuthorizationStatus struct {
	CloudControlStatus `json:",inline"`

	// The status of the authorization action.
	// Read-only: reported by AWS after creation.
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// The AWS account ID of the grantee of the cluster.
	// Read-only: reported by AWS after creation.
	// +optional
	Grantee string `json:"grantee,omitempty" cfn:"Grantee"`

	// The AWS account ID of the cluster owner.
	// Read-only: reported by AWS after creation.
	// +optional
	Grantor string `json:"grantor,omitempty" cfn:"Grantor"`

	// The number of Redshift-managed VPC endpoints created for the authorization.
	// Read-only: reported by AWS after creation.
	// +optional
	EndpointCount *int64 `json:"endpointCount,omitempty" cfn:"EndpointCount"`

	// The time (UTC) when the authorization was created.
	// Read-only: reported by AWS after creation.
	// +optional
	AuthorizeTime string `json:"authorizeTime,omitempty" cfn:"AuthorizeTime"`

	// The VPCs allowed access to the cluster.
	// Read-only: reported by AWS after creation.
	// +optional
	AllowedVPCs []string `json:"allowedVPCs,omitempty" cfn:"AllowedVPCs"`

	// Indicates whether all VPCs in the grantee account are allowed access to the cluster.
	// Read-only: reported by AWS after creation.
	// +optional
	AllowedAllVPCs *bool `json:"allowedAllVPCs,omitempty" cfn:"AllowedAllVPCs"`

	// The status of the cluster.
	// Read-only: reported by AWS after creation.
	// +optional
	ClusterStatus string `json:"clusterStatus,omitempty" cfn:"ClusterStatus"`
}

// RedshiftEndpointAuthorization manages AWS::Redshift::EndpointAuthorization through the AWS Cloud Control API.
// Describes an endpoint authorization for authorizing Redshift-managed VPC endpoint access to a cluster across
// AWS accounts.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type RedshiftEndpointAuthorization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedshiftEndpointAuthorizationSpec   `json:"spec,omitempty"`
	Status RedshiftEndpointAuthorizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedshiftEndpointAuthorizationList contains a list of RedshiftEndpointAuthorization.
type RedshiftEndpointAuthorizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedshiftEndpointAuthorization `json:"items"`
}

func (o *RedshiftEndpointAuthorization) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *RedshiftEndpointAuthorization) CloudControlTypeName() string {
	return "AWS::Redshift::EndpointAuthorization"
}
func (o *RedshiftEndpointAuthorization) CloudControlSpec() interface{} { return &o.Spec }
func (o *RedshiftEndpointAuthorization) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *RedshiftEndpointAuthorization) CloudControlObserved() interface{} { return &o.Status }

// RedshiftEventSubscriptionSpec is the desired state of AWS::Redshift::EventSubscription.
type RedshiftEventSubscriptionSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The type of source that will be generating the events.
	// +kubebuilder:validation:Enum=cluster;cluster-parameter-group;cluster-security-group;cluster-snapshot;scheduled-action
	// +optional
	SourceType string `json:"sourceType,omitempty" cfn:"SourceType"`

	// Specifies the Amazon Redshift event categories to be published by the event notification subscription.
	// +optional
	EventCategories []string `json:"eventCategories,omitempty" cfn:"EventCategories"`

	// A boolean value; set to true to activate the subscription, and set to false to create the subscription but not
	// activate it.
	// +optional
	Enabled *bool `json:"enabled,omitempty" cfn:"Enabled"`

	// Specifies the Amazon Redshift event severity to be published by the event notification subscription.
	// +kubebuilder:validation:Enum=ERROR;INFO
	// +optional
	Severity string `json:"severity,omitempty" cfn:"Severity"`

	// The name of the Amazon Redshift event notification subscription
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="subscriptionName is immutable"
	SubscriptionName string `json:"subscriptionName" cfn:"SubscriptionName"`

	// A list of one or more identifiers of Amazon Redshift source objects.
	// +optional
	SourceIds []string `json:"sourceIds,omitempty" cfn:"SourceIds"`

	// The Amazon Resource Name (ARN) of the Amazon SNS topic used to transmit the event notifications.
	// +optional
	SnsTopicArn string `json:"snsTopicArn,omitempty" cfn:"SnsTopicArn"`

	// An array of key-value pairs to apply to this resource.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// RedshiftEventSubscriptionStatus is the observed state of AWS::Redshift::EventSubscription.
type RedshiftEventSubscriptionStatus struct {
	CloudControlStatus `json:",inline"`

	// The status of the Amazon Redshift event notification subscription.
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:Enum=active;no-permission;topic-not-exist
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// The name of the Amazon Redshift event notification subscription.
	// Read-only: reported by AWS after creation.
	// +optional
	CustSubscriptionId string `json:"custSubscriptionId,omitempty" cfn:"CustSubscriptionId"`

	// The list of Amazon Redshift event categories specified in the event notification subscription.
	// Read-only: reported by AWS after creation.
	// +optional
	EventCategoriesList []string `json:"eventCategoriesList,omitempty" cfn:"EventCategoriesList"`

	// The AWS account associated with the Amazon Redshift event notification subscription.
	// Read-only: reported by AWS after creation.
	// +optional
	CustomerAwsId string `json:"customerAwsId,omitempty" cfn:"CustomerAwsId"`

	// A list of the sources that publish events to the Amazon Redshift event notification subscription.
	// Read-only: reported by AWS after creation.
	// +optional
	SourceIdsList []string `json:"sourceIdsList,omitempty" cfn:"SourceIdsList"`

	// The date and time the Amazon Redshift event notification subscription was created.
	// Read-only: reported by AWS after creation.
	// +optional
	SubscriptionCreationTime string `json:"subscriptionCreationTime,omitempty" cfn:"SubscriptionCreationTime"`
}

// RedshiftEventSubscription manages AWS::Redshift::EventSubscription through the AWS Cloud Control API. The
// `AWS::Redshift::EventSubscription` resource creates an Amazon Redshift Event Subscription.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type RedshiftEventSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedshiftEventSubscriptionSpec   `json:"spec,omitempty"`
	Status RedshiftEventSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedshiftEventSubscriptionList contains a list of RedshiftEventSubscription.
type RedshiftEventSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedshiftEventSubscription `json:"items"`
}

func (o *RedshiftEventSubscription) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *RedshiftEventSubscription) CloudControlTypeName() string {
	return "AWS::Redshift::EventSubscription"
}
func (o *RedshiftEventSubscription) CloudControlSpec() interface{} { return &o.Spec }
func (o *RedshiftEventSubscription) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *RedshiftEventSubscription) CloudControlObserved() interface{} { return &o.Status }

// RedshiftIntegrationSpec is the desired state of AWS::Redshift::Integration.
type RedshiftIntegrationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The name of the integration.
	// +kubebuilder:validation:MaxLength=64
	// +optional
	IntegrationName string `json:"integrationName,omitempty" cfn:"IntegrationName"`

	// The Amazon Resource Name (ARN) of the database to use as the source for replication
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="sourceArn is immutable"
	SourceArn string `json:"sourceArn" cfn:"SourceArn"`

	// The Amazon Resource Name (ARN) of the Redshift data warehouse to use as the target for replication
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="targetArn is immutable"
	TargetArn string `json:"targetArn" cfn:"TargetArn"`

	// An array of key-value pairs to apply to this resource.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// An KMS key identifier for the key to use to encrypt the integration. If you don't specify an encryption key,
	// the default AWS owned KMS key is used.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	KMSKeyId string `json:"kmsKeyId,omitempty" cfn:"KMSKeyId"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	AdditionalEncryptionContext map[string]string `json:"additionalEncryptionContext,omitempty" cfn:"AdditionalEncryptionContext"`
}

// RedshiftIntegrationStatus is the observed state of AWS::Redshift::Integration.
type RedshiftIntegrationStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the integration.
	// Read-only: reported by AWS after creation.
	// +optional
	IntegrationArn string `json:"integrationArn,omitempty" cfn:"IntegrationArn"`

	// The time (UTC) when the integration was created.
	// Read-only: reported by AWS after creation.
	// +optional
	CreateTime string `json:"createTime,omitempty" cfn:"CreateTime"`
}

// RedshiftIntegration manages AWS::Redshift::Integration through the AWS Cloud Control API. Integration from a
// source AWS service to a Redshift cluster
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type RedshiftIntegration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedshiftIntegrationSpec   `json:"spec,omitempty"`
	Status RedshiftIntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedshiftIntegrationList contains a list of RedshiftIntegration.
type RedshiftIntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedshiftIntegration `json:"items"`
}

func (o *RedshiftIntegration) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *RedshiftIntegration) CloudControlTypeName() string  { return "AWS::Redshift::Integration" }
func (o *RedshiftIntegration) CloudControlSpec() interface{} { return &o.Spec }
func (o *RedshiftIntegration) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *RedshiftIntegration) CloudControlObserved() interface{} { return &o.Status }

// RedshiftScheduledActionSpec is the desired state of AWS::Redshift::ScheduledAction.
type RedshiftScheduledActionSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the scheduled action.
	// +optional
	ScheduledActionDescription string `json:"scheduledActionDescription,omitempty" cfn:"ScheduledActionDescription"`

	// The name of the scheduled action. The name must be unique within an account.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="scheduledActionName is immutable"
	ScheduledActionName string `json:"scheduledActionName" cfn:"ScheduledActionName"`

	// The end time in UTC of the scheduled action. After this time, the scheduled action does not trigger.
	// +optional
	EndTime string `json:"endTime,omitempty" cfn:"EndTime"`

	// The schedule in `at( )` or `cron( )` format.
	// +optional
	Schedule string `json:"schedule,omitempty" cfn:"Schedule"`

	// The IAM role to assume to run the target action.
	// +optional
	IamRole string `json:"iamRole,omitempty" cfn:"IamRole"`

	// The start time in UTC of the scheduled action. Before this time, the scheduled action does not trigger.
	// +optional
	StartTime string `json:"startTime,omitempty" cfn:"StartTime"`

	// If true, the schedule is enabled. If false, the scheduled action does not trigger.
	// +optional
	Enable *bool `json:"enable,omitempty" cfn:"Enable"`

	// A JSON format string of the Amazon Redshift API operation with input parameters.
	// +kubebuilder:pruning:PreserveUnknownFields
	// +optional
	TargetAction apiextensionsv1.JSON `json:"targetAction,omitempty" cfn:"TargetAction"`
}

// RedshiftScheduledActionStatus is the observed state of AWS::Redshift::ScheduledAction.
type RedshiftScheduledActionStatus struct {
	CloudControlStatus `json:",inline"`

	// The state of the scheduled action.
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:Enum=ACTIVE;DISABLED
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// List of times when the scheduled action will run.
	// Read-only: reported by AWS after creation.
	// +optional
	NextInvocations []string `json:"nextInvocations,omitempty" cfn:"NextInvocations"`
}

// RedshiftScheduledAction manages AWS::Redshift::ScheduledAction through the AWS Cloud Control API. The
// `AWS::Redshift::ScheduledAction` resource creates an Amazon Redshift Scheduled Action.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type RedshiftScheduledAction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedshiftScheduledActionSpec   `json:"spec,omitempty"`
	Status RedshiftScheduledActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedshiftScheduledActionList contains a list of RedshiftScheduledAction.
type RedshiftScheduledActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedshiftScheduledAction `json:"items"`
}

func (o *RedshiftScheduledAction) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *RedshiftScheduledAction) CloudControlTypeName() string {
	return "AWS::Redshift::ScheduledAction"
}
func (o *RedshiftScheduledAction) CloudControlSpec() interface{} { return &o.Spec }
func (o *RedshiftScheduledAction) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *RedshiftScheduledAction) CloudControlObserved() interface{} { return &o.Status }

// RedshiftSnapshotScheduleSpec is the desired state of AWS::Redshift::SnapshotSchedule.
type RedshiftSnapshotScheduleSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// A unique identifier for the snapshot schedule. Only alphanumeric characters are allowed.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="scheduleIdentifier is immutable"
	ScheduleIdentifier string `json:"scheduleIdentifier" cfn:"ScheduleIdentifier"`

	// The description of the snapshot schedule.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ScheduleDescription string `json:"scheduleDescription,omitempty" cfn:"ScheduleDescription"`

	// The definition of the snapshot schedule. The definition is made up of schedule expressions, for example
	// "cron(30 12 *)" or "rate(12 hours)".
	ScheduleDefinitions []string `json:"scheduleDefinitions" cfn:"ScheduleDefinitions"`

	// An optional set of tags for the snapshot schedule.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// RedshiftSnapshotScheduleStatus is the observed state of AWS::Redshift::SnapshotSchedule.
type RedshiftSnapshotScheduleStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the snapshot schedule.
	// Read-only: reported by AWS after creation.
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`

	// The number of clusters associated with the schedule.
	// Read-only: reported by AWS after creation.
	// +optional
	AssociatedClusterCount *int64 `json:"associatedClusterCount,omitempty" cfn:"AssociatedClusterCount"`
}

// RedshiftSnapshotSchedule manages AWS::Redshift::SnapshotSchedule through the AWS Cloud Control API. Creates a
// snapshot schedule that lets you set up automatic snapshots of your Amazon Redshift cluster at regular
// intervals.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type RedshiftSnapshotSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedshiftSnapshotScheduleSpec   `json:"spec,omitempty"`
	Status RedshiftSnapshotScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedshiftSnapshotScheduleList contains a list of RedshiftSnapshotSchedule.
type RedshiftSnapshotScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedshiftSnapshotSchedule `json:"items"`
}

func (o *RedshiftSnapshotSchedule) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *RedshiftSnapshotSchedule) CloudControlTypeName() string {
	return "AWS::Redshift::SnapshotSchedule"
}
func (o *RedshiftSnapshotSchedule) CloudControlSpec() interface{} { return &o.Spec }
func (o *RedshiftSnapshotSchedule) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *RedshiftSnapshotSchedule) CloudControlObserved() interface{} { return &o.Status }

func init() {
	SchemeBuilder.Register(&RedshiftEndpointAccess{}, &RedshiftEndpointAccessList{})
	SchemeBuilder.Register(&RedshiftEndpointAuthorization{}, &RedshiftEndpointAuthorizationList{})
	SchemeBuilder.Register(&RedshiftEventSubscription{}, &RedshiftEventSubscriptionList{})
	SchemeBuilder.Register(&RedshiftIntegration{}, &RedshiftIntegrationList{})
	SchemeBuilder.Register(&RedshiftScheduledAction{}, &RedshiftScheduledActionList{})
	SchemeBuilder.Register(&RedshiftSnapshotSchedule{}, &RedshiftSnapshotScheduleList{})
}
