/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// ServiceCatalogAcceptedPortfolioShareSpec is the desired state of AWS::ServiceCatalog::AcceptedPortfolioShare.
type ServiceCatalogAcceptedPortfolioShareSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The language code.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// The portfolio identifier.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=100
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`
}

// ServiceCatalogAcceptedPortfolioShareStatus is the observed state of AWS::ServiceCatalog::AcceptedPortfolioShare.
type ServiceCatalogAcceptedPortfolioShareStatus struct {
	CloudControlStatus `json:",inline"`
}

// ServiceCatalogAcceptedPortfolioShare manages AWS::ServiceCatalog::AcceptedPortfolioShare through the AWS Cloud
// Control API. Resource Type definition for AWS::ServiceCatalog::AcceptedPortfolioShare
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogAcceptedPortfolioShare struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogAcceptedPortfolioShareSpec   `json:"spec,omitempty"`
	Status ServiceCatalogAcceptedPortfolioShareStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogAcceptedPortfolioShareList contains a list of ServiceCatalogAcceptedPortfolioShare.
type ServiceCatalogAcceptedPortfolioShareList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogAcceptedPortfolioShare `json:"items"`
}

func (o *ServiceCatalogAcceptedPortfolioShare) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogAcceptedPortfolioShare) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::AcceptedPortfolioShare"
}
func (o *ServiceCatalogAcceptedPortfolioShare) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogAcceptedPortfolioShare) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogAcceptedPortfolioShare) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogCloudFormationProvisionedProductSpec is the desired state of AWS::ServiceCatalog::CloudFormationProvisionedProduct.
type ServiceCatalogCloudFormationProvisionedProductSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:validation:Enum=en;jp;zh
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	NotificationArns []string `json:"notificationArns,omitempty" cfn:"NotificationArns"`

	// +kubebuilder:validation:MaxLength=100
	// +optional
	PathId string `json:"pathId,omitempty" cfn:"PathId"`

	// +kubebuilder:validation:MaxLength=100
	// +optional
	PathName string `json:"pathName,omitempty" cfn:"PathName"`

	// +kubebuilder:validation:MaxLength=100
	// +optional
	ProductId string `json:"productId,omitempty" cfn:"ProductId"`

	// +kubebuilder:validation:MaxLength=128
	// +optional
	ProductName string `json:"productName,omitempty" cfn:"ProductName"`

	// +kubebuilder:validation:MaxLength=128
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ProvisionedProductName string `json:"provisionedProductName,omitempty" cfn:"ProvisionedProductName"`

	// +kubebuilder:validation:MaxLength=100
	// +optional
	ProvisioningArtifactId string `json:"provisioningArtifactId,omitempty" cfn:"ProvisioningArtifactId"`

	// +optional
	ProvisioningArtifactName string `json:"provisioningArtifactName,omitempty" cfn:"ProvisioningArtifactName"`

	// +optional
	ProvisioningParameters []CFNTag `json:"provisioningParameters,omitempty" cfn:"ProvisioningParameters"`

	// +optional
	ProvisioningPreferences *ServiceCatalogCloudFormationProvisionedProductProvisioningPreferences `json:"provisioningPreferences,omitempty" cfn:"ProvisioningPreferences"`

	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// ServiceCatalogCloudFormationProvisionedProductStatus is the observed state of AWS::ServiceCatalog::CloudFormationProvisionedProduct.
type ServiceCatalogCloudFormationProvisionedProductStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=50
	// +optional
	ProvisionedProductId string `json:"provisionedProductId,omitempty" cfn:"ProvisionedProductId"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=50
	// +optional
	RecordId string `json:"recordId,omitempty" cfn:"RecordId"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=256
	// +optional
	CloudformationStackArn string `json:"cloudformationStackArn,omitempty" cfn:"CloudformationStackArn"`

	// List of key-value pair outputs.
	// Read-only: reported by AWS after creation.
	// +optional
	Outputs map[string]string `json:"outputs,omitempty" cfn:"Outputs"`
}

// ServiceCatalogCloudFormationProvisionedProduct manages AWS::ServiceCatalog::CloudFormationProvisionedProduct
// through the AWS Cloud Control API. Resource Schema for AWS::ServiceCatalog::CloudFormationProvisionedProduct
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogCloudFormationProvisionedProduct struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogCloudFormationProvisionedProductSpec   `json:"spec,omitempty"`
	Status ServiceCatalogCloudFormationProvisionedProductStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogCloudFormationProvisionedProductList contains a list of ServiceCatalogCloudFormationProvisionedProduct.
type ServiceCatalogCloudFormationProvisionedProductList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogCloudFormationProvisionedProduct `json:"items"`
}

func (o *ServiceCatalogCloudFormationProvisionedProduct) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogCloudFormationProvisionedProduct) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
}
func (o *ServiceCatalogCloudFormationProvisionedProduct) CloudControlSpec() interface{} {
	return &o.Spec
}
func (o *ServiceCatalogCloudFormationProvisionedProduct) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogCloudFormationProvisionedProduct) CloudControlObserved() interface{} {
	return &o.Status
}

// ServiceCatalogCloudFormationProvisionedProductProvisioningPreferences is a nested property type of AWS::ServiceCatalog::CloudFormationProvisionedProduct.
type ServiceCatalogCloudFormationProvisionedProductProvisioningPreferences struct {
	// +optional
	StackSetAccounts []string `json:"stackSetAccounts,omitempty" cfn:"StackSetAccounts"`

	// +kubebuilder:validation:Minimum=0
	// +optional
	StackSetFailureToleranceCount *int64 `json:"stackSetFailureToleranceCount,omitempty" cfn:"StackSetFailureToleranceCount"`

	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=100
	// +optional
	StackSetFailureTolerancePercentage *int64 `json:"stackSetFailureTolerancePercentage,omitempty" cfn:"StackSetFailureTolerancePercentage"`

	// +kubebuilder:validation:Minimum=1
	// +optional
	StackSetMaxConcurrencyCount *int64 `json:"stackSetMaxConcurrencyCount,omitempty" cfn:"StackSetMaxConcurrencyCount"`

	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=100
	// +optional
	StackSetMaxConcurrencyPercentage *int64 `json:"stackSetMaxConcurrencyPercentage,omitempty" cfn:"StackSetMaxConcurrencyPercentage"`

	// +kubebuilder:validation:Enum=CREATE;UPDATE;DELETE
	// +optional
	StackSetOperationType string `json:"stackSetOperationType,omitempty" cfn:"StackSetOperationType"`

	// +optional
	StackSetRegions []string `json:"stackSetRegions,omitempty" cfn:"StackSetRegions"`
}

// ServiceCatalogLaunchNotificationConstraintSpec is the desired state of AWS::ServiceCatalog::LaunchNotificationConstraint.
type ServiceCatalogLaunchNotificationConstraintSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	NotificationArns []string `json:"notificationArns" cfn:"NotificationArns"`

	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="productId is immutable"
	ProductId string `json:"productId" cfn:"ProductId"`
}

// ServiceCatalogLaunchNotificationConstraintStatus is the observed state of AWS::ServiceCatalog::LaunchNotificationConstraint.
type ServiceCatalogLaunchNotificationConstraintStatus struct {
	CloudControlStatus `json:",inline"`

	// Unique identifier for the constraint
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogLaunchNotificationConstraint manages AWS::ServiceCatalog::LaunchNotificationConstraint through
// the AWS Cloud Control API. Resource Type definition for AWS::ServiceCatalog::LaunchNotificationConstraint
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogLaunchNotificationConstraint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogLaunchNotificationConstraintSpec   `json:"spec,omitempty"`
	Status ServiceCatalogLaunchNotificationConstraintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogLaunchNotificationConstraintList contains a list of ServiceCatalogLaunchNotificationConstraint.
type ServiceCatalogLaunchNotificationConstraintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogLaunchNotificationConstraint `json:"items"`
}

func (o *ServiceCatalogLaunchNotificationConstraint) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogLaunchNotificationConstraint) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::LaunchNotificationConstraint"
}
func (o *ServiceCatalogLaunchNotificationConstraint) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogLaunchNotificationConstraint) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogLaunchNotificationConstraint) CloudControlObserved() interface{} {
	return &o.Status
}

// ServiceCatalogLaunchRoleConstraintSpec is the desired state of AWS::ServiceCatalog::LaunchRoleConstraint.
type ServiceCatalogLaunchRoleConstraintSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the launch role constraint.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The language code for the constraint.
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// The ID of the portfolio to which this launch role constraint applies.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`

	// The ID of the product to which this launch role constraint applies.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="productId is immutable"
	ProductId string `json:"productId" cfn:"ProductId"`

	// The local IAM role name to use in the launch constraint.
	// +optional
	LocalRoleName string `json:"localRoleName,omitempty" cfn:"LocalRoleName"`

	// The ARN of the IAM role used for the launch constraint.
	// +optional
	RoleArn string `json:"roleArn,omitempty" cfn:"RoleArn"`
}

// ServiceCatalogLaunchRoleConstraintStatus is the observed state of AWS::ServiceCatalog::LaunchRoleConstraint.
type ServiceCatalogLaunchRoleConstraintStatus struct {
	CloudControlStatus `json:",inline"`

	// The unique identifier for the launch role constraint.
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogLaunchRoleConstraint manages AWS::ServiceCatalog::LaunchRoleConstraint through the AWS Cloud
// Control API. Resource Type definition for AWS::ServiceCatalog::LaunchRoleConstraint
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogLaunchRoleConstraint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogLaunchRoleConstraintSpec   `json:"spec,omitempty"`
	Status ServiceCatalogLaunchRoleConstraintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogLaunchRoleConstraintList contains a list of ServiceCatalogLaunchRoleConstraint.
type ServiceCatalogLaunchRoleConstraintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogLaunchRoleConstraint `json:"items"`
}

func (o *ServiceCatalogLaunchRoleConstraint) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *ServiceCatalogLaunchRoleConstraint) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::LaunchRoleConstraint"
}
func (o *ServiceCatalogLaunchRoleConstraint) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogLaunchRoleConstraint) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogLaunchRoleConstraint) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogLaunchTemplateConstraintSpec is the desired state of AWS::ServiceCatalog::LaunchTemplateConstraint.
type ServiceCatalogLaunchTemplateConstraintSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the constraint.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The language code.
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// The portfolio identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`

	// The product identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="productId is immutable"
	ProductId string `json:"productId" cfn:"ProductId"`

	// A json encoded string of the template constraint rules
	Rules string `json:"rules" cfn:"Rules"`
}

// ServiceCatalogLaunchTemplateConstraintStatus is the observed state of AWS::ServiceCatalog::LaunchTemplateConstraint.
type ServiceCatalogLaunchTemplateConstraintStatus struct {
	CloudControlStatus `json:",inline"`

	// Unique identifier for the constraint
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogLaunchTemplateConstraint manages AWS::ServiceCatalog::LaunchTemplateConstraint through the AWS
// Cloud Control API. Resource Type definition for AWS::ServiceCatalog::LaunchTemplateConstraint
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogLaunchTemplateConstraint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogLaunchTemplateConstraintSpec   `json:"spec,omitempty"`
	Status ServiceCatalogLaunchTemplateConstraintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogLaunchTemplateConstraintList contains a list of ServiceCatalogLaunchTemplateConstraint.
type ServiceCatalogLaunchTemplateConstraintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogLaunchTemplateConstraint `json:"items"`
}

func (o *ServiceCatalogLaunchTemplateConstraint) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogLaunchTemplateConstraint) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::LaunchTemplateConstraint"
}
func (o *ServiceCatalogLaunchTemplateConstraint) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogLaunchTemplateConstraint) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogLaunchTemplateConstraint) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogPortfolioPrincipalAssociationSpec is the desired state of AWS::ServiceCatalog::PortfolioPrincipalAssociation.
type ServiceCatalogPortfolioPrincipalAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ARN of the principal (user, role, or group).
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	PrincipalARN string `json:"principalARN,omitempty" cfn:"PrincipalARN"`

	// The language code.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// The portfolio identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	PortfolioId string `json:"portfolioId,omitempty" cfn:"PortfolioId"`

	// The principal type. The supported value is IAM if you use a fully defined Amazon Resource Name (ARN), or
	// IAM_PATTERN if you use an ARN with no accountID, with or without wildcard characters.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="principalType is immutable"
	PrincipalType string `json:"principalType" cfn:"PrincipalType"`
}

// ServiceCatalogPortfolioPrincipalAssociationStatus is the observed state of AWS::ServiceCatalog::PortfolioPrincipalAssociation.
type ServiceCatalogPortfolioPrincipalAssociationStatus struct {
	CloudControlStatus `json:",inline"`
}

// ServiceCatalogPortfolioPrincipalAssociation manages AWS::ServiceCatalog::PortfolioPrincipalAssociation through
// the AWS Cloud Control API. Resource Type definition for AWS::ServiceCatalog::PortfolioPrincipalAssociation
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogPortfolioPrincipalAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogPortfolioPrincipalAssociationSpec   `json:"spec,omitempty"`
	Status ServiceCatalogPortfolioPrincipalAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogPortfolioPrincipalAssociationList contains a list of ServiceCatalogPortfolioPrincipalAssociation.
type ServiceCatalogPortfolioPrincipalAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogPortfolioPrincipalAssociation `json:"items"`
}

func (o *ServiceCatalogPortfolioPrincipalAssociation) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogPortfolioPrincipalAssociation) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::PortfolioPrincipalAssociation"
}
func (o *ServiceCatalogPortfolioPrincipalAssociation) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogPortfolioPrincipalAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogPortfolioPrincipalAssociation) CloudControlObserved() interface{} {
	return &o.Status
}

// ServiceCatalogPortfolioShareSpec is the desired state of AWS::ServiceCatalog::PortfolioShare.
type ServiceCatalogPortfolioShareSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The language code.
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// The portfolio identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`

	// The AWS account ID.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="accountId is immutable"
	AccountId string `json:"accountId" cfn:"AccountId"`

	// Enables or disables TagOptions sharing when creating the portfolio share.
	// +optional
	ShareTagOptions *bool `json:"shareTagOptions,omitempty" cfn:"ShareTagOptions"`
}

// ServiceCatalogPortfolioShareStatus is the observed state of AWS::ServiceCatalog::PortfolioShare.
type ServiceCatalogPortfolioShareStatus struct {
	CloudControlStatus `json:",inline"`
}

// ServiceCatalogPortfolioShare manages AWS::ServiceCatalog::PortfolioShare through the AWS Cloud Control API.
// Resource Type definition for AWS::ServiceCatalog::PortfolioShare
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogPortfolioShare struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogPortfolioShareSpec   `json:"spec,omitempty"`
	Status ServiceCatalogPortfolioShareStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogPortfolioShareList contains a list of ServiceCatalogPortfolioShare.
type ServiceCatalogPortfolioShareList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogPortfolioShare `json:"items"`
}

func (o *ServiceCatalogPortfolioShare) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *ServiceCatalogPortfolioShare) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::PortfolioShare"
}
func (o *ServiceCatalogPortfolioShare) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogPortfolioShare) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogPortfolioShare) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogResourceUpdateConstraintSpec is the desired state of AWS::ServiceCatalog::ResourceUpdateConstraint.
type ServiceCatalogResourceUpdateConstraintSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the constraint
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The language code
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// ALLOWED or NOT_ALLOWED, to permit or prevent changes to the tags on provisioned instances of the specified
	// portfolio / product combination
	TagUpdateOnProvisionedProduct string `json:"tagUpdateOnProvisionedProduct" cfn:"TagUpdateOnProvisionedProduct"`

	// The portfolio identifier
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`

	// The product identifier
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="productId is immutable"
	ProductId string `json:"productId" cfn:"ProductId"`
}

// ServiceCatalogResourceUpdateConstraintStatus is the observed state of AWS::ServiceCatalog::ResourceUpdateConstraint.
type ServiceCatalogResourceUpdateConstraintStatus struct {
	CloudControlStatus `json:",inline"`

	// Unique identifier for the constraint
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogResourceUpdateConstraint manages AWS::ServiceCatalog::ResourceUpdateConstraint through the AWS
// Cloud Control API. Resource type definition for AWS::ServiceCatalog::ResourceUpdateConstraint
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogResourceUpdateConstraint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogResourceUpdateConstraintSpec   `json:"spec,omitempty"`
	Status ServiceCatalogResourceUpdateConstraintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogResourceUpdateConstraintList contains a list of ServiceCatalogResourceUpdateConstraint.
type ServiceCatalogResourceUpdateConstraintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogResourceUpdateConstraint `json:"items"`
}

func (o *ServiceCatalogResourceUpdateConstraint) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogResourceUpdateConstraint) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::ResourceUpdateConstraint"
}
func (o *ServiceCatalogResourceUpdateConstraint) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogResourceUpdateConstraint) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogResourceUpdateConstraint) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogServiceActionSpec is the desired state of AWS::ServiceCatalog::ServiceAction.
type ServiceCatalogServiceActionSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:validation:Enum=en;jp;zh
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	Name string `json:"name" cfn:"Name"`

	// +kubebuilder:validation:Enum=SSM_AUTOMATION
	DefinitionType string `json:"definitionType" cfn:"DefinitionType"`

	Definition []CFNTag `json:"definition" cfn:"Definition"`

	// +kubebuilder:validation:MaxLength=1024
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`
}

// ServiceCatalogServiceActionStatus is the observed state of AWS::ServiceCatalog::ServiceAction.
type ServiceCatalogServiceActionStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=100
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogServiceAction manages AWS::ServiceCatalog::ServiceAction through the AWS Cloud Control API.
// Resource Schema for AWS::ServiceCatalog::ServiceAction
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogServiceAction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogServiceActionSpec   `json:"spec,omitempty"`
	Status ServiceCatalogServiceActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogServiceActionList contains a list of ServiceCatalogServiceAction.
type ServiceCatalogServiceActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogServiceAction `json:"items"`
}

func (o *ServiceCatalogServiceAction) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *ServiceCatalogServiceAction) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::ServiceAction"
}
func (o *ServiceCatalogServiceAction) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogServiceAction) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogServiceAction) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogServiceActionAssociationSpec is the desired state of AWS::ServiceCatalog::ServiceActionAssociation.
type ServiceCatalogServiceActionAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=100
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="productId is immutable"
	ProductId string `json:"productId" cfn:"ProductId"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=100
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="provisioningArtifactId is immutable"
	ProvisioningArtifactId string `json:"provisioningArtifactId" cfn:"ProvisioningArtifactId"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=100
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="serviceActionId is immutable"
	ServiceActionId string `json:"serviceActionId" cfn:"ServiceActionId"`
}

// ServiceCatalogServiceActionAssociationStatus is the observed state of AWS::ServiceCatalog::ServiceActionAssociation.
type ServiceCatalogServiceActionAssociationStatus struct {
	CloudControlStatus `json:",inline"`
}

// ServiceCatalogServiceActionAssociation manages AWS::ServiceCatalog::ServiceActionAssociation through the AWS
// Cloud Control API. Resource Schema for AWS::ServiceCatalog::ServiceActionAssociation
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogServiceActionAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogServiceActionAssociationSpec   `json:"spec,omitempty"`
	Status ServiceCatalogServiceActionAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogServiceActionAssociationList contains a list of ServiceCatalogServiceActionAssociation.
type ServiceCatalogServiceActionAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogServiceActionAssociation `json:"items"`
}

func (o *ServiceCatalogServiceActionAssociation) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *ServiceCatalogServiceActionAssociation) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::ServiceActionAssociation"
}
func (o *ServiceCatalogServiceActionAssociation) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogServiceActionAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogServiceActionAssociation) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogStackSetConstraintSpec is the desired state of AWS::ServiceCatalog::StackSetConstraint.
type ServiceCatalogStackSetConstraintSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the constraint.
	Description string `json:"description" cfn:"Description"`

	// Permission to create, update, and delete stack instances. Choose from ALLOWED and NOT_ALLOWED.
	StackInstanceControl string `json:"stackInstanceControl" cfn:"StackInstanceControl"`

	// The language code.
	// +optional
	AcceptLanguage string `json:"acceptLanguage,omitempty" cfn:"AcceptLanguage"`

	// The portfolio identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="portfolioId is immutable"
	PortfolioId string `json:"portfolioId" cfn:"PortfolioId"`

	// The product identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="productId is immutable"
	ProductId string `json:"productId" cfn:"ProductId"`

	// One or more AWS Regions where the provisioned product will be available.
	RegionList []string `json:"regionList" cfn:"RegionList"`

	// AdminRole ARN.
	AdminRole string `json:"adminRole" cfn:"AdminRole"`

	// One or more AWS accounts that will have access to the provisioned product.
	AccountList []string `json:"accountList" cfn:"AccountList"`

	// ExecutionRole name.
	ExecutionRole string `json:"executionRole" cfn:"ExecutionRole"`
}

// ServiceCatalogStackSetConstraintStatus is the observed state of AWS::ServiceCatalog::StackSetConstraint.
type ServiceCatalogStackSetConstraintStatus struct {
	CloudControlStatus `json:",inline"`

	// Unique identifier for the constraint
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogStackSetConstraint manages AWS::ServiceCatalog::StackSetConstraint through the AWS Cloud Control
// API. Resource Type definition for AWS::ServiceCatalog::StackSetConstraint
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogStackSetConstraint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogStackSetConstraintSpec   `json:"spec,omitempty"`
	Status ServiceCatalogStackSetConstraintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogStackSetConstraintList contains a list of ServiceCatalogStackSetConstraint.
type ServiceCatalogStackSetConstraintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogStackSetConstraint `json:"items"`
}

func (o *ServiceCatalogStackSetConstraint) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *ServiceCatalogStackSetConstraint) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::StackSetConstraint"
}
func (o *ServiceCatalogStackSetConstraint) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogStackSetConstraint) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogStackSetConstraint) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogTagOptionSpec is the desired state of AWS::ServiceCatalog::TagOption.
type ServiceCatalogTagOptionSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The TagOption active state.
	// +optional
	Active *bool `json:"active,omitempty" cfn:"Active"`

	// The TagOption value.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="value is immutable"
	Value string `json:"value" cfn:"Value"`

	// The TagOption key.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="key is immutable"
	Key string `json:"key" cfn:"Key"`
}

// ServiceCatalogTagOptionStatus is the observed state of AWS::ServiceCatalog::TagOption.
type ServiceCatalogTagOptionStatus struct {
	CloudControlStatus `json:",inline"`

	// The TagOption identifier.
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// ServiceCatalogTagOption manages AWS::ServiceCatalog::TagOption through the AWS Cloud Control API. Resource
// type definition for AWS::ServiceCatalog::TagOption
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogTagOption struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogTagOptionSpec   `json:"spec,omitempty"`
	Status ServiceCatalogTagOptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogTagOptionList contains a list of ServiceCatalogTagOption.
type ServiceCatalogTagOptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogTagOption `json:"items"`
}

func (o *ServiceCatalogTagOption) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *ServiceCatalogTagOption) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::TagOption"
}
func (o *ServiceCatalogTagOption) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogTagOption) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogTagOption) CloudControlObserved() interface{} { return &o.Status }

// ServiceCatalogTagOptionAssociationSpec is the desired state of AWS::ServiceCatalog::TagOptionAssociation.
type ServiceCatalogTagOptionAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The TagOption identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	TagOptionId string `json:"tagOptionId,omitempty" cfn:"TagOptionId"`

	// The CloudformationProduct or Portfolio identifier.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ResourceId string `json:"resourceId,omitempty" cfn:"ResourceId"`
}

// ServiceCatalogTagOptionAssociationStatus is the observed state of AWS::ServiceCatalog::TagOptionAssociation.
type ServiceCatalogTagOptionAssociationStatus struct {
	CloudControlStatus `json:",inline"`
}

// ServiceCatalogTagOptionAssociation manages AWS::ServiceCatalog::TagOptionAssociation through the AWS Cloud
// Control API. Resource Type definition for AWS::ServiceCatalog::TagOptionAssociation
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type ServiceCatalogTagOptionAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceCatalogTagOptionAssociationSpec   `json:"spec,omitempty"`
	Status ServiceCatalogTagOptionAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceCatalogTagOptionAssociationList contains a list of ServiceCatalogTagOptionAssociation.
type ServiceCatalogTagOptionAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceCatalogTagOptionAssociation `json:"items"`
}

func (o *ServiceCatalogTagOptionAssociation) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *ServiceCatalogTagOptionAssociation) CloudControlTypeName() string {
	return "AWS::ServiceCatalog::TagOptionAssociation"
}
func (o *ServiceCatalogTagOptionAssociation) CloudControlSpec() interface{} { return &o.Spec }
func (o *ServiceCatalogTagOptionAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *ServiceCatalogTagOptionAssociation) CloudControlObserved() interface{} { return &o.Status }

func init() {
	SchemeBuilder.Register(&ServiceCatalogAcceptedPortfolioShare{}, &ServiceCatalogAcceptedPortfolioShareList{})
	SchemeBuilder.Register(&ServiceCatalogCloudFormationProvisionedProduct{}, &ServiceCatalogCloudFormationProvisionedProductList{})
	SchemeBuilder.Register(&ServiceCatalogLaunchNotificationConstraint{}, &ServiceCatalogLaunchNotificationConstraintList{})
	SchemeBuilder.Register(&ServiceCatalogLaunchRoleConstraint{}, &ServiceCatalogLaunchRoleConstraintList{})
	SchemeBuilder.Register(&ServiceCatalogLaunchTemplateConstraint{}, &ServiceCatalogLaunchTemplateConstraintList{})
	SchemeBuilder.Register(&ServiceCatalogPortfolioPrincipalAssociation{}, &ServiceCatalogPortfolioPrincipalAssociationList{})
	SchemeBuilder.Register(&ServiceCatalogPortfolioShare{}, &ServiceCatalogPortfolioShareList{})
	SchemeBuilder.Register(&ServiceCatalogResourceUpdateConstraint{}, &ServiceCatalogResourceUpdateConstraintList{})
	SchemeBuilder.Register(&ServiceCatalogServiceAction{}, &ServiceCatalogServiceActionList{})
	SchemeBuilder.Register(&ServiceCatalogServiceActionAssociation{}, &ServiceCatalogServiceActionAssociationList{})
	SchemeBuilder.Register(&ServiceCatalogStackSetConstraint{}, &ServiceCatalogStackSetConstraintList{})
	SchemeBuilder.Register(&ServiceCatalogTagOption{}, &ServiceCatalogTagOptionList{})
	SchemeBuilder.Register(&ServiceCatalogTagOptionAssociation{}, &ServiceCatalogTagOptionAssociationList{})
}
