/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// SecurityLakeAwsLogSourceSpec is the desired state of AWS::SecurityLake::AwsLogSource.
type SecurityLakeAwsLogSourceSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// AWS account where you want to collect logs from.
	// +optional
	Accounts []string `json:"accounts,omitempty" cfn:"Accounts"`

	// The ARN for the data lake.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="dataLakeArn is immutable"
	DataLakeArn string `json:"dataLakeArn" cfn:"DataLakeArn"`

	// The name for a AWS source. This must be a Regionally unique value.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="sourceName is immutable"
	SourceName string `json:"sourceName" cfn:"SourceName"`

	// The version for a AWS source. This must be a Regionally unique value.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="sourceVersion is immutable"
	SourceVersion string `json:"sourceVersion" cfn:"SourceVersion"`
}

// SecurityLakeAwsLogSourceStatus is the observed state of AWS::SecurityLake::AwsLogSource.
type SecurityLakeAwsLogSourceStatus struct {
	CloudControlStatus `json:",inline"`
}

// SecurityLakeAwsLogSource manages AWS::SecurityLake::AwsLogSource through the AWS Cloud Control API. Resource
// Type definition for AWS::SecurityLake::AwsLogSource
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type SecurityLakeAwsLogSource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SecurityLakeAwsLogSourceSpec   `json:"spec,omitempty"`
	Status SecurityLakeAwsLogSourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityLakeAwsLogSourceList contains a list of SecurityLakeAwsLogSource.
type SecurityLakeAwsLogSourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityLakeAwsLogSource `json:"items"`
}

func (o *SecurityLakeAwsLogSource) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *SecurityLakeAwsLogSource) CloudControlTypeName() string {
	return "AWS::SecurityLake::AwsLogSource"
}
func (o *SecurityLakeAwsLogSource) CloudControlSpec() interface{} { return &o.Spec }
func (o *SecurityLakeAwsLogSource) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *SecurityLakeAwsLogSource) CloudControlObserved() interface{} { return &o.Status }

// SecurityLakeDataLakeSpec is the desired state of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +optional
	EncryptionConfiguration *SecurityLakeDataLakeEncryptionConfiguration `json:"encryptionConfiguration,omitempty" cfn:"EncryptionConfiguration"`

	// +optional
	LifecycleConfiguration *SecurityLakeDataLakeLifecycleConfiguration `json:"lifecycleConfiguration,omitempty" cfn:"LifecycleConfiguration"`

	// +optional
	ReplicationConfiguration *SecurityLakeDataLakeReplicationConfiguration `json:"replicationConfiguration,omitempty" cfn:"ReplicationConfiguration"`

	// The Amazon Resource Name (ARN) used to index AWS Glue table partitions that are generated by the ingestion and
	// normalization of AWS log sources and custom sources.
	// +optional
	MetaStoreManagerRoleArn string `json:"metaStoreManagerRoleArn,omitempty" cfn:"MetaStoreManagerRoleArn"`

	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// SecurityLakeDataLakeStatus is the observed state of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) created by you to provide to the subscriber.
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=1011
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`

	// The ARN for the Amazon Security Lake Amazon S3 bucket.
	// Read-only: reported by AWS after creation.
	// +optional
	S3BucketArn string `json:"s3BucketArn,omitempty" cfn:"S3BucketArn"`
}

// SecurityLakeDataLake manages AWS::SecurityLake::DataLake through the AWS Cloud Control API. Resource Type
// definition for AWS::SecurityLake::DataLake
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type SecurityLakeDataLake struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SecurityLakeDataLakeSpec   `json:"spec,omitempty"`
	Status SecurityLakeDataLakeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityLakeDataLakeList contains a list of SecurityLakeDataLake.
type SecurityLakeDataLakeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityLakeDataLake `json:"items"`
}

func (o *SecurityLakeDataLake) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *SecurityLakeDataLake) CloudControlTypeName() string  { return "AWS::SecurityLake::DataLake" }
func (o *SecurityLakeDataLake) CloudControlSpec() interface{} { return &o.Spec }
func (o *SecurityLakeDataLake) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *SecurityLakeDataLake) CloudControlObserved() interface{} { return &o.Status }

// SecurityLakeDataLakeEncryptionConfiguration is a nested property type of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeEncryptionConfiguration struct {
	// The id of KMS encryption key used by Amazon Security Lake to encrypt the Security Lake object.
	// +optional
	KmsKeyId string `json:"kmsKeyId,omitempty" cfn:"KmsKeyId"`
}

// SecurityLakeDataLakeLifecycleConfiguration is a nested property type of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeLifecycleConfiguration struct {
	// +optional
	Expiration *SecurityLakeDataLakeExpiration `json:"expiration,omitempty" cfn:"Expiration"`

	// Provides data storage transition details of Amazon Security Lake object.
	// +optional
	Transitions []SecurityLakeDataLakeTransitions `json:"transitions,omitempty" cfn:"Transitions"`
}

// SecurityLakeDataLakeExpiration is a nested property type of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeExpiration struct {
	// +kubebuilder:validation:Minimum=1
	// +optional
	Days *int64 `json:"days,omitempty" cfn:"Days"`
}

// SecurityLakeDataLakeTransitions is a nested property type of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeTransitions struct {
	// Number of days before data transitions to a different S3 Storage Class in the Amazon Security Lake object.
	// +kubebuilder:validation:Minimum=1
	// +optional
	Days *int64 `json:"days,omitempty" cfn:"Days"`

	// The range of storage classes that you can choose from based on the data access, resiliency, and cost
	// requirements of your workloads.
	// +optional
	StorageClass string `json:"storageClass,omitempty" cfn:"StorageClass"`
}

// SecurityLakeDataLakeReplicationConfiguration is a nested property type of AWS::SecurityLake::DataLake.
type SecurityLakeDataLakeReplicationConfiguration struct {
	// +optional
	Regions []string `json:"regions,omitempty" cfn:"Regions"`

	// Replication settings for the Amazon S3 buckets. This parameter uses the AWS Identity and Access Management
	// (IAM) role you created that is managed by Security Lake, to ensure the replication setting is correct.
	// +optional
	RoleArn string `json:"roleArn,omitempty" cfn:"RoleArn"`
}

// SecurityLakeSubscriberSpec is the desired state of AWS::SecurityLake::Subscriber.
type SecurityLakeSubscriberSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	AccessTypes []string `json:"accessTypes" cfn:"AccessTypes"`

	// The ARN for the data lake.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="dataLakeArn is immutable"
	DataLakeArn string `json:"dataLakeArn" cfn:"DataLakeArn"`

	// The AWS identity used to access your data.
	SubscriberIdentity SecurityLakeSubscriberSubscriberIdentity `json:"subscriberIdentity" cfn:"SubscriberIdentity"`

	// The name of your Security Lake subscriber account.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=64
	SubscriberName string `json:"subscriberName" cfn:"SubscriberName"`

	// The description for your subscriber account in Security Lake.
	// +optional
	SubscriberDescription string `json:"subscriberDescription,omitempty" cfn:"SubscriberDescription"`

	// An array of objects, one for each tag to associate with the subscriber. For each tag, you must specify both a
	// tag key and a tag value. A tag value cannot be null, but it can be an empty string.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The supported AWS services from which logs and events are collected.
	Sources []SecurityLakeSubscriberSourcesItem `json:"sources" cfn:"Sources"`
}

// SecurityLakeSubscriberStatus is the observed state of AWS::SecurityLake::Subscriber.
type SecurityLakeSubscriberStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	ResourceShareArn string `json:"resourceShareArn,omitempty" cfn:"ResourceShareArn"`

	// Read-only: reported by AWS after creation.
	// +optional
	ResourceShareName string `json:"resourceShareName,omitempty" cfn:"ResourceShareName"`

	// Read-only: reported by AWS after creation.
	// +optional
	SubscriberRoleArn string `json:"subscriberRoleArn,omitempty" cfn:"SubscriberRoleArn"`

	// Read-only: reported by AWS after creation.
	// +optional
	S3BucketArn string `json:"s3BucketArn,omitempty" cfn:"S3BucketArn"`

	// Read-only: reported by AWS after creation.
	// +optional
	SubscriberArn string `json:"subscriberArn,omitempty" cfn:"SubscriberArn"`
}

// SecurityLakeSubscriber manages AWS::SecurityLake::Subscriber through the AWS Cloud Control API. Resource Type
// definition for AWS::SecurityLake::Subscriber
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type SecurityLakeSubscriber struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SecurityLakeSubscriberSpec   `json:"spec,omitempty"`
	Status SecurityLakeSubscriberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityLakeSubscriberList contains a list of SecurityLakeSubscriber.
type SecurityLakeSubscriberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityLakeSubscriber `json:"items"`
}

func (o *SecurityLakeSubscriber) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *SecurityLakeSubscriber) CloudControlTypeName() string {
	return "AWS::SecurityLake::Subscriber"
}
func (o *SecurityLakeSubscriber) CloudControlSpec() interface{} { return &o.Spec }
func (o *SecurityLakeSubscriber) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *SecurityLakeSubscriber) CloudControlObserved() interface{} { return &o.Status }

// SecurityLakeSubscriberSubscriberIdentity is a nested property type of AWS::SecurityLake::Subscriber.
type SecurityLakeSubscriberSubscriberIdentity struct {
	// The external ID used to establish trust relationship with the AWS identity.
	// +kubebuilder:validation:MinLength=2
	// +kubebuilder:validation:MaxLength=1224
	ExternalId string `json:"externalId" cfn:"ExternalId"`

	// The AWS identity principal.
	Principal string `json:"principal" cfn:"Principal"`
}

// SecurityLakeSubscriberSourcesItem is a nested property type of AWS::SecurityLake::Subscriber.
type SecurityLakeSubscriberSourcesItem struct {
	// +optional
	AwsLogSource *SecurityLakeSubscriberAwsLogSource `json:"awsLogSource,omitempty" cfn:"AwsLogSource"`

	// +optional
	CustomLogSource *SecurityLakeSubscriberCustomLogSource `json:"customLogSource,omitempty" cfn:"CustomLogSource"`
}

// SecurityLakeSubscriberAwsLogSource is a nested property type of AWS::SecurityLake::Subscriber.
type SecurityLakeSubscriberAwsLogSource struct {
	// The name for a AWS source. This must be a Regionally unique value.
	// +optional
	SourceName string `json:"sourceName,omitempty" cfn:"SourceName"`

	// The version for a AWS source. This must be a Regionally unique value.
	// +optional
	SourceVersion string `json:"sourceVersion,omitempty" cfn:"SourceVersion"`
}

// SecurityLakeSubscriberCustomLogSource is a nested property type of AWS::SecurityLake::Subscriber.
type SecurityLakeSubscriberCustomLogSource struct {
	// The name for a third-party custom source. This must be a Regionally unique value.
	// +kubebuilder:validation:MaxLength=64
	// +optional
	SourceName string `json:"sourceName,omitempty" cfn:"SourceName"`

	// The version for a third-party custom source. This must be a Regionally unique value.
	// +kubebuilder:validation:MaxLength=32
	// +optional
	SourceVersion string `json:"sourceVersion,omitempty" cfn:"SourceVersion"`
}

// SecurityLakeSubscriberNotificationSpec is the desired state of AWS::SecurityLake::SubscriberNotification.
type SecurityLakeSubscriberNotificationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	NotificationConfiguration SecurityLakeSubscriberNotificationNotificationConfiguration `json:"notificationConfiguration" cfn:"NotificationConfiguration"`

	// The ARN for the subscriber
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="subscriberArn is immutable"
	SubscriberArn string `json:"subscriberArn" cfn:"SubscriberArn"`
}

// SecurityLakeSubscriberNotificationStatus is the observed state of AWS::SecurityLake::SubscriberNotification.
type SecurityLakeSubscriberNotificationStatus struct {
	CloudControlStatus `json:",inline"`

	// The endpoint the subscriber should listen to for notifications
	// Read-only: reported by AWS after creation.
	// +optional
	SubscriberEndpoint string `json:"subscriberEndpoint,omitempty" cfn:"SubscriberEndpoint"`
}

// SecurityLakeSubscriberNotification manages AWS::SecurityLake::SubscriberNotification through the AWS Cloud
// Control API. Resource Type definition for AWS::SecurityLake::SubscriberNotification
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type SecurityLakeSubscriberNotification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SecurityLakeSubscriberNotificationSpec   `json:"spec,omitempty"`
	Status SecurityLakeSubscriberNotificationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityLakeSubscriberNotificationList contains a list of SecurityLakeSubscriberNotification.
type SecurityLakeSubscriberNotificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityLakeSubscriberNotification `json:"items"`
}

func (o *SecurityLakeSubscriberNotification) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *SecurityLakeSubscriberNotification) CloudControlTypeName() string {
	return "AWS::SecurityLake::SubscriberNotification"
}
func (o *SecurityLakeSubscriberNotification) CloudControlSpec() interface{} { return &o.Spec }
func (o *SecurityLakeSubscriberNotification) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *SecurityLakeSubscriberNotification) CloudControlObserved() interface{} { return &o.Status }

// SecurityLakeSubscriberNotificationNotificationConfiguration is a nested property type of AWS::SecurityLake::SubscriberNotification.
type SecurityLakeSubscriberNotificationNotificationConfiguration struct {
	// +optional
	HttpsNotificationConfiguration *SecurityLakeSubscriberNotificationHttpsNotificationConfiguration `json:"httpsNotificationConfiguration,omitempty" cfn:"HttpsNotificationConfiguration"`

	// +kubebuilder:pruning:PreserveUnknownFields
	// +optional
	SqsNotificationConfiguration apiextensionsv1.JSON `json:"sqsNotificationConfiguration,omitempty" cfn:"SqsNotificationConfiguration"`
}

// SecurityLakeSubscriberNotificationHttpsNotificationConfiguration is a nested property type of AWS::SecurityLake::SubscriberNotification.
type SecurityLakeSubscriberNotificationHttpsNotificationConfiguration struct {
	// The key name for the notification subscription.
	// +optional
	AuthorizationApiKeyName string `json:"authorizationApiKeyName,omitempty" cfn:"AuthorizationApiKeyName"`

	// The key value for the notification subscription.
	// +optional
	AuthorizationApiKeyValue string `json:"authorizationApiKeyValue,omitempty" cfn:"AuthorizationApiKeyValue"`

	// The subscription endpoint in Security Lake.
	Endpoint string `json:"endpoint" cfn:"Endpoint"`

	// The HTTPS method used for the notification subscription.
	// +kubebuilder:validation:Enum=POST;PUT
	// +optional
	HttpMethod string `json:"httpMethod,omitempty" cfn:"HttpMethod"`

	// The Amazon Resource Name (ARN) of the EventBridge API destinations IAM role that you created.
	TargetRoleArn string `json:"targetRoleArn" cfn:"TargetRoleArn"`
}

func init() {
	SchemeBuilder.Register(&SecurityLakeAwsLogSource{}, &SecurityLakeAwsLogSourceList{})
	SchemeBuilder.Register(&SecurityLakeDataLake{}, &SecurityLakeDataLakeList{})
	SchemeBuilder.Register(&SecurityLakeSubscriber{}, &SecurityLakeSubscriberList{})
	SchemeBuilder.Register(&SecurityLakeSubscriberNotification{}, &SecurityLakeSubscriberNotificationList{})
}
