/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// MSKBatchScramSecretSpec is the desired state of AWS::MSK::BatchScramSecret.
type MSKBatchScramSecretSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clusterArn is immutable"
	ClusterArn string `json:"clusterArn" cfn:"ClusterArn"`

	// +optional
	SecretArnList []string `json:"secretArnList,omitempty" cfn:"SecretArnList"`
}

// MSKBatchScramSecretStatus is the observed state of AWS::MSK::BatchScramSecret.
type MSKBatchScramSecretStatus struct {
	CloudControlStatus `json:",inline"`
}

// MSKBatchScramSecret manages AWS::MSK::BatchScramSecret through the AWS Cloud Control API. Resource Type
// definition for AWS::MSK::BatchScramSecret
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type MSKBatchScramSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MSKBatchScramSecretSpec   `json:"spec,omitempty"`
	Status MSKBatchScramSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MSKBatchScramSecretList contains a list of MSKBatchScramSecret.
type MSKBatchScramSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MSKBatchScramSecret `json:"items"`
}

func (o *MSKBatchScramSecret) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *MSKBatchScramSecret) CloudControlTypeName() string  { return "AWS::MSK::BatchScramSecret" }
func (o *MSKBatchScramSecret) CloudControlSpec() interface{} { return &o.Spec }
func (o *MSKBatchScramSecret) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *MSKBatchScramSecret) CloudControlObserved() interface{} { return &o.Status }

// MSKChannelSpec is the desired state of AWS::MSK::Channel.
type MSKChannelSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=64
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="channelName is immutable"
	ChannelName string `json:"channelName" cfn:"ChannelName"`

	// The Amazon Resource Name (ARN) of the cluster
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ClusterArn string `json:"clusterArn,omitempty" cfn:"ClusterArn"`

	// Topic configuration
	// Create-only in AWS: changing it requires replacing the resource.
	TopicConfigurationList []MSKChannelTopicConfiguration `json:"topicConfigurationList" cfn:"TopicConfigurationList"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	EncryptionConfiguration *MSKChannelEncryptionConfiguration `json:"encryptionConfiguration,omitempty" cfn:"EncryptionConfiguration"`

	// +optional
	IcebergDestinationConfiguration *MSKChannelIcebergDestinationConfiguration `json:"icebergDestinationConfiguration,omitempty" cfn:"IcebergDestinationConfiguration"`

	// +optional
	S3DestinationConfiguration *MSKChannelS3DestinationConfiguration `json:"s3DestinationConfiguration,omitempty" cfn:"S3DestinationConfiguration"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	LoggingInfo *MSKChannelChannelLoggingInfo `json:"loggingInfo,omitempty" cfn:"LoggingInfo"`

	// +optional
	Tags map[string]string `json:"tags,omitempty" cfn:"Tags"`
}

// MSKChannelStatus is the observed state of AWS::MSK::Channel.
type MSKChannelStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) that uniquely identifies the channel
	// Read-only: reported by AWS after creation.
	// +optional
	ChannelArn string `json:"channelArn,omitempty" cfn:"ChannelArn"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:Enum=CREATING;ACTIVE;UPDATING;DELETING;FAILED;SUSPENDING;SUSPENDED
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// Read-only: reported by AWS after creation.
	// +optional
	StateInfo *MSKChannelChannelStateInfo `json:"stateInfo,omitempty" cfn:"StateInfo"`
}

// MSKChannel manages AWS::MSK::Channel through the AWS Cloud Control API. Resource Type definition for
// AWS::MSK::Channel
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type MSKChannel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MSKChannelSpec   `json:"spec,omitempty"`
	Status MSKChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MSKChannelList contains a list of MSKChannel.
type MSKChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MSKChannel `json:"items"`
}

func (o *MSKChannel) GetProviderRef() *ProviderRef               { return o.Spec.ProviderRef }
func (o *MSKChannel) CloudControlTypeName() string               { return "AWS::MSK::Channel" }
func (o *MSKChannel) CloudControlSpec() interface{}              { return &o.Spec }
func (o *MSKChannel) CloudControlStatusRef() *CloudControlStatus { return &o.Status.CloudControlStatus }
func (o *MSKChannel) CloudControlObserved() interface{}          { return &o.Status }

// MSKChannelTopicConfiguration is a nested property type of AWS::MSK::Channel.
type MSKChannelTopicConfiguration struct {
	// The Amazon Resource Name (ARN) that uniquely identifies the topic
	TopicArn string `json:"topicArn" cfn:"TopicArn"`

	RecordConverter MSKChannelRecordConverter `json:"recordConverter" cfn:"RecordConverter"`

	// +optional
	RecordSchema *MSKChannelRecordSchema `json:"recordSchema,omitempty" cfn:"RecordSchema"`
}

// MSKChannelRecordConverter is a nested property type of AWS::MSK::Channel.
type MSKChannelRecordConverter struct {
	// +kubebuilder:validation:Enum=BYTE_ARRAY;JSON;JSON_SCHEMA_GSR;STRING
	ValueConverter string `json:"valueConverter" cfn:"ValueConverter"`
}

// MSKChannelRecordSchema is a nested property type of AWS::MSK::Channel.
type MSKChannelRecordSchema struct {
	// ARN of Glue Schema Registry resource used for table schema
	GsrArn string `json:"gsrArn" cfn:"GsrArn"`
}

// MSKChannelEncryptionConfiguration is a nested property type of AWS::MSK::Channel.
type MSKChannelEncryptionConfiguration struct {
	// The ARN of the KMS key for encryption
	KmsKeyArn string `json:"kmsKeyArn" cfn:"KmsKeyArn"`
}

// MSKChannelIcebergDestinationConfiguration is a nested property type of AWS::MSK::Channel.
type MSKChannelIcebergDestinationConfiguration struct {
	// The Amazon Resource Name (ARN) of an IAM role used by MSK to access the table
	ServiceExecutionRoleArn string `json:"serviceExecutionRoleArn" cfn:"ServiceExecutionRoleArn"`

	// Data freshness in seconds
	// +kubebuilder:validation:Minimum=60
	// +kubebuilder:validation:Maximum=900
	// +optional
	DataFreshnessInSeconds *int64 `json:"dataFreshnessInSeconds,omitempty" cfn:"DataFreshnessInSeconds"`

	// +optional
	Catalog *MSKChannelCatalog `json:"catalog,omitempty" cfn:"Catalog"`

	DeadLetterQueueS3 MSKChannelDeadLetterQueueS3 `json:"deadLetterQueueS3" cfn:"DeadLetterQueueS3"`

	// Append only mode
	AppendOnly bool `json:"appendOnly" cfn:"AppendOnly"`

	SchemaEvolution MSKChannelSchemaEvolution `json:"schemaEvolution" cfn:"SchemaEvolution"`

	TableCreation MSKChannelTableCreation `json:"tableCreation" cfn:"TableCreation"`

	// List of destination tables
	DestinationTableList []MSKChannelDestinationTable `json:"destinationTableList" cfn:"DestinationTableList"`

	// +kubebuilder:validation:Enum=ZSTD;SNAPPY
	// +optional
	CompressionType string `json:"compressionType,omitempty" cfn:"CompressionType"`
}

// MSKChannelCatalog is a nested property type of AWS::MSK::Channel.
type MSKChannelCatalog struct {
	// The ARN of the catalog
	// +optional
	CatalogArn string `json:"catalogArn,omitempty" cfn:"CatalogArn"`

	// The warehouse location
	// +optional
	WarehouseLocation string `json:"warehouseLocation,omitempty" cfn:"WarehouseLocation"`
}

// MSKChannelDeadLetterQueueS3 is a nested property type of AWS::MSK::Channel.
type MSKChannelDeadLetterQueueS3 struct {
	// The ARN of the S3 bucket
	BucketArn string `json:"bucketArn" cfn:"BucketArn"`

	// The error output prefix
	ErrorOutputPrefix string `json:"errorOutputPrefix" cfn:"ErrorOutputPrefix"`

	// Optional 12-digit AWS account ID expected to own the dead-letter S3 bucket
	// +optional
	ExpectedBucketOwner string `json:"expectedBucketOwner,omitempty" cfn:"ExpectedBucketOwner"`
}

// MSKChannelSchemaEvolution is a nested property type of AWS::MSK::Channel.
type MSKChannelSchemaEvolution struct {
	// Whether schema evolution is enabled
	EnableSchemaEvolution bool `json:"enableSchemaEvolution" cfn:"EnableSchemaEvolution"`
}

// MSKChannelTableCreation is a nested property type of AWS::MSK::Channel.
type MSKChannelTableCreation struct {
	// Whether table creation is enabled
	EnableTableCreation bool `json:"enableTableCreation" cfn:"EnableTableCreation"`
}

// MSKChannelDestinationTable is a nested property type of AWS::MSK::Channel.
type MSKChannelDestinationTable struct {
	// The destination database name
	DestinationDatabaseName string `json:"destinationDatabaseName" cfn:"DestinationDatabaseName"`

	// The destination table name
	DestinationTableName string `json:"destinationTableName" cfn:"DestinationTableName"`

	// +optional
	PartitionSpec *MSKChannelPartitionSpec `json:"partitionSpec,omitempty" cfn:"PartitionSpec"`
}

// MSKChannelPartitionSpec is a nested property type of AWS::MSK::Channel.
type MSKChannelPartitionSpec struct {
	// +kubebuilder:validation:Enum=TIME_HOUR
	PartitionStrategy string `json:"partitionStrategy" cfn:"PartitionStrategy"`

	// Source list
	// +optional
	SourceList []MSKChannelPartitionSource `json:"sourceList,omitempty" cfn:"SourceList"`
}

// MSKChannelPartitionSource is a nested property type of AWS::MSK::Channel.
type MSKChannelPartitionSource struct {
	// Source name
	// +optional
	SourceName string `json:"sourceName,omitempty" cfn:"SourceName"`
}

// MSKChannelS3DestinationConfiguration is a nested property type of AWS::MSK::Channel.
type MSKChannelS3DestinationConfiguration struct {
	// Data freshness in seconds
	// +kubebuilder:validation:Minimum=60
	// +kubebuilder:validation:Maximum=900
	// +optional
	DataFreshnessInSeconds *int64 `json:"dataFreshnessInSeconds,omitempty" cfn:"DataFreshnessInSeconds"`

	DeadLetterQueueS3 MSKChannelDeadLetterQueueS3 `json:"deadLetterQueueS3" cfn:"DeadLetterQueueS3"`

	// The Amazon Resource Name (ARN) of an IAM role used by MSK to access S3
	ServiceExecutionRoleArn string `json:"serviceExecutionRoleArn" cfn:"ServiceExecutionRoleArn"`

	Storage MSKChannelS3Storage `json:"storage" cfn:"Storage"`
}

// MSKChannelS3Storage is a nested property type of AWS::MSK::Channel.
type MSKChannelS3Storage struct {
	// ARN of the S3 bucket
	BucketArn string `json:"bucketArn" cfn:"BucketArn"`

	// Optional prefix for output objects
	// +optional
	OutputPrefix string `json:"outputPrefix,omitempty" cfn:"OutputPrefix"`

	// Template for S3 key for output objects, used for partitioning
	// +optional
	OutputKeyTemplate string `json:"outputKeyTemplate,omitempty" cfn:"OutputKeyTemplate"`

	// +kubebuilder:validation:Enum=STANDARD;INTELLIGENT_TIERING;GLACIER_IR
	StorageClass string `json:"storageClass" cfn:"StorageClass"`

	// +kubebuilder:validation:Enum=NONE;GZIP;ZSTD
	CompressionType string `json:"compressionType" cfn:"CompressionType"`

	// Optional 12-digit AWS account ID expected to own the S3 bucket
	// +optional
	ExpectedBucketOwner string `json:"expectedBucketOwner,omitempty" cfn:"ExpectedBucketOwner"`
}

// MSKChannelChannelLoggingInfo is a nested property type of AWS::MSK::Channel.
type MSKChannelChannelLoggingInfo struct {
	// +optional
	S3 *MSKChannelS3LogDestination `json:"s3,omitempty" cfn:"S3"`

	// +optional
	CloudWatchLogs *MSKChannelCloudWatchLogsLogDestination `json:"cloudWatchLogs,omitempty" cfn:"CloudWatchLogs"`

	// +optional
	Firehose *MSKChannelFirehoseLogDestination `json:"firehose,omitempty" cfn:"Firehose"`
}

// MSKChannelS3LogDestination is a nested property type of AWS::MSK::Channel.
type MSKChannelS3LogDestination struct {
	// Whether S3 logging is enabled
	Enabled bool `json:"enabled" cfn:"Enabled"`

	// The name of the S3 bucket for log delivery
	// +optional
	Bucket string `json:"bucket,omitempty" cfn:"Bucket"`

	// The S3 prefix for log delivery
	// +optional
	Prefix string `json:"prefix,omitempty" cfn:"Prefix"`
}

// MSKChannelCloudWatchLogsLogDestination is a nested property type of AWS::MSK::Channel.
type MSKChannelCloudWatchLogsLogDestination struct {
	// Whether CloudWatch Logs logging is enabled
	Enabled bool `json:"enabled" cfn:"Enabled"`

	// The CloudWatch log group for log delivery
	// +optional
	LogGroup string `json:"logGroup,omitempty" cfn:"LogGroup"`
}

// MSKChannelFirehoseLogDestination is a nested property type of AWS::MSK::Channel.
type MSKChannelFirehoseLogDestination struct {
	// Whether Firehose logging is enabled
	Enabled bool `json:"enabled" cfn:"Enabled"`

	// The Firehose delivery stream for log delivery
	// +optional
	DeliveryStream string `json:"deliveryStream,omitempty" cfn:"DeliveryStream"`
}

// MSKChannelChannelStateInfo is a nested property type of AWS::MSK::Channel.
type MSKChannelChannelStateInfo struct {
	// Code for channel state
	// +optional
	Code string `json:"code,omitempty" cfn:"Code"`

	// Message for channel state
	// +optional
	Message string `json:"message,omitempty" cfn:"Message"`
}

// MSKClusterPolicySpec is the desired state of AWS::MSK::ClusterPolicy.
type MSKClusterPolicySpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// A policy document containing permissions to add to the specified cluster.
	// +kubebuilder:pruning:PreserveUnknownFields
	Policy apiextensionsv1.JSON `json:"policy" cfn:"Policy"`

	// The arn of the cluster for the resource policy.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clusterArn is immutable"
	ClusterArn string `json:"clusterArn" cfn:"ClusterArn"`
}

// MSKClusterPolicyStatus is the observed state of AWS::MSK::ClusterPolicy.
type MSKClusterPolicyStatus struct {
	CloudControlStatus `json:",inline"`

	// The current version of the policy attached to the specified cluster
	// Read-only: reported by AWS after creation.
	// +optional
	CurrentVersion string `json:"currentVersion,omitempty" cfn:"CurrentVersion"`
}

// MSKClusterPolicy manages AWS::MSK::ClusterPolicy through the AWS Cloud Control API. Resource Type definition
// for AWS::MSK::ClusterPolicy
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type MSKClusterPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MSKClusterPolicySpec   `json:"spec,omitempty"`
	Status MSKClusterPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MSKClusterPolicyList contains a list of MSKClusterPolicy.
type MSKClusterPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MSKClusterPolicy `json:"items"`
}

func (o *MSKClusterPolicy) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *MSKClusterPolicy) CloudControlTypeName() string  { return "AWS::MSK::ClusterPolicy" }
func (o *MSKClusterPolicy) CloudControlSpec() interface{} { return &o.Spec }
func (o *MSKClusterPolicy) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *MSKClusterPolicy) CloudControlObserved() interface{} { return &o.Status }

// MSKReplicatorSpec is the desired state of AWS::MSK::Replicator.
type MSKReplicatorSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The name of the replicator.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="replicatorName is immutable"
	ReplicatorName string `json:"replicatorName" cfn:"ReplicatorName"`

	// A summary description of the replicator.
	// +kubebuilder:validation:MaxLength=1024
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// Specifies a list of Kafka clusters which are targets of the replicator.
	// Create-only in AWS: changing it requires replacing the resource.
	KafkaClusters []MSKReplicatorKafkaCluster `json:"kafkaClusters" cfn:"KafkaClusters"`

	// A list of replication configurations, where each configuration targets a given source cluster to target
	// cluster replication flow.
	ReplicationInfoList []MSKReplicatorReplicationInfo `json:"replicationInfoList" cfn:"ReplicationInfoList"`

	// The Amazon Resource Name (ARN) of the IAM role used by the replicator to access external resources.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="serviceExecutionRoleArn is immutable"
	ServiceExecutionRoleArn string `json:"serviceExecutionRoleArn" cfn:"ServiceExecutionRoleArn"`

	// A collection of tags associated with a resource
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// Configuration for log delivery for the replicator.
	// +optional
	LogDelivery *MSKReplicatorLogDelivery `json:"logDelivery,omitempty" cfn:"LogDelivery"`
}

// MSKReplicatorStatus is the observed state of AWS::MSK::Replicator.
type MSKReplicatorStatus struct {
	CloudControlStatus `json:",inline"`

	// Amazon Resource Name for the created replicator.
	// Read-only: reported by AWS after creation.
	// +optional
	ReplicatorArn string `json:"replicatorArn,omitempty" cfn:"ReplicatorArn"`

	// The current version of the MSK replicator.
	// Read-only: reported by AWS after creation.
	// +optional
	CurrentVersion string `json:"currentVersion,omitempty" cfn:"CurrentVersion"`
}

// MSKReplicator manages AWS::MSK::Replicator through the AWS Cloud Control API. Resource Type definition for
// AWS::MSK::Replicator
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type MSKReplicator struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MSKReplicatorSpec   `json:"spec,omitempty"`
	Status MSKReplicatorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MSKReplicatorList contains a list of MSKReplicator.
type MSKReplicatorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MSKReplicator `json:"items"`
}

func (o *MSKReplicator) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *MSKReplicator) CloudControlTypeName() string  { return "AWS::MSK::Replicator" }
func (o *MSKReplicator) CloudControlSpec() interface{} { return &o.Spec }
func (o *MSKReplicator) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *MSKReplicator) CloudControlObserved() interface{} { return &o.Status }

// MSKReplicatorKafkaCluster is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaCluster struct {
	// Details of an Amazon MSK cluster.
	// +optional
	AmazonMskCluster *MSKReplicatorAmazonMskCluster `json:"amazonMskCluster,omitempty" cfn:"AmazonMskCluster"`

	// Details of an Apache Kafka cluster.
	// +optional
	ApacheKafkaCluster *MSKReplicatorApacheKafkaCluster `json:"apacheKafkaCluster,omitempty" cfn:"ApacheKafkaCluster"`

	// Details of an Amazon VPC which has network connectivity to the Apache Kafka cluster.
	// +optional
	VpcConfig *MSKReplicatorKafkaClusterClientVpcConfig `json:"vpcConfig,omitempty" cfn:"VpcConfig"`

	// Details of the client authentication used by the Apache Kafka cluster.
	// +optional
	ClientAuthentication *MSKReplicatorKafkaClusterClientAuthentication `json:"clientAuthentication,omitempty" cfn:"ClientAuthentication"`

	// Details of encryption in transit to the Apache Kafka cluster.
	// +optional
	EncryptionInTransit *MSKReplicatorKafkaClusterEncryptionInTransit `json:"encryptionInTransit,omitempty" cfn:"EncryptionInTransit"`
}

// MSKReplicatorAmazonMskCluster is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorAmazonMskCluster struct {
	// The ARN of an Amazon MSK cluster.
	MskClusterArn string `json:"mskClusterArn" cfn:"MskClusterArn"`
}

// MSKReplicatorApacheKafkaCluster is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorApacheKafkaCluster struct {
	// The ID of the Apache Kafka cluster.
	ApacheKafkaClusterId string `json:"apacheKafkaClusterId" cfn:"ApacheKafkaClusterId"`

	// The bootstrap broker string of the Apache Kafka cluster.
	BootstrapBrokerString string `json:"bootstrapBrokerString" cfn:"BootstrapBrokerString"`
}

// MSKReplicatorKafkaClusterClientVpcConfig is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterClientVpcConfig struct {
	// The AWS security groups to associate with the elastic network interfaces in order to specify what the
	// replicator has access to. If a security group is not specified, the default security group associated with the
	// VPC is used.
	// +optional
	SecurityGroupIds []string `json:"securityGroupIds,omitempty" cfn:"SecurityGroupIds"`

	// The list of subnets to connect to in the virtual private cloud (VPC). AWS creates elastic network interfaces
	// inside these subnets.
	SubnetIds []string `json:"subnetIds" cfn:"SubnetIds"`
}

// MSKReplicatorKafkaClusterClientAuthentication is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterClientAuthentication struct {
	// Details for SASL/SCRAM client authentication.
	// +optional
	SaslScram *MSKReplicatorKafkaClusterSaslScramAuthentication `json:"saslScram,omitempty" cfn:"SaslScram"`

	// Details for mTLS client authentication.
	// +optional
	MTLS *MSKReplicatorKafkaClusterMtlsAuthentication `json:"mtls,omitempty" cfn:"MTLS"`

	// Details for client authentication using SASL/OAUTHBEARER.
	// +optional
	SaslOAuthBearer *MSKReplicatorKafkaClusterSaslOAuthBearerAuthentication `json:"saslOAuthBearer,omitempty" cfn:"SaslOAuthBearer"`
}

// MSKReplicatorKafkaClusterSaslScramAuthentication is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterSaslScramAuthentication struct {
	// The SASL/SCRAM authentication mechanism.
	// +kubebuilder:validation:Enum=SHA256;SHA512
	Mechanism string `json:"mechanism" cfn:"Mechanism"`

	// The Amazon Resource Name (ARN) of the Secrets Manager secret.
	SecretArn string `json:"secretArn" cfn:"SecretArn"`
}

// MSKReplicatorKafkaClusterMtlsAuthentication is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterMtlsAuthentication struct {
	// The Amazon Resource Name (ARN) of the Secrets Manager secret.
	SecretArn string `json:"secretArn" cfn:"SecretArn"`
}

// MSKReplicatorKafkaClusterSaslOAuthBearerAuthentication is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterSaslOAuthBearerAuthentication struct {
	// The HTTPS URL of the OAuth token endpoint that vends OAuth Bearer tokens per RFC 6749.
	TokenEndpointUrl string `json:"tokenEndpointUrl" cfn:"TokenEndpointUrl"`

	// Details for SASL/OAUTHBEARER using standard client_credentials grant. Mutually exclusive with iamJwtBearer and
	// clientCredentialsAssertion.
	// +optional
	ClientCredentials *MSKReplicatorKafkaClusterOAuthClientCredentials `json:"clientCredentials,omitempty" cfn:"ClientCredentials"`

	// Details for SASL/OAUTHBEARER using JWT Bearer assertion grant (RFC 7523). Mutually exclusive with
	// clientCredentials and clientCredentialsAssertion.
	// +optional
	IamJwtBearer *MSKReplicatorKafkaClusterOAuthIamJwtBearer `json:"iamJwtBearer,omitempty" cfn:"IamJwtBearer"`

	// Details for SASL/OAUTHBEARER using client credentials grant with JWT client assertion (RFC 7521/7523).
	// Mutually exclusive with clientCredentials and iamJwtBearer.
	// +optional
	ClientCredentialsAssertion *MSKReplicatorKafkaClusterOAuthClientCredentialsAssertion `json:"clientCredentialsAssertion,omitempty" cfn:"ClientCredentialsAssertion"`

	// How client credentials are sent to the identity provider (POST, BASIC, or NONE).
	// +kubebuilder:validation:Enum=POST;BASIC;NONE
	TokenEndpointAuthenticationMethod string `json:"tokenEndpointAuthenticationMethod" cfn:"TokenEndpointAuthenticationMethod"`

	// OAuth scope to request. Included in the token request if provided.
	// +optional
	Scope string `json:"scope,omitempty" cfn:"Scope"`

	// Secrets Manager ARN containing a custom CA certificate for the identity provider. Required only if the
	// identity provider uses a private CA.
	// +optional
	TokenEndpointTlsCertificateArn string `json:"tokenEndpointTlsCertificateArn,omitempty" cfn:"TokenEndpointTlsCertificateArn"`
}

// MSKReplicatorKafkaClusterOAuthClientCredentials is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterOAuthClientCredentials struct {
	// Secrets Manager ARN of the secret containing the client_id and client_secret used to obtain an OAuth Bearer
	// token via the client_credentials grant.
	TokenRequestSecretArn string `json:"tokenRequestSecretArn" cfn:"TokenRequestSecretArn"`
}

// MSKReplicatorKafkaClusterOAuthIamJwtBearer is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterOAuthIamJwtBearer struct {
	// The audience (aud claim) set in the STS JWT assertion.
	Audience string `json:"audience" cfn:"Audience"`

	// The algorithm used to sign the JWT assertion.
	// +kubebuilder:validation:Enum=RS256;ES384
	SigningAlgorithm string `json:"signingAlgorithm" cfn:"SigningAlgorithm"`

	// Optional Secrets Manager ARN for identity providers that require client authentication alongside the JWT
	// Bearer assertion.
	// +optional
	TokenRequestSecretArn string `json:"tokenRequestSecretArn,omitempty" cfn:"TokenRequestSecretArn"`
}

// MSKReplicatorKafkaClusterOAuthClientCredentialsAssertion is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterOAuthClientCredentialsAssertion struct {
	// The audience (aud claim) set in the STS JWT client assertion.
	Audience string `json:"audience" cfn:"Audience"`

	// The algorithm used to sign the JWT client assertion.
	// +kubebuilder:validation:Enum=RS256;ES384
	SigningAlgorithm string `json:"signingAlgorithm" cfn:"SigningAlgorithm"`

	// Optional Secrets Manager ARN for identity providers that require client_id as a form parameter alongside the
	// JWT client assertion.
	// +optional
	TokenRequestSecretArn string `json:"tokenRequestSecretArn,omitempty" cfn:"TokenRequestSecretArn"`
}

// MSKReplicatorKafkaClusterEncryptionInTransit is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorKafkaClusterEncryptionInTransit struct {
	// The type of encryption in transit to the Apache Kafka cluster.
	// +kubebuilder:validation:Enum=TLS
	EncryptionType string `json:"encryptionType" cfn:"EncryptionType"`

	// The root CA certificate.
	// +optional
	RootCaCertificate string `json:"rootCaCertificate,omitempty" cfn:"RootCaCertificate"`
}

// MSKReplicatorReplicationInfo is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorReplicationInfo struct {
	// Amazon Resource Name of the source Kafka cluster.
	// +optional
	SourceKafkaClusterArn string `json:"sourceKafkaClusterArn,omitempty" cfn:"SourceKafkaClusterArn"`

	// The ID of the source Kafka cluster.
	// +optional
	SourceKafkaClusterId string `json:"sourceKafkaClusterId,omitempty" cfn:"SourceKafkaClusterId"`

	// Amazon Resource Name of the target Kafka cluster.
	// +optional
	TargetKafkaClusterArn string `json:"targetKafkaClusterArn,omitempty" cfn:"TargetKafkaClusterArn"`

	// The ID of the target Kafka cluster.
	// +optional
	TargetKafkaClusterId string `json:"targetKafkaClusterId,omitempty" cfn:"TargetKafkaClusterId"`

	// The type of compression to use writing records to target Kafka cluster.
	// +kubebuilder:validation:Enum=NONE;GZIP;SNAPPY;LZ4;ZSTD
	TargetCompressionType string `json:"targetCompressionType" cfn:"TargetCompressionType"`

	// Configuration relating to topic replication.
	TopicReplication MSKReplicatorTopicReplication `json:"topicReplication" cfn:"TopicReplication"`

	// Configuration relating to consumer group replication.
	ConsumerGroupReplication MSKReplicatorConsumerGroupReplication `json:"consumerGroupReplication" cfn:"ConsumerGroupReplication"`
}

// MSKReplicatorTopicReplication is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorTopicReplication struct {
	// List of regular expression patterns indicating the topics to copy.
	TopicsToReplicate []string `json:"topicsToReplicate" cfn:"TopicsToReplicate"`

	// List of regular expression patterns indicating the topics that should not be replicated.
	// +optional
	TopicsToExclude []string `json:"topicsToExclude,omitempty" cfn:"TopicsToExclude"`

	// Whether to periodically configure remote topics to match their corresponding upstream topics.
	// +optional
	CopyTopicConfigurations *bool `json:"copyTopicConfigurations,omitempty" cfn:"CopyTopicConfigurations"`

	// Whether to periodically configure remote topic ACLs to match their corresponding upstream topics.
	// +optional
	CopyAccessControlListsForTopics *bool `json:"copyAccessControlListsForTopics,omitempty" cfn:"CopyAccessControlListsForTopics"`

	// Whether to periodically check for new topics and partitions.
	// +optional
	DetectAndCopyNewTopics *bool `json:"detectAndCopyNewTopics,omitempty" cfn:"DetectAndCopyNewTopics"`

	// Configuration for specifying the position in the topics to start replicating from.
	// +optional
	StartingPosition *MSKReplicatorReplicationStartingPosition `json:"startingPosition,omitempty" cfn:"StartingPosition"`

	// Configuration for specifying replicated topic names should be the same as their corresponding upstream topics
	// or prefixed with source cluster alias.
	// +optional
	TopicNameConfiguration *MSKReplicatorReplicationTopicNameConfiguration `json:"topicNameConfiguration,omitempty" cfn:"TopicNameConfiguration"`
}

// MSKReplicatorReplicationStartingPosition is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorReplicationStartingPosition struct {
	// +kubebuilder:validation:Enum=LATEST;EARLIEST
	// +optional
	Type string `json:"type,omitempty" cfn:"Type"`
}

// MSKReplicatorReplicationTopicNameConfiguration is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorReplicationTopicNameConfiguration struct {
	// +kubebuilder:validation:Enum=PREFIXED_WITH_SOURCE_CLUSTER_ALIAS;IDENTICAL
	// +optional
	Type string `json:"type,omitempty" cfn:"Type"`
}

// MSKReplicatorConsumerGroupReplication is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorConsumerGroupReplication struct {
	// List of regular expression patterns indicating the consumer groups to copy.
	ConsumerGroupsToReplicate []string `json:"consumerGroupsToReplicate" cfn:"ConsumerGroupsToReplicate"`

	// List of regular expression patterns indicating the consumer groups that should not be replicated.
	// +optional
	ConsumerGroupsToExclude []string `json:"consumerGroupsToExclude,omitempty" cfn:"ConsumerGroupsToExclude"`

	// Whether to periodically write the translated offsets to __consumer_offsets topic in target cluster.
	// +optional
	SynchroniseConsumerGroupOffsets *bool `json:"synchroniseConsumerGroupOffsets,omitempty" cfn:"SynchroniseConsumerGroupOffsets"`

	// Whether to periodically check for new consumer groups.
	// +optional
	DetectAndCopyNewConsumerGroups *bool `json:"detectAndCopyNewConsumerGroups,omitempty" cfn:"DetectAndCopyNewConsumerGroups"`

	// The consumer group offset synchronization mode.
	// +kubebuilder:validation:Enum=LEGACY;ENHANCED
	// +optional
	ConsumerGroupOffsetSyncMode string `json:"consumerGroupOffsetSyncMode,omitempty" cfn:"ConsumerGroupOffsetSyncMode"`
}

// MSKReplicatorLogDelivery is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorLogDelivery struct {
	// The replicator logs configuration.
	// +optional
	ReplicatorLogDelivery *MSKReplicatorReplicatorLogDelivery `json:"replicatorLogDelivery,omitempty" cfn:"ReplicatorLogDelivery"`
}

// MSKReplicatorReplicatorLogDelivery is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorReplicatorLogDelivery struct {
	// Details of the CloudWatch Logs destination for replicator logs.
	// +optional
	CloudWatchLogs *MSKReplicatorCloudWatchLogs `json:"cloudWatchLogs,omitempty" cfn:"CloudWatchLogs"`

	// Details of the Kinesis Data Firehose delivery stream that is the destination for replicator logs.
	// +optional
	Firehose *MSKReplicatorFirehose `json:"firehose,omitempty" cfn:"Firehose"`

	// Details of the Amazon S3 destination for replicator logs.
	// +optional
	S3 *MSKReplicatorS3 `json:"s3,omitempty" cfn:"S3"`
}

// MSKReplicatorCloudWatchLogs is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorCloudWatchLogs struct {
	// Whether log delivery to CloudWatch Logs is enabled.
	Enabled bool `json:"enabled" cfn:"Enabled"`

	// The CloudWatch log group that is the destination for log delivery.
	// +optional
	LogGroup string `json:"logGroup,omitempty" cfn:"LogGroup"`
}

// MSKReplicatorFirehose is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorFirehose struct {
	// Whether log delivery to Firehose is enabled.
	Enabled bool `json:"enabled" cfn:"Enabled"`

	// The Firehose delivery stream that is the destination for log delivery.
	// +optional
	DeliveryStream string `json:"deliveryStream,omitempty" cfn:"DeliveryStream"`
}

// MSKReplicatorS3 is a nested property type of AWS::MSK::Replicator.
type MSKReplicatorS3 struct {
	// Whether log delivery to S3 is enabled.
	Enabled bool `json:"enabled" cfn:"Enabled"`

	// The S3 bucket that is the destination for log delivery.
	// +optional
	Bucket string `json:"bucket,omitempty" cfn:"Bucket"`

	// The S3 prefix that is the destination for log delivery.
	// +optional
	Prefix string `json:"prefix,omitempty" cfn:"Prefix"`
}

// MSKTopicSpec is the desired state of AWS::MSK::Topic.
type MSKTopicSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The Amazon Resource Name (ARN) of the MSK cluster
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clusterArn is immutable"
	ClusterArn string `json:"clusterArn" cfn:"ClusterArn"`

	// The name of the topic
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="topicName is immutable"
	TopicName string `json:"topicName" cfn:"TopicName"`

	// The number of partitions for the topic
	// +kubebuilder:validation:Minimum=1
	PartitionCount int64 `json:"partitionCount" cfn:"PartitionCount"`

	// The replication factor for the topic
	// +kubebuilder:validation:Minimum=1
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="replicationFactor is immutable"
	ReplicationFactor int64 `json:"replicationFactor" cfn:"ReplicationFactor"`

	// Base64 encoded configuration properties of the topic
	// +optional
	Configs string `json:"configs,omitempty" cfn:"Configs"`
}

// MSKTopicStatus is the observed state of AWS::MSK::Topic.
type MSKTopicStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the topic
	// Read-only: reported by AWS after creation.
	// +optional
	TopicArn string `json:"topicArn,omitempty" cfn:"TopicArn"`
}

// MSKTopic manages AWS::MSK::Topic through the AWS Cloud Control API. Resource Type definition for
// AWS::MSK::Topic
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type MSKTopic struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MSKTopicSpec   `json:"spec,omitempty"`
	Status MSKTopicStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MSKTopicList contains a list of MSKTopic.
type MSKTopicList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MSKTopic `json:"items"`
}

func (o *MSKTopic) GetProviderRef() *ProviderRef               { return o.Spec.ProviderRef }
func (o *MSKTopic) CloudControlTypeName() string               { return "AWS::MSK::Topic" }
func (o *MSKTopic) CloudControlSpec() interface{}              { return &o.Spec }
func (o *MSKTopic) CloudControlStatusRef() *CloudControlStatus { return &o.Status.CloudControlStatus }
func (o *MSKTopic) CloudControlObserved() interface{}          { return &o.Status }

// MSKVpcConnectionSpec is the desired state of AWS::MSK::VpcConnection.
type MSKVpcConnectionSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:validation:Enum=SASL_IAM;SASL_SCRAM;TLS
	// +kubebuilder:validation:MinLength=3
	// +kubebuilder:validation:MaxLength=10
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="authentication is immutable"
	Authentication string `json:"authentication" cfn:"Authentication"`

	// Create-only in AWS: changing it requires replacing the resource.
	ClientSubnets []string `json:"clientSubnets" cfn:"ClientSubnets"`

	// The Amazon Resource Name (ARN) of the target cluster
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="targetClusterArn is immutable"
	TargetClusterArn string `json:"targetClusterArn" cfn:"TargetClusterArn"`

	// Create-only in AWS: changing it requires replacing the resource.
	SecurityGroups []string `json:"securityGroups" cfn:"SecurityGroups"`

	// +optional
	Tags map[string]string `json:"tags,omitempty" cfn:"Tags"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="vpcId is immutable"
	VpcId string `json:"vpcId" cfn:"VpcId"`
}

// MSKVpcConnectionStatus is the observed state of AWS::MSK::VpcConnection.
type MSKVpcConnectionStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`
}

// MSKVpcConnection manages AWS::MSK::VpcConnection through the AWS Cloud Control API. Resource Type definition
// for AWS::MSK::VpcConnection
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type MSKVpcConnection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MSKVpcConnectionSpec   `json:"spec,omitempty"`
	Status MSKVpcConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MSKVpcConnectionList contains a list of MSKVpcConnection.
type MSKVpcConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MSKVpcConnection `json:"items"`
}

func (o *MSKVpcConnection) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *MSKVpcConnection) CloudControlTypeName() string  { return "AWS::MSK::VpcConnection" }
func (o *MSKVpcConnection) CloudControlSpec() interface{} { return &o.Spec }
func (o *MSKVpcConnection) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *MSKVpcConnection) CloudControlObserved() interface{} { return &o.Status }

func init() {
	SchemeBuilder.Register(&MSKBatchScramSecret{}, &MSKBatchScramSecretList{})
	SchemeBuilder.Register(&MSKChannel{}, &MSKChannelList{})
	SchemeBuilder.Register(&MSKClusterPolicy{}, &MSKClusterPolicyList{})
	SchemeBuilder.Register(&MSKReplicator{}, &MSKReplicatorList{})
	SchemeBuilder.Register(&MSKTopic{}, &MSKTopicList{})
	SchemeBuilder.Register(&MSKVpcConnection{}, &MSKVpcConnectionList{})
}
