/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// InternetMonitorMonitorSpec is the desired state of AWS::InternetMonitor::Monitor.
type InternetMonitorMonitorSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="monitorName is immutable"
	MonitorName string `json:"monitorName" cfn:"MonitorName"`

	// +kubebuilder:validation:MaxLength=12
	// +optional
	LinkedAccountId string `json:"linkedAccountId,omitempty" cfn:"LinkedAccountId"`

	// +optional
	IncludeLinkedAccounts *bool `json:"includeLinkedAccounts,omitempty" cfn:"IncludeLinkedAccounts"`

	// +optional
	Resources []string `json:"resources,omitempty" cfn:"Resources"`

	// +optional
	ResourcesToAdd []string `json:"resourcesToAdd,omitempty" cfn:"ResourcesToAdd"`

	// +optional
	ResourcesToRemove []string `json:"resourcesToRemove,omitempty" cfn:"ResourcesToRemove"`

	// +kubebuilder:validation:Enum=PENDING;ACTIVE;INACTIVE;ERROR
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=500000
	// +optional
	MaxCityNetworksToMonitor *int64 `json:"maxCityNetworksToMonitor,omitempty" cfn:"MaxCityNetworksToMonitor"`

	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=100
	// +optional
	TrafficPercentageToMonitor *int64 `json:"trafficPercentageToMonitor,omitempty" cfn:"TrafficPercentageToMonitor"`

	// +optional
	InternetMeasurementsLogDelivery *InternetMonitorMonitorInternetMeasurementsLogDelivery `json:"internetMeasurementsLogDelivery,omitempty" cfn:"InternetMeasurementsLogDelivery"`

	// +optional
	HealthEventsConfig *InternetMonitorMonitorHealthEventsConfig `json:"healthEventsConfig,omitempty" cfn:"HealthEventsConfig"`
}

// InternetMonitorMonitorStatus is the observed state of AWS::InternetMonitor::Monitor.
type InternetMonitorMonitorStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Read-only: reported by AWS after creation.
	// +optional
	ModifiedAt string `json:"modifiedAt,omitempty" cfn:"ModifiedAt"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=512
	// +optional
	MonitorArn string `json:"monitorArn,omitempty" cfn:"MonitorArn"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:Enum=OK;INACTIVE;COLLECTING_DATA;INSUFFICIENT_DATA;FAULT_SERVICE;FAULT_ACCESS_CLOUDWATCH
	// +optional
	ProcessingStatus string `json:"processingStatus,omitempty" cfn:"ProcessingStatus"`

	// Read-only: reported by AWS after creation.
	// +optional
	ProcessingStatusInfo string `json:"processingStatusInfo,omitempty" cfn:"ProcessingStatusInfo"`
}

// InternetMonitorMonitor manages AWS::InternetMonitor::Monitor through the AWS Cloud Control API. Represents a
// monitor, which defines the monitoring boundaries for measurements that Internet Monitor publishes information
// about for an application
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type InternetMonitorMonitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   InternetMonitorMonitorSpec   `json:"spec,omitempty"`
	Status InternetMonitorMonitorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InternetMonitorMonitorList contains a list of InternetMonitorMonitor.
type InternetMonitorMonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InternetMonitorMonitor `json:"items"`
}

func (o *InternetMonitorMonitor) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *InternetMonitorMonitor) CloudControlTypeName() string {
	return "AWS::InternetMonitor::Monitor"
}
func (o *InternetMonitorMonitor) CloudControlSpec() interface{} { return &o.Spec }
func (o *InternetMonitorMonitor) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *InternetMonitorMonitor) CloudControlObserved() interface{} { return &o.Status }

// InternetMonitorMonitorInternetMeasurementsLogDelivery is a nested property type of AWS::InternetMonitor::Monitor.
type InternetMonitorMonitorInternetMeasurementsLogDelivery struct {
	// +optional
	S3Config *InternetMonitorMonitorS3Config `json:"s3Config,omitempty" cfn:"S3Config"`
}

// InternetMonitorMonitorS3Config is a nested property type of AWS::InternetMonitor::Monitor.
type InternetMonitorMonitorS3Config struct {
	// +optional
	BucketName string `json:"bucketName,omitempty" cfn:"BucketName"`

	// +optional
	BucketPrefix string `json:"bucketPrefix,omitempty" cfn:"BucketPrefix"`

	// +kubebuilder:validation:Enum=ENABLED;DISABLED
	// +optional
	LogDeliveryStatus string `json:"logDeliveryStatus,omitempty" cfn:"LogDeliveryStatus"`
}

// InternetMonitorMonitorHealthEventsConfig is a nested property type of AWS::InternetMonitor::Monitor.
type InternetMonitorMonitorHealthEventsConfig struct {
	// +optional
	AvailabilityScoreThreshold *float64 `json:"availabilityScoreThreshold,omitempty" cfn:"AvailabilityScoreThreshold"`

	// +optional
	PerformanceScoreThreshold *float64 `json:"performanceScoreThreshold,omitempty" cfn:"PerformanceScoreThreshold"`

	// +optional
	AvailabilityLocalHealthEventsConfig *InternetMonitorMonitorLocalHealthEventsConfig `json:"availabilityLocalHealthEventsConfig,omitempty" cfn:"AvailabilityLocalHealthEventsConfig"`

	// +optional
	PerformanceLocalHealthEventsConfig *InternetMonitorMonitorLocalHealthEventsConfig `json:"performanceLocalHealthEventsConfig,omitempty" cfn:"PerformanceLocalHealthEventsConfig"`
}

// InternetMonitorMonitorLocalHealthEventsConfig is a nested property type of AWS::InternetMonitor::Monitor.
type InternetMonitorMonitorLocalHealthEventsConfig struct {
	// +kubebuilder:validation:Enum=ENABLED;DISABLED
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// +optional
	HealthScoreThreshold *float64 `json:"healthScoreThreshold,omitempty" cfn:"HealthScoreThreshold"`

	// +optional
	MinTrafficImpact *float64 `json:"minTrafficImpact,omitempty" cfn:"MinTrafficImpact"`
}

func init() {
	SchemeBuilder.Register(&InternetMonitorMonitor{}, &InternetMonitorMonitorList{})
}
