/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// CassandraKeyspaceSpec is the desired state of AWS::Cassandra::Keyspace.
type CassandraKeyspaceSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// Name for Cassandra keyspace
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	KeyspaceName string `json:"keyspaceName,omitempty" cfn:"KeyspaceName"`

	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// +optional
	ReplicationSpecification *CassandraKeyspaceReplicationSpecification `json:"replicationSpecification,omitempty" cfn:"ReplicationSpecification"`

	// Indicates whether client-side timestamps are enabled (true) or disabled (false) for all tables in the
	// keyspace. To add a Region to a single-Region keyspace with at least one table, the value must be set to true.
	// After you enabled client-side timestamps for a table, you can’t disable it again.
	// +optional
	ClientSideTimestampsEnabled *bool `json:"clientSideTimestampsEnabled,omitempty" cfn:"ClientSideTimestampsEnabled"`
}

// CassandraKeyspaceStatus is the observed state of AWS::Cassandra::Keyspace.
type CassandraKeyspaceStatus struct {
	CloudControlStatus `json:",inline"`
}

// CassandraKeyspace manages AWS::Cassandra::Keyspace through the AWS Cloud Control API. Resource schema for
// AWS::Cassandra::Keyspace
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CassandraKeyspace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CassandraKeyspaceSpec   `json:"spec,omitempty"`
	Status CassandraKeyspaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CassandraKeyspaceList contains a list of CassandraKeyspace.
type CassandraKeyspaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CassandraKeyspace `json:"items"`
}

func (o *CassandraKeyspace) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *CassandraKeyspace) CloudControlTypeName() string  { return "AWS::Cassandra::Keyspace" }
func (o *CassandraKeyspace) CloudControlSpec() interface{} { return &o.Spec }
func (o *CassandraKeyspace) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *CassandraKeyspace) CloudControlObserved() interface{} { return &o.Status }

// CassandraKeyspaceReplicationSpecification is a nested property type of AWS::Cassandra::Keyspace.
type CassandraKeyspaceReplicationSpecification struct {
	// +kubebuilder:validation:Enum=SINGLE_REGION;MULTI_REGION
	// +optional
	ReplicationStrategy string `json:"replicationStrategy,omitempty" cfn:"ReplicationStrategy"`

	// +optional
	RegionList []string `json:"regionList,omitempty" cfn:"RegionList"`
}

// CassandraTableSpec is the desired state of AWS::Cassandra::Table.
type CassandraTableSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// Name for Cassandra keyspace
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="keyspaceName is immutable"
	KeyspaceName string `json:"keyspaceName" cfn:"KeyspaceName"`

	// Name for Cassandra table
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	TableName string `json:"tableName,omitempty" cfn:"TableName"`

	// Non-key columns of the table
	// +optional
	RegularColumns []CassandraTableColumn `json:"regularColumns,omitempty" cfn:"RegularColumns"`

	// Partition key columns of the table
	// Create-only in AWS: changing it requires replacing the resource.
	PartitionKeyColumns []CassandraTableColumn `json:"partitionKeyColumns" cfn:"PartitionKeyColumns"`

	// Clustering key columns of the table
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ClusteringKeyColumns []CassandraTableClusteringKeyColumn `json:"clusteringKeyColumns,omitempty" cfn:"ClusteringKeyColumns"`

	// +optional
	BillingMode *CassandraTableBillingMode `json:"billingMode,omitempty" cfn:"BillingMode"`

	// Indicates whether point in time recovery is enabled (true) or disabled (false) on the table
	// +optional
	PointInTimeRecoveryEnabled *bool `json:"pointInTimeRecoveryEnabled,omitempty" cfn:"PointInTimeRecoveryEnabled"`

	// Indicates whether client side timestamps are enabled (true) or disabled (false) on the table. False by
	// default, once it is enabled it cannot be disabled again.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ClientSideTimestampsEnabled *bool `json:"clientSideTimestampsEnabled,omitempty" cfn:"ClientSideTimestampsEnabled"`

	// An array of key-value pairs to apply to this resource
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// Default TTL (Time To Live) in seconds, where zero is disabled. If the value is greater than zero, TTL is
	// enabled for the entire table and an expiration timestamp is added to each column.
	// +kubebuilder:validation:Minimum=0
	// +optional
	DefaultTimeToLive *int64 `json:"defaultTimeToLive,omitempty" cfn:"DefaultTimeToLive"`

	// +optional
	EncryptionSpecification *CassandraTableEncryptionSpecification `json:"encryptionSpecification,omitempty" cfn:"EncryptionSpecification"`

	// +optional
	AutoScalingSpecifications *CassandraTableAutoScalingSpecification `json:"autoScalingSpecifications,omitempty" cfn:"AutoScalingSpecifications"`

	// +optional
	CdcSpecification *CassandraTableCdcSpecification `json:"cdcSpecification,omitempty" cfn:"CdcSpecification"`

	// +optional
	ReplicaSpecifications []CassandraTableReplicaSpecification `json:"replicaSpecifications,omitempty" cfn:"ReplicaSpecifications"`

	// +optional
	WarmThroughput *CassandraTableWarmThroughput `json:"warmThroughput,omitempty" cfn:"WarmThroughput"`
}

// CassandraTableStatus is the observed state of AWS::Cassandra::Table.
type CassandraTableStatus struct {
	CloudControlStatus `json:",inline"`
}

// CassandraTable manages AWS::Cassandra::Table through the AWS Cloud Control API. Resource schema for
// AWS::Cassandra::Table
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CassandraTable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CassandraTableSpec   `json:"spec,omitempty"`
	Status CassandraTableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CassandraTableList contains a list of CassandraTable.
type CassandraTableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CassandraTable `json:"items"`
}

func (o *CassandraTable) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *CassandraTable) CloudControlTypeName() string  { return "AWS::Cassandra::Table" }
func (o *CassandraTable) CloudControlSpec() interface{} { return &o.Spec }
func (o *CassandraTable) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *CassandraTable) CloudControlObserved() interface{} { return &o.Status }

// CassandraTableColumn is a nested property type of AWS::Cassandra::Table.
type CassandraTableColumn struct {
	ColumnName string `json:"columnName" cfn:"ColumnName"`

	ColumnType string `json:"columnType" cfn:"ColumnType"`
}

// CassandraTableClusteringKeyColumn is a nested property type of AWS::Cassandra::Table.
type CassandraTableClusteringKeyColumn struct {
	Column CassandraTableColumn `json:"column" cfn:"Column"`

	// +kubebuilder:validation:Enum=ASC;DESC
	// +optional
	OrderBy string `json:"orderBy,omitempty" cfn:"OrderBy"`
}

// CassandraTableBillingMode is a nested property type of AWS::Cassandra::Table.
type CassandraTableBillingMode struct {
	// +kubebuilder:validation:Enum=PROVISIONED;ON_DEMAND
	Mode string `json:"mode" cfn:"Mode"`

	// +optional
	ProvisionedThroughput *CassandraTableProvisionedThroughput `json:"provisionedThroughput,omitempty" cfn:"ProvisionedThroughput"`
}

// CassandraTableProvisionedThroughput is a nested property type of AWS::Cassandra::Table.
type CassandraTableProvisionedThroughput struct {
	// +kubebuilder:validation:Minimum=1
	ReadCapacityUnits int64 `json:"readCapacityUnits" cfn:"ReadCapacityUnits"`

	// +kubebuilder:validation:Minimum=1
	WriteCapacityUnits int64 `json:"writeCapacityUnits" cfn:"WriteCapacityUnits"`
}

// CassandraTableEncryptionSpecification is a nested property type of AWS::Cassandra::Table.
type CassandraTableEncryptionSpecification struct {
	// +kubebuilder:validation:Enum=AWS_OWNED_KMS_KEY;CUSTOMER_MANAGED_KMS_KEY
	EncryptionType string `json:"encryptionType" cfn:"EncryptionType"`

	// +optional
	KmsKeyIdentifier string `json:"kmsKeyIdentifier,omitempty" cfn:"KmsKeyIdentifier"`
}

// CassandraTableAutoScalingSpecification is a nested property type of AWS::Cassandra::Table.
type CassandraTableAutoScalingSpecification struct {
	// +optional
	WriteCapacityAutoScaling *CassandraTableAutoScalingSetting `json:"writeCapacityAutoScaling,omitempty" cfn:"WriteCapacityAutoScaling"`

	// +optional
	ReadCapacityAutoScaling *CassandraTableAutoScalingSetting `json:"readCapacityAutoScaling,omitempty" cfn:"ReadCapacityAutoScaling"`
}

// CassandraTableAutoScalingSetting is a nested property type of AWS::Cassandra::Table.
type CassandraTableAutoScalingSetting struct {
	// +optional
	AutoScalingDisabled *bool `json:"autoScalingDisabled,omitempty" cfn:"AutoScalingDisabled"`

	// +kubebuilder:validation:Minimum=1
	// +optional
	MinimumUnits *int64 `json:"minimumUnits,omitempty" cfn:"MinimumUnits"`

	// +kubebuilder:validation:Minimum=1
	// +optional
	MaximumUnits *int64 `json:"maximumUnits,omitempty" cfn:"MaximumUnits"`

	// +optional
	ScalingPolicy *CassandraTableScalingPolicy `json:"scalingPolicy,omitempty" cfn:"ScalingPolicy"`
}

// CassandraTableScalingPolicy is a nested property type of AWS::Cassandra::Table.
type CassandraTableScalingPolicy struct {
	// +optional
	TargetTrackingScalingPolicyConfiguration *CassandraTableTargetTrackingScalingPolicyConfiguration `json:"targetTrackingScalingPolicyConfiguration,omitempty" cfn:"TargetTrackingScalingPolicyConfiguration"`
}

// CassandraTableTargetTrackingScalingPolicyConfiguration is a nested property type of AWS::Cassandra::Table.
type CassandraTableTargetTrackingScalingPolicyConfiguration struct {
	// +optional
	DisableScaleIn *bool `json:"disableScaleIn,omitempty" cfn:"DisableScaleIn"`

	// +optional
	ScaleInCooldown *int64 `json:"scaleInCooldown,omitempty" cfn:"ScaleInCooldown"`

	// +optional
	ScaleOutCooldown *int64 `json:"scaleOutCooldown,omitempty" cfn:"ScaleOutCooldown"`

	TargetValue int64 `json:"targetValue" cfn:"TargetValue"`
}

// CassandraTableCdcSpecification is a nested property type of AWS::Cassandra::Table.
type CassandraTableCdcSpecification struct {
	// +kubebuilder:validation:Enum=ENABLED;DISABLED
	Status string `json:"status" cfn:"Status"`

	// +kubebuilder:validation:Enum=NEW_IMAGE;OLD_IMAGE;KEYS_ONLY;NEW_AND_OLD_IMAGES
	// +optional
	ViewType string `json:"viewType,omitempty" cfn:"ViewType"`

	// An array of key-value pairs to apply to the CDC stream resource
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// CassandraTableReplicaSpecification is a nested property type of AWS::Cassandra::Table.
type CassandraTableReplicaSpecification struct {
	// +kubebuilder:validation:MinLength=2
	// +kubebuilder:validation:MaxLength=25
	Region string `json:"region" cfn:"Region"`

	// +optional
	ReadCapacityUnits *int64 `json:"readCapacityUnits,omitempty" cfn:"ReadCapacityUnits"`

	// +optional
	ReadCapacityAutoScaling *CassandraTableAutoScalingSetting `json:"readCapacityAutoScaling,omitempty" cfn:"ReadCapacityAutoScaling"`
}

// CassandraTableWarmThroughput is a nested property type of AWS::Cassandra::Table.
type CassandraTableWarmThroughput struct {
	// +kubebuilder:validation:Minimum=1
	// +optional
	ReadUnitsPerSecond *int64 `json:"readUnitsPerSecond,omitempty" cfn:"ReadUnitsPerSecond"`

	// +kubebuilder:validation:Minimum=1
	// +optional
	WriteUnitsPerSecond *int64 `json:"writeUnitsPerSecond,omitempty" cfn:"WriteUnitsPerSecond"`
}

// CassandraTypeSpec is the desired state of AWS::Cassandra::Type.
type CassandraTypeSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// Name of the Keyspace which contains the User-Defined Type.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="keyspaceName is immutable"
	KeyspaceName string `json:"keyspaceName" cfn:"KeyspaceName"`

	// Name of the User-Defined Type.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="typeName is immutable"
	TypeName string `json:"typeName" cfn:"TypeName"`

	// Field definitions of the User-Defined Type
	// Create-only in AWS: changing it requires replacing the resource.
	Fields []CassandraTypeField `json:"fields" cfn:"Fields"`
}

// CassandraTypeStatus is the observed state of AWS::Cassandra::Type.
type CassandraTypeStatus struct {
	CloudControlStatus `json:",inline"`

	// List of Tables that directly reference the User-Defined Type in their columns.
	// Read-only: reported by AWS after creation.
	// +optional
	DirectReferringTables []string `json:"directReferringTables,omitempty" cfn:"DirectReferringTables"`

	// List of parent User-Defined Types that directly reference the User-Defined Type in their fields.
	// Read-only: reported by AWS after creation.
	// +optional
	DirectParentTypes []string `json:"directParentTypes,omitempty" cfn:"DirectParentTypes"`

	// Maximum nesting depth of the User-Defined Type across the field types.
	// Read-only: reported by AWS after creation.
	// +optional
	MaxNestingDepth *int64 `json:"maxNestingDepth,omitempty" cfn:"MaxNestingDepth"`

	// Timestamp of the last time the User-Defined Type's meta data was modified.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModifiedTimestamp *float64 `json:"lastModifiedTimestamp,omitempty" cfn:"LastModifiedTimestamp"`

	// ARN of the Keyspace which contains the User-Defined Type.
	// Read-only: reported by AWS after creation.
	// +optional
	KeyspaceArn string `json:"keyspaceArn,omitempty" cfn:"KeyspaceArn"`
}

// CassandraType manages AWS::Cassandra::Type through the AWS Cloud Control API. Resource schema for
// AWS::Cassandra::Type
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CassandraType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CassandraTypeSpec   `json:"spec,omitempty"`
	Status CassandraTypeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CassandraTypeList contains a list of CassandraType.
type CassandraTypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CassandraType `json:"items"`
}

func (o *CassandraType) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *CassandraType) CloudControlTypeName() string  { return "AWS::Cassandra::Type" }
func (o *CassandraType) CloudControlSpec() interface{} { return &o.Spec }
func (o *CassandraType) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *CassandraType) CloudControlObserved() interface{} { return &o.Status }

// CassandraTypeField is a nested property type of AWS::Cassandra::Type.
type CassandraTypeField struct {
	FieldName string `json:"fieldName" cfn:"FieldName"`

	FieldType string `json:"fieldType" cfn:"FieldType"`
}

func init() {
	SchemeBuilder.Register(&CassandraKeyspace{}, &CassandraKeyspaceList{})
	SchemeBuilder.Register(&CassandraTable{}, &CassandraTableList{})
	SchemeBuilder.Register(&CassandraType{}, &CassandraTypeList{})
}
