/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// CodeGuruReviewerRepositoryAssociationSpec is the desired state of AWS::CodeGuruReviewer::RepositoryAssociation.
type CodeGuruReviewerRepositoryAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// Name of the repository to be associated.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=100
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="name is immutable"
	Name string `json:"name" cfn:"Name"`

	// The type of repository to be associated.
	// +kubebuilder:validation:Enum=CodeCommit;Bitbucket;GitHubEnterpriseServer;S3Bucket
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="type is immutable"
	Type string `json:"type" cfn:"Type"`

	// The owner of the repository. For a Bitbucket repository, this is the username for the account that owns the
	// repository.
	// +kubebuilder:validation:MaxLength=100
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	Owner string `json:"owner,omitempty" cfn:"Owner"`

	// The name of the S3 bucket associated with an associated S3 repository. It must start with
	// `codeguru-reviewer-`.
	// +kubebuilder:validation:MaxLength=63
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	BucketName string `json:"bucketName,omitempty" cfn:"BucketName"`

	// The Amazon Resource Name (ARN) of an AWS CodeStar Connections connection.
	// +kubebuilder:validation:MaxLength=256
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ConnectionArn string `json:"connectionArn,omitempty" cfn:"ConnectionArn"`

	// The tags associated with a repository association.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// CodeGuruReviewerRepositoryAssociationStatus is the observed state of AWS::CodeGuruReviewer::RepositoryAssociation.
type CodeGuruReviewerRepositoryAssociationStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the repository association.
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=256
	// +optional
	AssociationArn string `json:"associationArn,omitempty" cfn:"AssociationArn"`
}

// CodeGuruReviewerRepositoryAssociation manages AWS::CodeGuruReviewer::RepositoryAssociation through the AWS
// Cloud Control API. This resource schema represents the RepositoryAssociation resource in the Amazon CodeGuru
// Reviewer service.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CodeGuruReviewerRepositoryAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CodeGuruReviewerRepositoryAssociationSpec   `json:"spec,omitempty"`
	Status CodeGuruReviewerRepositoryAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CodeGuruReviewerRepositoryAssociationList contains a list of CodeGuruReviewerRepositoryAssociation.
type CodeGuruReviewerRepositoryAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CodeGuruReviewerRepositoryAssociation `json:"items"`
}

func (o *CodeGuruReviewerRepositoryAssociation) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *CodeGuruReviewerRepositoryAssociation) CloudControlTypeName() string {
	return "AWS::CodeGuruReviewer::RepositoryAssociation"
}
func (o *CodeGuruReviewerRepositoryAssociation) CloudControlSpec() interface{} { return &o.Spec }
func (o *CodeGuruReviewerRepositoryAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *CodeGuruReviewerRepositoryAssociation) CloudControlObserved() interface{} { return &o.Status }

func init() {
	SchemeBuilder.Register(&CodeGuruReviewerRepositoryAssociation{}, &CodeGuruReviewerRepositoryAssociationList{})
}
