/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// CodeDeployDeploymentConfigSpec is the desired state of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The destination platform type for the deployment (Lambda, Server, or ECS).
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ComputePlatform string `json:"computePlatform,omitempty" cfn:"ComputePlatform"`

	// A name for the deployment configuration. If you don't specify a name, AWS CloudFormation generates a unique
	// physical ID and uses that ID for the deployment configuration name. For more information, see Name Type.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	DeploymentConfigName string `json:"deploymentConfigName,omitempty" cfn:"DeploymentConfigName"`

	// The minimum number of healthy instances that should be available at any time during the deployment. There are
	// two parameters expected in the input: type and value.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	MinimumHealthyHosts *CodeDeployDeploymentConfigMinimumHealthyHosts `json:"minimumHealthyHosts,omitempty" cfn:"MinimumHealthyHosts"`

	// The zonal deployment config that specifies how the zonal deployment behaves
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ZonalConfig *CodeDeployDeploymentConfigZonalConfig `json:"zonalConfig,omitempty" cfn:"ZonalConfig"`

	// The configuration that specifies how the deployment traffic is routed.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	TrafficRoutingConfig *CodeDeployDeploymentConfigTrafficRoutingConfig `json:"trafficRoutingConfig,omitempty" cfn:"TrafficRoutingConfig"`
}

// CodeDeployDeploymentConfigStatus is the observed state of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigStatus struct {
	CloudControlStatus `json:",inline"`
}

// CodeDeployDeploymentConfig manages AWS::CodeDeploy::DeploymentConfig through the AWS Cloud Control API.
// Resource Type definition for AWS::CodeDeploy::DeploymentConfig
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CodeDeployDeploymentConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CodeDeployDeploymentConfigSpec   `json:"spec,omitempty"`
	Status CodeDeployDeploymentConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CodeDeployDeploymentConfigList contains a list of CodeDeployDeploymentConfig.
type CodeDeployDeploymentConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CodeDeployDeploymentConfig `json:"items"`
}

func (o *CodeDeployDeploymentConfig) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *CodeDeployDeploymentConfig) CloudControlTypeName() string {
	return "AWS::CodeDeploy::DeploymentConfig"
}
func (o *CodeDeployDeploymentConfig) CloudControlSpec() interface{} { return &o.Spec }
func (o *CodeDeployDeploymentConfig) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *CodeDeployDeploymentConfig) CloudControlObserved() interface{} { return &o.Status }

// CodeDeployDeploymentConfigMinimumHealthyHosts is a nested property type of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigMinimumHealthyHosts struct {
	Value int64 `json:"value" cfn:"Value"`

	Type string `json:"type" cfn:"Type"`
}

// CodeDeployDeploymentConfigZonalConfig is a nested property type of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigZonalConfig struct {
	// +optional
	FirstZoneMonitorDurationInSeconds *int64 `json:"firstZoneMonitorDurationInSeconds,omitempty" cfn:"FirstZoneMonitorDurationInSeconds"`

	// +optional
	MonitorDurationInSeconds *int64 `json:"monitorDurationInSeconds,omitempty" cfn:"MonitorDurationInSeconds"`

	// +optional
	MinimumHealthyHostsPerZone *CodeDeployDeploymentConfigMinimumHealthyHostsPerZone `json:"minimumHealthyHostsPerZone,omitempty" cfn:"MinimumHealthyHostsPerZone"`
}

// CodeDeployDeploymentConfigMinimumHealthyHostsPerZone is a nested property type of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigMinimumHealthyHostsPerZone struct {
	Value int64 `json:"value" cfn:"Value"`

	Type string `json:"type" cfn:"Type"`
}

// CodeDeployDeploymentConfigTrafficRoutingConfig is a nested property type of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigTrafficRoutingConfig struct {
	Type string `json:"type" cfn:"Type"`

	// +optional
	TimeBasedLinear *CodeDeployDeploymentConfigTimeBasedLinear `json:"timeBasedLinear,omitempty" cfn:"TimeBasedLinear"`

	// +optional
	TimeBasedCanary *CodeDeployDeploymentConfigTimeBasedCanary `json:"timeBasedCanary,omitempty" cfn:"TimeBasedCanary"`
}

// CodeDeployDeploymentConfigTimeBasedLinear is a nested property type of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigTimeBasedLinear struct {
	LinearInterval int64 `json:"linearInterval" cfn:"LinearInterval"`

	LinearPercentage int64 `json:"linearPercentage" cfn:"LinearPercentage"`
}

// CodeDeployDeploymentConfigTimeBasedCanary is a nested property type of AWS::CodeDeploy::DeploymentConfig.
type CodeDeployDeploymentConfigTimeBasedCanary struct {
	CanaryPercentage int64 `json:"canaryPercentage" cfn:"CanaryPercentage"`

	CanaryInterval int64 `json:"canaryInterval" cfn:"CanaryInterval"`
}

func init() {
	SchemeBuilder.Register(&CodeDeployDeploymentConfig{}, &CodeDeployDeploymentConfigList{})
}
