/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// DetectiveGraphSpec is the desired state of AWS::Detective::Graph.
type DetectiveGraphSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// Indicates whether to automatically enable new organization accounts as member accounts in the organization
	// behavior graph.
	// +optional
	AutoEnableMembers *bool `json:"autoEnableMembers,omitempty" cfn:"AutoEnableMembers"`
}

// DetectiveGraphStatus is the observed state of AWS::Detective::Graph.
type DetectiveGraphStatus struct {
	CloudControlStatus `json:",inline"`

	// The Detective graph ARN
	// Read-only: reported by AWS after creation.
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`
}

// DetectiveGraph manages AWS::Detective::Graph through the AWS Cloud Control API. Resource schema for
// AWS::Detective::Graph
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type DetectiveGraph struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DetectiveGraphSpec   `json:"spec,omitempty"`
	Status DetectiveGraphStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DetectiveGraphList contains a list of DetectiveGraph.
type DetectiveGraphList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DetectiveGraph `json:"items"`
}

func (o *DetectiveGraph) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *DetectiveGraph) CloudControlTypeName() string  { return "AWS::Detective::Graph" }
func (o *DetectiveGraph) CloudControlSpec() interface{} { return &o.Spec }
func (o *DetectiveGraph) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *DetectiveGraph) CloudControlObserved() interface{} { return &o.Status }

// DetectiveMemberInvitationSpec is the desired state of AWS::Detective::MemberInvitation.
type DetectiveMemberInvitationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ARN of the graph to which the member account will be invited
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="graphArn is immutable"
	GraphArn string `json:"graphArn" cfn:"GraphArn"`

	// The AWS account ID to be invited to join the graph as a member
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="memberId is immutable"
	MemberId string `json:"memberId" cfn:"MemberId"`

	// The root email address for the account to be invited, for validation. Updating this field has no effect.
	MemberEmailAddress string `json:"memberEmailAddress" cfn:"MemberEmailAddress"`

	// When set to true, invitation emails are not sent to the member accounts. Member accounts must still accept the
	// invitation before they are added to the behavior graph. Updating this field has no effect.
	// +optional
	DisableEmailNotification *bool `json:"disableEmailNotification,omitempty" cfn:"DisableEmailNotification"`

	// A message to be included in the email invitation sent to the invited account. Updating this field has no
	// effect.
	// +kubebuilder:validation:MaxLength=1000
	// +optional
	Message string `json:"message,omitempty" cfn:"Message"`
}

// DetectiveMemberInvitationStatus is the observed state of AWS::Detective::MemberInvitation.
type DetectiveMemberInvitationStatus struct {
	CloudControlStatus `json:",inline"`
}

// DetectiveMemberInvitation manages AWS::Detective::MemberInvitation through the AWS Cloud Control API. Resource
// schema for AWS::Detective::MemberInvitation
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type DetectiveMemberInvitation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DetectiveMemberInvitationSpec   `json:"spec,omitempty"`
	Status DetectiveMemberInvitationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DetectiveMemberInvitationList contains a list of DetectiveMemberInvitation.
type DetectiveMemberInvitationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DetectiveMemberInvitation `json:"items"`
}

func (o *DetectiveMemberInvitation) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *DetectiveMemberInvitation) CloudControlTypeName() string {
	return "AWS::Detective::MemberInvitation"
}
func (o *DetectiveMemberInvitation) CloudControlSpec() interface{} { return &o.Spec }
func (o *DetectiveMemberInvitation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *DetectiveMemberInvitation) CloudControlObserved() interface{} { return &o.Status }

// DetectiveOrganizationAdminSpec is the desired state of AWS::Detective::OrganizationAdmin.
type DetectiveOrganizationAdminSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The account ID of the account that should be registered as your Organization's delegated administrator for
	// Detective
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="accountId is immutable"
	AccountId string `json:"accountId" cfn:"AccountId"`
}

// DetectiveOrganizationAdminStatus is the observed state of AWS::Detective::OrganizationAdmin.
type DetectiveOrganizationAdminStatus struct {
	CloudControlStatus `json:",inline"`

	// The Detective graph ARN
	// Read-only: reported by AWS after creation.
	// +optional
	GraphArn string `json:"graphArn,omitempty" cfn:"GraphArn"`
}

// DetectiveOrganizationAdmin manages AWS::Detective::OrganizationAdmin through the AWS Cloud Control API.
// Resource schema for AWS::Detective::OrganizationAdmin
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type DetectiveOrganizationAdmin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DetectiveOrganizationAdminSpec   `json:"spec,omitempty"`
	Status DetectiveOrganizationAdminStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DetectiveOrganizationAdminList contains a list of DetectiveOrganizationAdmin.
type DetectiveOrganizationAdminList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DetectiveOrganizationAdmin `json:"items"`
}

func (o *DetectiveOrganizationAdmin) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *DetectiveOrganizationAdmin) CloudControlTypeName() string {
	return "AWS::Detective::OrganizationAdmin"
}
func (o *DetectiveOrganizationAdmin) CloudControlSpec() interface{} { return &o.Spec }
func (o *DetectiveOrganizationAdmin) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *DetectiveOrganizationAdmin) CloudControlObserved() interface{} { return &o.Status }

func init() {
	SchemeBuilder.Register(&DetectiveGraph{}, &DetectiveGraphList{})
	SchemeBuilder.Register(&DetectiveMemberInvitation{}, &DetectiveMemberInvitationList{})
	SchemeBuilder.Register(&DetectiveOrganizationAdmin{}, &DetectiveOrganizationAdminList{})
}
