/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// NetworkManagerConnectAttachmentSpec is the desired state of AWS::NetworkManager::ConnectAttachment.
type NetworkManagerConnectAttachmentSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// ID of the CoreNetwork that the attachment will be attached to.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="coreNetworkId is immutable"
	CoreNetworkId string `json:"coreNetworkId" cfn:"CoreNetworkId"`

	// Edge location of the attachment.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="edgeLocation is immutable"
	EdgeLocation string `json:"edgeLocation" cfn:"EdgeLocation"`

	// The attachment to move from one segment to another.
	// +optional
	ProposedSegmentChange *NetworkManagerConnectAttachmentProposedSegmentChange `json:"proposedSegmentChange,omitempty" cfn:"ProposedSegmentChange"`

	// The name of the network function group attachment.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`

	// The attachment to move from one network function group to another.
	// +optional
	ProposedNetworkFunctionGroupChange *NetworkManagerConnectAttachmentProposedNetworkFunctionGroupChange `json:"proposedNetworkFunctionGroupChange,omitempty" cfn:"ProposedNetworkFunctionGroupChange"`

	// Routing policy label
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	RoutingPolicyLabel string `json:"routingPolicyLabel,omitempty" cfn:"RoutingPolicyLabel"`

	// Tags for the attachment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// Id of transport attachment
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="transportAttachmentId is immutable"
	TransportAttachmentId string `json:"transportAttachmentId" cfn:"TransportAttachmentId"`

	// Protocol options for connect attachment
	// Create-only in AWS: changing it requires replacing the resource.
	Options NetworkManagerConnectAttachmentConnectAttachmentOptions `json:"options" cfn:"Options"`
}

// NetworkManagerConnectAttachmentStatus is the observed state of AWS::NetworkManager::ConnectAttachment.
type NetworkManagerConnectAttachmentStatus struct {
	CloudControlStatus `json:",inline"`

	// The ARN of a core network.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// The ID of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentId string `json:"attachmentId,omitempty" cfn:"AttachmentId"`

	// The ID of the attachment account owner.
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// The type of attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentType string `json:"attachmentType,omitempty" cfn:"AttachmentType"`

	// State of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The attachment resource ARN.
	// Read-only: reported by AWS after creation.
	// +optional
	ResourceArn string `json:"resourceArn,omitempty" cfn:"ResourceArn"`

	// The policy rule number associated with the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`

	// Creation time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Last update time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	UpdatedAt string `json:"updatedAt,omitempty" cfn:"UpdatedAt"`

	// Errors from the last modification of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerConnectAttachment manages AWS::NetworkManager::ConnectAttachment through the AWS Cloud Control
// API. AWS::NetworkManager::ConnectAttachment Resource Type Definition
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerConnectAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerConnectAttachmentSpec   `json:"spec,omitempty"`
	Status NetworkManagerConnectAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerConnectAttachmentList contains a list of NetworkManagerConnectAttachment.
type NetworkManagerConnectAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerConnectAttachment `json:"items"`
}

func (o *NetworkManagerConnectAttachment) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *NetworkManagerConnectAttachment) CloudControlTypeName() string {
	return "AWS::NetworkManager::ConnectAttachment"
}
func (o *NetworkManagerConnectAttachment) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerConnectAttachment) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerConnectAttachment) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerConnectAttachmentProposedSegmentChange is a nested property type of AWS::NetworkManager::ConnectAttachment.
type NetworkManagerConnectAttachmentProposedSegmentChange struct {
	// The list of key-value tags that changed for the segment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment to change.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`
}

// NetworkManagerConnectAttachmentProposedNetworkFunctionGroupChange is a nested property type of AWS::NetworkManager::ConnectAttachment.
type NetworkManagerConnectAttachmentProposedNetworkFunctionGroupChange struct {
	// The key-value tags that changed for the network function group.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the network function group to change.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`
}

// NetworkManagerConnectAttachmentConnectAttachmentOptions is a nested property type of AWS::NetworkManager::ConnectAttachment.
type NetworkManagerConnectAttachmentConnectAttachmentOptions struct {
	// Tunnel protocol for connect attachment
	// +optional
	Protocol string `json:"protocol,omitempty" cfn:"Protocol"`
}

// NetworkManagerConnectPeerSpec is the desired state of AWS::NetworkManager::ConnectPeer.
type NetworkManagerConnectPeerSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The IP address of the Connect peer.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="peerAddress is immutable"
	PeerAddress string `json:"peerAddress" cfn:"PeerAddress"`

	// The IP address of a core network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	CoreNetworkAddress string `json:"coreNetworkAddress,omitempty" cfn:"CoreNetworkAddress"`

	// Bgp options for connect peer.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	BgpOptions *NetworkManagerConnectPeerBgpOptions `json:"bgpOptions,omitempty" cfn:"BgpOptions"`

	// The inside IP addresses used for a Connect peer configuration.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	InsideCidrBlocks []string `json:"insideCidrBlocks,omitempty" cfn:"InsideCidrBlocks"`

	// The ID of the attachment to connect.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="connectAttachmentId is immutable"
	ConnectAttachmentId string `json:"connectAttachmentId" cfn:"ConnectAttachmentId"`

	// The subnet ARN for the connect peer.
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	SubnetArn string `json:"subnetArn,omitempty" cfn:"SubnetArn"`

	// An array of key-value pairs to apply to this resource.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// NetworkManagerConnectPeerStatus is the observed state of AWS::NetworkManager::ConnectPeer.
type NetworkManagerConnectPeerStatus struct {
	CloudControlStatus `json:",inline"`

	// The ID of the core network.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkId string `json:"coreNetworkId,omitempty" cfn:"CoreNetworkId"`

	// The ID of the Connect peer.
	// Read-only: reported by AWS after creation.
	// +optional
	ConnectPeerId string `json:"connectPeerId,omitempty" cfn:"ConnectPeerId"`

	// The Connect peer Regions where edges are located.
	// Read-only: reported by AWS after creation.
	// +optional
	EdgeLocation string `json:"edgeLocation,omitempty" cfn:"EdgeLocation"`

	// State of the connect peer.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// Connect peer creation time.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Configuration of the connect peer.
	// Read-only: reported by AWS after creation.
	// +optional
	Configuration *NetworkManagerConnectPeerConnectPeerConfiguration `json:"configuration,omitempty" cfn:"Configuration"`

	// Errors from the last modification of the connect peer.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerConnectPeer manages AWS::NetworkManager::ConnectPeer through the AWS Cloud Control API.
// AWS::NetworkManager::ConnectPeer Resource Type Definition.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerConnectPeer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerConnectPeerSpec   `json:"spec,omitempty"`
	Status NetworkManagerConnectPeerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerConnectPeerList contains a list of NetworkManagerConnectPeer.
type NetworkManagerConnectPeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerConnectPeer `json:"items"`
}

func (o *NetworkManagerConnectPeer) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *NetworkManagerConnectPeer) CloudControlTypeName() string {
	return "AWS::NetworkManager::ConnectPeer"
}
func (o *NetworkManagerConnectPeer) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerConnectPeer) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerConnectPeer) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerConnectPeerBgpOptions is a nested property type of AWS::NetworkManager::ConnectPeer.
type NetworkManagerConnectPeerBgpOptions struct {
	// +optional
	PeerAsn *float64 `json:"peerAsn,omitempty" cfn:"PeerAsn"`
}

// NetworkManagerConnectPeerConnectPeerConfiguration is a nested property type of AWS::NetworkManager::ConnectPeer.
type NetworkManagerConnectPeerConnectPeerConfiguration struct {
	// The IP address of a core network.
	// +optional
	CoreNetworkAddress string `json:"coreNetworkAddress,omitempty" cfn:"CoreNetworkAddress"`

	// The IP address of the Connect peer.
	// +optional
	PeerAddress string `json:"peerAddress,omitempty" cfn:"PeerAddress"`

	// The inside IP addresses used for a Connect peer configuration.
	// +optional
	InsideCidrBlocks []string `json:"insideCidrBlocks,omitempty" cfn:"InsideCidrBlocks"`

	// +optional
	Protocol string `json:"protocol,omitempty" cfn:"Protocol"`

	// +optional
	BgpConfigurations []NetworkManagerConnectPeerConnectPeerBgpConfiguration `json:"bgpConfigurations,omitempty" cfn:"BgpConfigurations"`
}

// NetworkManagerConnectPeerConnectPeerBgpConfiguration is a nested property type of AWS::NetworkManager::ConnectPeer.
type NetworkManagerConnectPeerConnectPeerBgpConfiguration struct {
	// The ASN of the Coret Network.
	// +optional
	CoreNetworkAsn *float64 `json:"coreNetworkAsn,omitempty" cfn:"CoreNetworkAsn"`

	// The ASN of the Connect peer.
	// +optional
	PeerAsn *float64 `json:"peerAsn,omitempty" cfn:"PeerAsn"`

	// The address of a core network.
	// +optional
	CoreNetworkAddress string `json:"coreNetworkAddress,omitempty" cfn:"CoreNetworkAddress"`

	// The address of a core network Connect peer.
	// +optional
	PeerAddress string `json:"peerAddress,omitempty" cfn:"PeerAddress"`
}

// NetworkManagerCoreNetworkSpec is the desired state of AWS::NetworkManager::CoreNetwork.
type NetworkManagerCoreNetworkSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of the global network that your core network is a part of.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// Live policy document for the core network, you must provide PolicyDocument in Json Format
	// +kubebuilder:pruning:PreserveUnknownFields
	// +optional
	PolicyDocument apiextensionsv1.JSON `json:"policyDocument,omitempty" cfn:"PolicyDocument"`

	// The description of core network
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The tags for the global network.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// NetworkManagerCoreNetworkStatus is the observed state of AWS::NetworkManager::CoreNetwork.
type NetworkManagerCoreNetworkStatus struct {
	CloudControlStatus `json:",inline"`

	// The Id of core network
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkId string `json:"coreNetworkId,omitempty" cfn:"CoreNetworkId"`

	// The ARN (Amazon resource name) of core network
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// The creation time of core network
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// The state of core network
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The segments within a core network.
	// Read-only: reported by AWS after creation.
	// +optional
	Segments []NetworkManagerCoreNetworkCoreNetworkSegment `json:"segments,omitempty" cfn:"Segments"`

	// The network function groups within a core network.
	// Read-only: reported by AWS after creation.
	// +optional
	NetworkFunctionGroups []NetworkManagerCoreNetworkCoreNetworkNetworkFunctionGroup `json:"networkFunctionGroups,omitempty" cfn:"NetworkFunctionGroups"`

	// The edges within a core network.
	// Read-only: reported by AWS after creation.
	// +optional
	Edges []NetworkManagerCoreNetworkCoreNetworkEdge `json:"edges,omitempty" cfn:"Edges"`

	// Owner of the core network
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccount string `json:"ownerAccount,omitempty" cfn:"OwnerAccount"`
}

// NetworkManagerCoreNetwork manages AWS::NetworkManager::CoreNetwork through the AWS Cloud Control API.
// AWS::NetworkManager::CoreNetwork Resource Type Definition.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerCoreNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerCoreNetworkSpec   `json:"spec,omitempty"`
	Status NetworkManagerCoreNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerCoreNetworkList contains a list of NetworkManagerCoreNetwork.
type NetworkManagerCoreNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerCoreNetwork `json:"items"`
}

func (o *NetworkManagerCoreNetwork) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *NetworkManagerCoreNetwork) CloudControlTypeName() string {
	return "AWS::NetworkManager::CoreNetwork"
}
func (o *NetworkManagerCoreNetwork) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerCoreNetwork) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerCoreNetwork) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerCoreNetworkCoreNetworkSegment is a nested property type of AWS::NetworkManager::CoreNetwork.
type NetworkManagerCoreNetworkCoreNetworkSegment struct {
	// Name of segment
	// +optional
	Name string `json:"name,omitempty" cfn:"Name"`

	// +optional
	EdgeLocations []string `json:"edgeLocations,omitempty" cfn:"EdgeLocations"`

	// +optional
	SharedSegments []string `json:"sharedSegments,omitempty" cfn:"SharedSegments"`
}

// NetworkManagerCoreNetworkCoreNetworkNetworkFunctionGroup is a nested property type of AWS::NetworkManager::CoreNetwork.
type NetworkManagerCoreNetworkCoreNetworkNetworkFunctionGroup struct {
	// Name of network function group
	// +optional
	Name string `json:"name,omitempty" cfn:"Name"`

	// +optional
	EdgeLocations []string `json:"edgeLocations,omitempty" cfn:"EdgeLocations"`

	// +optional
	Segments *NetworkManagerCoreNetworkCoreNetworkNetworkFunctionGroupSegments `json:"segments,omitempty" cfn:"Segments"`
}

// NetworkManagerCoreNetworkCoreNetworkNetworkFunctionGroupSegments is a nested property type of AWS::NetworkManager::CoreNetwork.
type NetworkManagerCoreNetworkCoreNetworkNetworkFunctionGroupSegments struct {
	// +optional
	SendTo []string `json:"sendTo,omitempty" cfn:"SendTo"`

	// +optional
	SendVia []string `json:"sendVia,omitempty" cfn:"SendVia"`
}

// NetworkManagerCoreNetworkCoreNetworkEdge is a nested property type of AWS::NetworkManager::CoreNetwork.
type NetworkManagerCoreNetworkCoreNetworkEdge struct {
	// The Region where a core network edge is located.
	// +optional
	EdgeLocation string `json:"edgeLocation,omitempty" cfn:"EdgeLocation"`

	// The ASN of a core network edge.
	// +optional
	Asn *float64 `json:"asn,omitempty" cfn:"Asn"`

	// +optional
	InsideCidrBlocks []string `json:"insideCidrBlocks,omitempty" cfn:"InsideCidrBlocks"`
}

// NetworkManagerCoreNetworkPrefixListAssociationSpec is the desired state of AWS::NetworkManager::CoreNetworkPrefixListAssociation.
type NetworkManagerCoreNetworkPrefixListAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of the core network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="coreNetworkId is immutable"
	CoreNetworkId string `json:"coreNetworkId" cfn:"CoreNetworkId"`

	// The Amazon Resource Name (ARN) of the prefix list.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="prefixListArn is immutable"
	PrefixListArn string `json:"prefixListArn" cfn:"PrefixListArn"`

	// The alias of the prefix list
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="prefixListAlias is immutable"
	PrefixListAlias string `json:"prefixListAlias" cfn:"PrefixListAlias"`
}

// NetworkManagerCoreNetworkPrefixListAssociationStatus is the observed state of AWS::NetworkManager::CoreNetworkPrefixListAssociation.
type NetworkManagerCoreNetworkPrefixListAssociationStatus struct {
	CloudControlStatus `json:",inline"`
}

// NetworkManagerCoreNetworkPrefixListAssociation manages AWS::NetworkManager::CoreNetworkPrefixListAssociation
// through the AWS Cloud Control API. Resource Type definition for
// AWS::NetworkManager::CoreNetworkPrefixListAssociation which associates a prefix list with a core network.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerCoreNetworkPrefixListAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerCoreNetworkPrefixListAssociationSpec   `json:"spec,omitempty"`
	Status NetworkManagerCoreNetworkPrefixListAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerCoreNetworkPrefixListAssociationList contains a list of NetworkManagerCoreNetworkPrefixListAssociation.
type NetworkManagerCoreNetworkPrefixListAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerCoreNetworkPrefixListAssociation `json:"items"`
}

func (o *NetworkManagerCoreNetworkPrefixListAssociation) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerCoreNetworkPrefixListAssociation) CloudControlTypeName() string {
	return "AWS::NetworkManager::CoreNetworkPrefixListAssociation"
}
func (o *NetworkManagerCoreNetworkPrefixListAssociation) CloudControlSpec() interface{} {
	return &o.Spec
}
func (o *NetworkManagerCoreNetworkPrefixListAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerCoreNetworkPrefixListAssociation) CloudControlObserved() interface{} {
	return &o.Status
}

// NetworkManagerCustomerGatewayAssociationSpec is the desired state of AWS::NetworkManager::CustomerGatewayAssociation.
type NetworkManagerCustomerGatewayAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of the global network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// The Amazon Resource Name (ARN) of the customer gateway.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="customerGatewayArn is immutable"
	CustomerGatewayArn string `json:"customerGatewayArn" cfn:"CustomerGatewayArn"`

	// The ID of the device
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="deviceId is immutable"
	DeviceId string `json:"deviceId" cfn:"DeviceId"`

	// The ID of the link
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	LinkId string `json:"linkId,omitempty" cfn:"LinkId"`
}

// NetworkManagerCustomerGatewayAssociationStatus is the observed state of AWS::NetworkManager::CustomerGatewayAssociation.
type NetworkManagerCustomerGatewayAssociationStatus struct {
	CloudControlStatus `json:",inline"`
}

// NetworkManagerCustomerGatewayAssociation manages AWS::NetworkManager::CustomerGatewayAssociation through the
// AWS Cloud Control API. The AWS::NetworkManager::CustomerGatewayAssociation type associates a customer gateway
// with a device and optionally, with a link.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerCustomerGatewayAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerCustomerGatewayAssociationSpec   `json:"spec,omitempty"`
	Status NetworkManagerCustomerGatewayAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerCustomerGatewayAssociationList contains a list of NetworkManagerCustomerGatewayAssociation.
type NetworkManagerCustomerGatewayAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerCustomerGatewayAssociation `json:"items"`
}

func (o *NetworkManagerCustomerGatewayAssociation) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerCustomerGatewayAssociation) CloudControlTypeName() string {
	return "AWS::NetworkManager::CustomerGatewayAssociation"
}
func (o *NetworkManagerCustomerGatewayAssociation) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerCustomerGatewayAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerCustomerGatewayAssociation) CloudControlObserved() interface{} {
	return &o.Status
}

// NetworkManagerDeviceSpec is the desired state of AWS::NetworkManager::Device.
type NetworkManagerDeviceSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the device.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The tags for the device.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The ID of the global network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// The Amazon Web Services location of the device, if applicable.
	// +optional
	AWSLocation *NetworkManagerDeviceAWSLocation `json:"awsLocation,omitempty" cfn:"AWSLocation"`

	// The site location.
	// +optional
	Location *NetworkManagerDeviceLocation `json:"location,omitempty" cfn:"Location"`

	// The device model
	// +optional
	Model string `json:"model,omitempty" cfn:"Model"`

	// The device serial number.
	// +optional
	SerialNumber string `json:"serialNumber,omitempty" cfn:"SerialNumber"`

	// The site ID.
	// +optional
	SiteId string `json:"siteId,omitempty" cfn:"SiteId"`

	// The device type.
	// +optional
	Type string `json:"type,omitempty" cfn:"Type"`

	// The device vendor.
	// +optional
	Vendor string `json:"vendor,omitempty" cfn:"Vendor"`
}

// NetworkManagerDeviceStatus is the observed state of AWS::NetworkManager::Device.
type NetworkManagerDeviceStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the device.
	// Read-only: reported by AWS after creation.
	// +optional
	DeviceArn string `json:"deviceArn,omitempty" cfn:"DeviceArn"`

	// The ID of the device.
	// Read-only: reported by AWS after creation.
	// +optional
	DeviceId string `json:"deviceId,omitempty" cfn:"DeviceId"`

	// The date and time that the device was created.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// The state of the device.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`
}

// NetworkManagerDevice manages AWS::NetworkManager::Device through the AWS Cloud Control API. The
// AWS::NetworkManager::Device type describes a device.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerDevice struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerDeviceSpec   `json:"spec,omitempty"`
	Status NetworkManagerDeviceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerDeviceList contains a list of NetworkManagerDevice.
type NetworkManagerDeviceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerDevice `json:"items"`
}

func (o *NetworkManagerDevice) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *NetworkManagerDevice) CloudControlTypeName() string  { return "AWS::NetworkManager::Device" }
func (o *NetworkManagerDevice) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerDevice) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerDevice) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerDeviceAWSLocation is a nested property type of AWS::NetworkManager::Device.
type NetworkManagerDeviceAWSLocation struct {
	// The Zone that the device is located in. Specify the ID of an Availability Zone, Local Zone, Wavelength Zone,
	// or an Outpost.
	// +optional
	Zone string `json:"zone,omitempty" cfn:"Zone"`

	// The Amazon Resource Name (ARN) of the subnet that the device is located in.
	// +optional
	SubnetArn string `json:"subnetArn,omitempty" cfn:"SubnetArn"`
}

// NetworkManagerDeviceLocation is a nested property type of AWS::NetworkManager::Device.
type NetworkManagerDeviceLocation struct {
	// The physical address.
	// +optional
	Address string `json:"address,omitempty" cfn:"Address"`

	// The latitude.
	// +optional
	Latitude string `json:"latitude,omitempty" cfn:"Latitude"`

	// The longitude.
	// +optional
	Longitude string `json:"longitude,omitempty" cfn:"Longitude"`
}

// NetworkManagerDirectConnectGatewayAttachmentSpec is the desired state of AWS::NetworkManager::DirectConnectGatewayAttachment.
type NetworkManagerDirectConnectGatewayAttachmentSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of a core network for the Direct Connect Gateway attachment.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="coreNetworkId is immutable"
	CoreNetworkId string `json:"coreNetworkId" cfn:"CoreNetworkId"`

	// The Regions where the edges are located.
	EdgeLocations []string `json:"edgeLocations" cfn:"EdgeLocations"`

	// The ARN of the Direct Connect Gateway.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="directConnectGatewayArn is immutable"
	DirectConnectGatewayArn string `json:"directConnectGatewayArn" cfn:"DirectConnectGatewayArn"`

	// The attachment to move from one segment to another.
	// +optional
	ProposedSegmentChange *NetworkManagerDirectConnectGatewayAttachmentProposedSegmentChange `json:"proposedSegmentChange,omitempty" cfn:"ProposedSegmentChange"`

	// The attachment to move from one network function group to another.
	// +optional
	ProposedNetworkFunctionGroupChange *NetworkManagerDirectConnectGatewayAttachmentProposedNetworkFunctionGroupChange `json:"proposedNetworkFunctionGroupChange,omitempty" cfn:"ProposedNetworkFunctionGroupChange"`

	// Routing policy label
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	RoutingPolicyLabel string `json:"routingPolicyLabel,omitempty" cfn:"RoutingPolicyLabel"`

	// Tags for the attachment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// NetworkManagerDirectConnectGatewayAttachmentStatus is the observed state of AWS::NetworkManager::DirectConnectGatewayAttachment.
type NetworkManagerDirectConnectGatewayAttachmentStatus struct {
	CloudControlStatus `json:",inline"`

	// The ARN of a core network for the Direct Connect Gateway attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// Id of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentId string `json:"attachmentId,omitempty" cfn:"AttachmentId"`

	// Owner account of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// Attachment type.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentType string `json:"attachmentType,omitempty" cfn:"AttachmentType"`

	// State of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The ARN of the Resource.
	// Read-only: reported by AWS after creation.
	// +optional
	ResourceArn string `json:"resourceArn,omitempty" cfn:"ResourceArn"`

	// The policy rule number associated with the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment attachment..
	// Read-only: reported by AWS after creation.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`

	// The name of the network function group attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`

	// Creation time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Last update time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	UpdatedAt string `json:"updatedAt,omitempty" cfn:"UpdatedAt"`

	// Errors from the last modification of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerDirectConnectGatewayAttachment manages AWS::NetworkManager::DirectConnectGatewayAttachment
// through the AWS Cloud Control API. AWS::NetworkManager::DirectConnectGatewayAttachment Resource Type
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerDirectConnectGatewayAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerDirectConnectGatewayAttachmentSpec   `json:"spec,omitempty"`
	Status NetworkManagerDirectConnectGatewayAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerDirectConnectGatewayAttachmentList contains a list of NetworkManagerDirectConnectGatewayAttachment.
type NetworkManagerDirectConnectGatewayAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerDirectConnectGatewayAttachment `json:"items"`
}

func (o *NetworkManagerDirectConnectGatewayAttachment) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerDirectConnectGatewayAttachment) CloudControlTypeName() string {
	return "AWS::NetworkManager::DirectConnectGatewayAttachment"
}
func (o *NetworkManagerDirectConnectGatewayAttachment) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerDirectConnectGatewayAttachment) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerDirectConnectGatewayAttachment) CloudControlObserved() interface{} {
	return &o.Status
}

// NetworkManagerDirectConnectGatewayAttachmentProposedSegmentChange is a nested property type of AWS::NetworkManager::DirectConnectGatewayAttachment.
type NetworkManagerDirectConnectGatewayAttachmentProposedSegmentChange struct {
	// The key-value tags that changed for the segment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment to change.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`
}

// NetworkManagerDirectConnectGatewayAttachmentProposedNetworkFunctionGroupChange is a nested property type of AWS::NetworkManager::DirectConnectGatewayAttachment.
type NetworkManagerDirectConnectGatewayAttachmentProposedNetworkFunctionGroupChange struct {
	// The key-value tags that changed for the network function group.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the network function group to change.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`
}

// NetworkManagerGlobalNetworkSpec is the desired state of AWS::NetworkManager::GlobalNetwork.
type NetworkManagerGlobalNetworkSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the global network.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The tags for the global network.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The date and time that the global network was created.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// The state of the global network.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`
}

// NetworkManagerGlobalNetworkStatus is the observed state of AWS::NetworkManager::GlobalNetwork.
type NetworkManagerGlobalNetworkStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the global network.
	// Read-only: reported by AWS after creation.
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`

	// The ID of the global network.
	// Read-only: reported by AWS after creation.
	// +optional
	Id string `json:"id,omitempty" cfn:"Id"`
}

// NetworkManagerGlobalNetwork manages AWS::NetworkManager::GlobalNetwork through the AWS Cloud Control API. The
// AWS::NetworkManager::GlobalNetwork type specifies a global network of the user's account
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerGlobalNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerGlobalNetworkSpec   `json:"spec,omitempty"`
	Status NetworkManagerGlobalNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerGlobalNetworkList contains a list of NetworkManagerGlobalNetwork.
type NetworkManagerGlobalNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerGlobalNetwork `json:"items"`
}

func (o *NetworkManagerGlobalNetwork) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *NetworkManagerGlobalNetwork) CloudControlTypeName() string {
	return "AWS::NetworkManager::GlobalNetwork"
}
func (o *NetworkManagerGlobalNetwork) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerGlobalNetwork) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerGlobalNetwork) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerLinkSpec is the desired state of AWS::NetworkManager::Link.
type NetworkManagerLinkSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of the global network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// The ID of the site
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="siteId is immutable"
	SiteId string `json:"siteId" cfn:"SiteId"`

	// The Bandwidth for the link.
	Bandwidth NetworkManagerLinkBandwidth `json:"bandwidth" cfn:"Bandwidth"`

	// The provider of the link.
	// +optional
	Provider string `json:"provider,omitempty" cfn:"Provider"`

	// The description of the link.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The tags for the link.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The type of the link.
	// +optional
	Type string `json:"type,omitempty" cfn:"Type"`
}

// NetworkManagerLinkStatus is the observed state of AWS::NetworkManager::Link.
type NetworkManagerLinkStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the link.
	// Read-only: reported by AWS after creation.
	// +optional
	LinkArn string `json:"linkArn,omitempty" cfn:"LinkArn"`

	// The ID of the link.
	// Read-only: reported by AWS after creation.
	// +optional
	LinkId string `json:"linkId,omitempty" cfn:"LinkId"`

	// The date and time that the device was created.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// The state of the link.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`
}

// NetworkManagerLink manages AWS::NetworkManager::Link through the AWS Cloud Control API. The
// AWS::NetworkManager::Link type describes a link.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerLink struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerLinkSpec   `json:"spec,omitempty"`
	Status NetworkManagerLinkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerLinkList contains a list of NetworkManagerLink.
type NetworkManagerLinkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerLink `json:"items"`
}

func (o *NetworkManagerLink) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *NetworkManagerLink) CloudControlTypeName() string  { return "AWS::NetworkManager::Link" }
func (o *NetworkManagerLink) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerLink) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerLink) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerLinkBandwidth is a nested property type of AWS::NetworkManager::Link.
type NetworkManagerLinkBandwidth struct {
	// Download speed in Mbps.
	// +optional
	DownloadSpeed *int64 `json:"downloadSpeed,omitempty" cfn:"DownloadSpeed"`

	// Upload speed in Mbps.
	// +optional
	UploadSpeed *int64 `json:"uploadSpeed,omitempty" cfn:"UploadSpeed"`
}

// NetworkManagerLinkAssociationSpec is the desired state of AWS::NetworkManager::LinkAssociation.
type NetworkManagerLinkAssociationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of the global network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// The ID of the device
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="deviceId is immutable"
	DeviceId string `json:"deviceId" cfn:"DeviceId"`

	// The ID of the link
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="linkId is immutable"
	LinkId string `json:"linkId" cfn:"LinkId"`
}

// NetworkManagerLinkAssociationStatus is the observed state of AWS::NetworkManager::LinkAssociation.
type NetworkManagerLinkAssociationStatus struct {
	CloudControlStatus `json:",inline"`
}

// NetworkManagerLinkAssociation manages AWS::NetworkManager::LinkAssociation through the AWS Cloud Control API.
// The AWS::NetworkManager::LinkAssociation type associates a link to a device. The device and link must be in
// the same global network and the same site.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerLinkAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerLinkAssociationSpec   `json:"spec,omitempty"`
	Status NetworkManagerLinkAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerLinkAssociationList contains a list of NetworkManagerLinkAssociation.
type NetworkManagerLinkAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerLinkAssociation `json:"items"`
}

func (o *NetworkManagerLinkAssociation) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *NetworkManagerLinkAssociation) CloudControlTypeName() string {
	return "AWS::NetworkManager::LinkAssociation"
}
func (o *NetworkManagerLinkAssociation) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerLinkAssociation) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerLinkAssociation) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerSiteSpec is the desired state of AWS::NetworkManager::Site.
type NetworkManagerSiteSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The description of the site.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The tags for the site.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The ID of the global network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// The location of the site.
	// +optional
	Location *NetworkManagerSiteLocation `json:"location,omitempty" cfn:"Location"`
}

// NetworkManagerSiteStatus is the observed state of AWS::NetworkManager::Site.
type NetworkManagerSiteStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the site.
	// Read-only: reported by AWS after creation.
	// +optional
	SiteArn string `json:"siteArn,omitempty" cfn:"SiteArn"`

	// The ID of the site.
	// Read-only: reported by AWS after creation.
	// +optional
	SiteId string `json:"siteId,omitempty" cfn:"SiteId"`

	// The date and time that the device was created.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// The state of the site.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`
}

// NetworkManagerSite manages AWS::NetworkManager::Site through the AWS Cloud Control API. The
// AWS::NetworkManager::Site type describes a site.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerSite struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerSiteSpec   `json:"spec,omitempty"`
	Status NetworkManagerSiteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerSiteList contains a list of NetworkManagerSite.
type NetworkManagerSiteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerSite `json:"items"`
}

func (o *NetworkManagerSite) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *NetworkManagerSite) CloudControlTypeName() string  { return "AWS::NetworkManager::Site" }
func (o *NetworkManagerSite) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerSite) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerSite) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerSiteLocation is a nested property type of AWS::NetworkManager::Site.
type NetworkManagerSiteLocation struct {
	// The physical address.
	// +optional
	Address string `json:"address,omitempty" cfn:"Address"`

	// The latitude.
	// +optional
	Latitude string `json:"latitude,omitempty" cfn:"Latitude"`

	// The longitude.
	// +optional
	Longitude string `json:"longitude,omitempty" cfn:"Longitude"`
}

// NetworkManagerSiteToSiteVpnAttachmentSpec is the desired state of AWS::NetworkManager::SiteToSiteVpnAttachment.
type NetworkManagerSiteToSiteVpnAttachmentSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of a core network where you're creating a site-to-site VPN attachment.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="coreNetworkId is immutable"
	CoreNetworkId string `json:"coreNetworkId" cfn:"CoreNetworkId"`

	// The attachment to move from one segment to another.
	// +optional
	ProposedSegmentChange *NetworkManagerSiteToSiteVpnAttachmentProposedSegmentChange `json:"proposedSegmentChange,omitempty" cfn:"ProposedSegmentChange"`

	// The name of the network function group attachment.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`

	// The attachment to move from one network function group to another.
	// +optional
	ProposedNetworkFunctionGroupChange *NetworkManagerSiteToSiteVpnAttachmentProposedNetworkFunctionGroupChange `json:"proposedNetworkFunctionGroupChange,omitempty" cfn:"ProposedNetworkFunctionGroupChange"`

	// Routing policy label
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	RoutingPolicyLabel string `json:"routingPolicyLabel,omitempty" cfn:"RoutingPolicyLabel"`

	// Tags for the attachment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The ARN of the site-to-site VPN attachment.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="vpnConnectionArn is immutable"
	VpnConnectionArn string `json:"vpnConnectionArn" cfn:"VpnConnectionArn"`
}

// NetworkManagerSiteToSiteVpnAttachmentStatus is the observed state of AWS::NetworkManager::SiteToSiteVpnAttachment.
type NetworkManagerSiteToSiteVpnAttachmentStatus struct {
	CloudControlStatus `json:",inline"`

	// The ARN of a core network for the VPC attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// The ID of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentId string `json:"attachmentId,omitempty" cfn:"AttachmentId"`

	// Owner account of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// The type of attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentType string `json:"attachmentType,omitempty" cfn:"AttachmentType"`

	// The state of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The Region where the edge is located.
	// Read-only: reported by AWS after creation.
	// +optional
	EdgeLocation string `json:"edgeLocation,omitempty" cfn:"EdgeLocation"`

	// The ARN of the Resource.
	// Read-only: reported by AWS after creation.
	// +optional
	ResourceArn string `json:"resourceArn,omitempty" cfn:"ResourceArn"`

	// The policy rule number associated with the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment that attachment is in.
	// Read-only: reported by AWS after creation.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`

	// Creation time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Last update time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	UpdatedAt string `json:"updatedAt,omitempty" cfn:"UpdatedAt"`

	// Errors from the last modification of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerSiteToSiteVpnAttachment manages AWS::NetworkManager::SiteToSiteVpnAttachment through the AWS
// Cloud Control API. AWS::NetworkManager::SiteToSiteVpnAttachment Resource Type definition.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerSiteToSiteVpnAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerSiteToSiteVpnAttachmentSpec   `json:"spec,omitempty"`
	Status NetworkManagerSiteToSiteVpnAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerSiteToSiteVpnAttachmentList contains a list of NetworkManagerSiteToSiteVpnAttachment.
type NetworkManagerSiteToSiteVpnAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerSiteToSiteVpnAttachment `json:"items"`
}

func (o *NetworkManagerSiteToSiteVpnAttachment) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerSiteToSiteVpnAttachment) CloudControlTypeName() string {
	return "AWS::NetworkManager::SiteToSiteVpnAttachment"
}
func (o *NetworkManagerSiteToSiteVpnAttachment) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerSiteToSiteVpnAttachment) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerSiteToSiteVpnAttachment) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerSiteToSiteVpnAttachmentProposedSegmentChange is a nested property type of AWS::NetworkManager::SiteToSiteVpnAttachment.
type NetworkManagerSiteToSiteVpnAttachmentProposedSegmentChange struct {
	// The key-value tags that changed for the segment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment to change.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`
}

// NetworkManagerSiteToSiteVpnAttachmentProposedNetworkFunctionGroupChange is a nested property type of AWS::NetworkManager::SiteToSiteVpnAttachment.
type NetworkManagerSiteToSiteVpnAttachmentProposedNetworkFunctionGroupChange struct {
	// The key-value tags that changed for the network function group.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the network function group to change.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`
}

// NetworkManagerTransitGatewayPeeringSpec is the desired state of AWS::NetworkManager::TransitGatewayPeering.
type NetworkManagerTransitGatewayPeeringSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The Id of the core network that you want to peer a transit gateway to.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="coreNetworkId is immutable"
	CoreNetworkId string `json:"coreNetworkId" cfn:"CoreNetworkId"`

	// The ARN (Amazon Resource Name) of the transit gateway that you will peer to a core network
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="transitGatewayArn is immutable"
	TransitGatewayArn string `json:"transitGatewayArn" cfn:"TransitGatewayArn"`

	// An array of key-value pairs to apply to this resource.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// NetworkManagerTransitGatewayPeeringStatus is the observed state of AWS::NetworkManager::TransitGatewayPeering.
type NetworkManagerTransitGatewayPeeringStatus struct {
	CloudControlStatus `json:",inline"`

	// The ARN (Amazon Resource Name) of the core network that you want to peer a transit gateway to.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// The ID of the TransitGatewayPeeringAttachment
	// Read-only: reported by AWS after creation.
	// +optional
	TransitGatewayPeeringAttachmentId string `json:"transitGatewayPeeringAttachmentId,omitempty" cfn:"TransitGatewayPeeringAttachmentId"`

	// The Id of the transit gateway peering
	// Read-only: reported by AWS after creation.
	// +optional
	PeeringId string `json:"peeringId,omitempty" cfn:"PeeringId"`

	// The state of the transit gateway peering
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The location of the transit gateway peering
	// Read-only: reported by AWS after creation.
	// +optional
	EdgeLocation string `json:"edgeLocation,omitempty" cfn:"EdgeLocation"`

	// The ARN (Amazon Resource Name) of the resource that you will peer to a core network
	// Read-only: reported by AWS after creation.
	// +optional
	ResourceArn string `json:"resourceArn,omitempty" cfn:"ResourceArn"`

	// Peering owner account Id
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// Peering type (TransitGatewayPeering)
	// Read-only: reported by AWS after creation.
	// +optional
	PeeringType string `json:"peeringType,omitempty" cfn:"PeeringType"`

	// The creation time of the transit gateway peering
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Errors from the last modification of the transit gateway peering.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerTransitGatewayPeering manages AWS::NetworkManager::TransitGatewayPeering through the AWS Cloud
// Control API. AWS::NetworkManager::TransitGatewayPeering Resoruce Type.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerTransitGatewayPeering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerTransitGatewayPeeringSpec   `json:"spec,omitempty"`
	Status NetworkManagerTransitGatewayPeeringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerTransitGatewayPeeringList contains a list of NetworkManagerTransitGatewayPeering.
type NetworkManagerTransitGatewayPeeringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerTransitGatewayPeering `json:"items"`
}

func (o *NetworkManagerTransitGatewayPeering) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerTransitGatewayPeering) CloudControlTypeName() string {
	return "AWS::NetworkManager::TransitGatewayPeering"
}
func (o *NetworkManagerTransitGatewayPeering) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerTransitGatewayPeering) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerTransitGatewayPeering) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerTransitGatewayRegistrationSpec is the desired state of AWS::NetworkManager::TransitGatewayRegistration.
type NetworkManagerTransitGatewayRegistrationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of the global network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="globalNetworkId is immutable"
	GlobalNetworkId string `json:"globalNetworkId" cfn:"GlobalNetworkId"`

	// The Amazon Resource Name (ARN) of the transit gateway.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="transitGatewayArn is immutable"
	TransitGatewayArn string `json:"transitGatewayArn" cfn:"TransitGatewayArn"`
}

// NetworkManagerTransitGatewayRegistrationStatus is the observed state of AWS::NetworkManager::TransitGatewayRegistration.
type NetworkManagerTransitGatewayRegistrationStatus struct {
	CloudControlStatus `json:",inline"`
}

// NetworkManagerTransitGatewayRegistration manages AWS::NetworkManager::TransitGatewayRegistration through the
// AWS Cloud Control API. The AWS::NetworkManager::TransitGatewayRegistration type registers a transit gateway in
// your global network. The transit gateway can be in any AWS Region, but it must be owned by the same AWS
// account that owns the global network. You cannot register a transit gatew...
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerTransitGatewayRegistration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerTransitGatewayRegistrationSpec   `json:"spec,omitempty"`
	Status NetworkManagerTransitGatewayRegistrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerTransitGatewayRegistrationList contains a list of NetworkManagerTransitGatewayRegistration.
type NetworkManagerTransitGatewayRegistrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerTransitGatewayRegistration `json:"items"`
}

func (o *NetworkManagerTransitGatewayRegistration) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerTransitGatewayRegistration) CloudControlTypeName() string {
	return "AWS::NetworkManager::TransitGatewayRegistration"
}
func (o *NetworkManagerTransitGatewayRegistration) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerTransitGatewayRegistration) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerTransitGatewayRegistration) CloudControlObserved() interface{} {
	return &o.Status
}

// NetworkManagerTransitGatewayRouteTableAttachmentSpec is the desired state of AWS::NetworkManager::TransitGatewayRouteTableAttachment.
type NetworkManagerTransitGatewayRouteTableAttachmentSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The Id of peering between transit gateway and core network.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="peeringId is immutable"
	PeeringId string `json:"peeringId" cfn:"PeeringId"`

	// The Arn of transit gateway route table.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="transitGatewayRouteTableArn is immutable"
	TransitGatewayRouteTableArn string `json:"transitGatewayRouteTableArn" cfn:"TransitGatewayRouteTableArn"`

	// The attachment to move from one segment to another.
	// +optional
	ProposedSegmentChange *NetworkManagerTransitGatewayRouteTableAttachmentProposedSegmentChange `json:"proposedSegmentChange,omitempty" cfn:"ProposedSegmentChange"`

	// The name of the network function group attachment.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`

	// The attachment to move from one network function group to another.
	// +optional
	ProposedNetworkFunctionGroupChange *NetworkManagerTransitGatewayRouteTableAttachmentProposedNetworkFunctionGroupChange `json:"proposedNetworkFunctionGroupChange,omitempty" cfn:"ProposedNetworkFunctionGroupChange"`

	// Routing policy label
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	RoutingPolicyLabel string `json:"routingPolicyLabel,omitempty" cfn:"RoutingPolicyLabel"`

	// An array of key-value pairs to apply to this resource.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// NetworkManagerTransitGatewayRouteTableAttachmentStatus is the observed state of AWS::NetworkManager::TransitGatewayRouteTableAttachment.
type NetworkManagerTransitGatewayRouteTableAttachmentStatus struct {
	CloudControlStatus `json:",inline"`

	// The ID of a core network where you're creating a site-to-site VPN attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkId string `json:"coreNetworkId,omitempty" cfn:"CoreNetworkId"`

	// The ARN of a core network for the VPC attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// The ID of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentId string `json:"attachmentId,omitempty" cfn:"AttachmentId"`

	// Owner account of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// The type of attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentType string `json:"attachmentType,omitempty" cfn:"AttachmentType"`

	// The state of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The Region where the edge is located.
	// Read-only: reported by AWS after creation.
	// +optional
	EdgeLocation string `json:"edgeLocation,omitempty" cfn:"EdgeLocation"`

	// The ARN of the Resource.
	// Read-only: reported by AWS after creation.
	// +optional
	ResourceArn string `json:"resourceArn,omitempty" cfn:"ResourceArn"`

	// The policy rule number associated with the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment that attachment is in.
	// Read-only: reported by AWS after creation.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`

	// Creation time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Last update time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	UpdatedAt string `json:"updatedAt,omitempty" cfn:"UpdatedAt"`

	// Errors from the last modification of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerTransitGatewayRouteTableAttachment manages
// AWS::NetworkManager::TransitGatewayRouteTableAttachment through the AWS Cloud Control API.
// AWS::NetworkManager::TransitGatewayRouteTableAttachment Resource Type definition.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerTransitGatewayRouteTableAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerTransitGatewayRouteTableAttachmentSpec   `json:"spec,omitempty"`
	Status NetworkManagerTransitGatewayRouteTableAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerTransitGatewayRouteTableAttachmentList contains a list of NetworkManagerTransitGatewayRouteTableAttachment.
type NetworkManagerTransitGatewayRouteTableAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerTransitGatewayRouteTableAttachment `json:"items"`
}

func (o *NetworkManagerTransitGatewayRouteTableAttachment) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *NetworkManagerTransitGatewayRouteTableAttachment) CloudControlTypeName() string {
	return "AWS::NetworkManager::TransitGatewayRouteTableAttachment"
}
func (o *NetworkManagerTransitGatewayRouteTableAttachment) CloudControlSpec() interface{} {
	return &o.Spec
}
func (o *NetworkManagerTransitGatewayRouteTableAttachment) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerTransitGatewayRouteTableAttachment) CloudControlObserved() interface{} {
	return &o.Status
}

// NetworkManagerTransitGatewayRouteTableAttachmentProposedSegmentChange is a nested property type of AWS::NetworkManager::TransitGatewayRouteTableAttachment.
type NetworkManagerTransitGatewayRouteTableAttachmentProposedSegmentChange struct {
	// The key-value tags that changed for the segment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment to change.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`
}

// NetworkManagerTransitGatewayRouteTableAttachmentProposedNetworkFunctionGroupChange is a nested property type of AWS::NetworkManager::TransitGatewayRouteTableAttachment.
type NetworkManagerTransitGatewayRouteTableAttachmentProposedNetworkFunctionGroupChange struct {
	// The key-value tags that changed for the network function group.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the network function group to change.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`
}

// NetworkManagerVpcAttachmentSpec is the desired state of AWS::NetworkManager::VpcAttachment.
type NetworkManagerVpcAttachmentSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The ID of a core network for the VPC attachment.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="coreNetworkId is immutable"
	CoreNetworkId string `json:"coreNetworkId" cfn:"CoreNetworkId"`

	// The ARN of the VPC.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="vpcArn is immutable"
	VpcArn string `json:"vpcArn" cfn:"VpcArn"`

	// The attachment to move from one segment to another.
	// +optional
	ProposedSegmentChange *NetworkManagerVpcAttachmentProposedSegmentChange `json:"proposedSegmentChange,omitempty" cfn:"ProposedSegmentChange"`

	// The attachment to move from one network function group to another.
	// +optional
	ProposedNetworkFunctionGroupChange *NetworkManagerVpcAttachmentProposedNetworkFunctionGroupChange `json:"proposedNetworkFunctionGroupChange,omitempty" cfn:"ProposedNetworkFunctionGroupChange"`

	// Routing policy label
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	RoutingPolicyLabel string `json:"routingPolicyLabel,omitempty" cfn:"RoutingPolicyLabel"`

	// Tags for the attachment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// Subnet Arn list
	SubnetArns []string `json:"subnetArns" cfn:"SubnetArns"`

	// Vpc options of the attachment.
	// +optional
	Options *NetworkManagerVpcAttachmentVpcOptions `json:"options,omitempty" cfn:"Options"`
}

// NetworkManagerVpcAttachmentStatus is the observed state of AWS::NetworkManager::VpcAttachment.
type NetworkManagerVpcAttachmentStatus struct {
	CloudControlStatus `json:",inline"`

	// The ARN of a core network for the VPC attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CoreNetworkArn string `json:"coreNetworkArn,omitempty" cfn:"CoreNetworkArn"`

	// Id of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentId string `json:"attachmentId,omitempty" cfn:"AttachmentId"`

	// Owner account of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// Attachment type.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentType string `json:"attachmentType,omitempty" cfn:"AttachmentType"`

	// State of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	State string `json:"state,omitempty" cfn:"State"`

	// The Region where the edge is located.
	// Read-only: reported by AWS after creation.
	// +optional
	EdgeLocation string `json:"edgeLocation,omitempty" cfn:"EdgeLocation"`

	// The ARN of the Resource.
	// Read-only: reported by AWS after creation.
	// +optional
	ResourceArn string `json:"resourceArn,omitempty" cfn:"ResourceArn"`

	// The policy rule number associated with the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment attachment..
	// Read-only: reported by AWS after creation.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`

	// The name of the network function group attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`

	// Creation time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt string `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Last update time of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	UpdatedAt string `json:"updatedAt,omitempty" cfn:"UpdatedAt"`

	// Errors from the last modification of the attachment.
	// Read-only: reported by AWS after creation.
	// +optional
	LastModificationErrors []string `json:"lastModificationErrors,omitempty" cfn:"LastModificationErrors"`
}

// NetworkManagerVpcAttachment manages AWS::NetworkManager::VpcAttachment through the AWS Cloud Control API.
// AWS::NetworkManager::VpcAttachment Resoruce Type
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type NetworkManagerVpcAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkManagerVpcAttachmentSpec   `json:"spec,omitempty"`
	Status NetworkManagerVpcAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkManagerVpcAttachmentList contains a list of NetworkManagerVpcAttachment.
type NetworkManagerVpcAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkManagerVpcAttachment `json:"items"`
}

func (o *NetworkManagerVpcAttachment) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *NetworkManagerVpcAttachment) CloudControlTypeName() string {
	return "AWS::NetworkManager::VpcAttachment"
}
func (o *NetworkManagerVpcAttachment) CloudControlSpec() interface{} { return &o.Spec }
func (o *NetworkManagerVpcAttachment) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *NetworkManagerVpcAttachment) CloudControlObserved() interface{} { return &o.Status }

// NetworkManagerVpcAttachmentProposedSegmentChange is a nested property type of AWS::NetworkManager::VpcAttachment.
type NetworkManagerVpcAttachmentProposedSegmentChange struct {
	// The key-value tags that changed for the segment.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the segment to change.
	// +optional
	SegmentName string `json:"segmentName,omitempty" cfn:"SegmentName"`
}

// NetworkManagerVpcAttachmentProposedNetworkFunctionGroupChange is a nested property type of AWS::NetworkManager::VpcAttachment.
type NetworkManagerVpcAttachmentProposedNetworkFunctionGroupChange struct {
	// The key-value tags that changed for the network function group.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// The rule number in the policy document that applies to this change.
	// +optional
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty" cfn:"AttachmentPolicyRuleNumber"`

	// The name of the network function group to change.
	// +optional
	NetworkFunctionGroupName string `json:"networkFunctionGroupName,omitempty" cfn:"NetworkFunctionGroupName"`
}

// NetworkManagerVpcAttachmentVpcOptions is a nested property type of AWS::NetworkManager::VpcAttachment.
type NetworkManagerVpcAttachmentVpcOptions struct {
	// Indicates whether to enable Ipv6 Support for Vpc Attachment. Valid Values: enable | disable
	// +optional
	Ipv6Support *bool `json:"ipv6Support,omitempty" cfn:"Ipv6Support"`

	// Indicates whether to enable ApplianceModeSupport Support for Vpc Attachment. Valid Values: true | false
	// +optional
	ApplianceModeSupport *bool `json:"applianceModeSupport,omitempty" cfn:"ApplianceModeSupport"`

	// Indicates whether to enable private DNS Support for Vpc Attachment. Valid Values: true | false
	// +optional
	DnsSupport *bool `json:"dnsSupport,omitempty" cfn:"DnsSupport"`

	// Indicates whether to enable Security Group Referencing Support for Vpc Attachment. Valid Values: true | false
	// +optional
	SecurityGroupReferencingSupport *bool `json:"securityGroupReferencingSupport,omitempty" cfn:"SecurityGroupReferencingSupport"`
}

func init() {
	SchemeBuilder.Register(&NetworkManagerConnectAttachment{}, &NetworkManagerConnectAttachmentList{})
	SchemeBuilder.Register(&NetworkManagerConnectPeer{}, &NetworkManagerConnectPeerList{})
	SchemeBuilder.Register(&NetworkManagerCoreNetwork{}, &NetworkManagerCoreNetworkList{})
	SchemeBuilder.Register(&NetworkManagerCoreNetworkPrefixListAssociation{}, &NetworkManagerCoreNetworkPrefixListAssociationList{})
	SchemeBuilder.Register(&NetworkManagerCustomerGatewayAssociation{}, &NetworkManagerCustomerGatewayAssociationList{})
	SchemeBuilder.Register(&NetworkManagerDevice{}, &NetworkManagerDeviceList{})
	SchemeBuilder.Register(&NetworkManagerDirectConnectGatewayAttachment{}, &NetworkManagerDirectConnectGatewayAttachmentList{})
	SchemeBuilder.Register(&NetworkManagerGlobalNetwork{}, &NetworkManagerGlobalNetworkList{})
	SchemeBuilder.Register(&NetworkManagerLink{}, &NetworkManagerLinkList{})
	SchemeBuilder.Register(&NetworkManagerLinkAssociation{}, &NetworkManagerLinkAssociationList{})
	SchemeBuilder.Register(&NetworkManagerSite{}, &NetworkManagerSiteList{})
	SchemeBuilder.Register(&NetworkManagerSiteToSiteVpnAttachment{}, &NetworkManagerSiteToSiteVpnAttachmentList{})
	SchemeBuilder.Register(&NetworkManagerTransitGatewayPeering{}, &NetworkManagerTransitGatewayPeeringList{})
	SchemeBuilder.Register(&NetworkManagerTransitGatewayRegistration{}, &NetworkManagerTransitGatewayRegistrationList{})
	SchemeBuilder.Register(&NetworkManagerTransitGatewayRouteTableAttachment{}, &NetworkManagerTransitGatewayRouteTableAttachmentList{})
	SchemeBuilder.Register(&NetworkManagerVpcAttachment{}, &NetworkManagerVpcAttachmentList{})
}
