/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// BillingBillingViewSpec is the desired state of AWS::Billing::BillingView.
type BillingBillingViewSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +optional
	DataFilterExpression *BillingBillingViewDataFilterExpression `json:"dataFilterExpression,omitempty" cfn:"DataFilterExpression"`

	// +kubebuilder:validation:MaxLength=1024
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="name is immutable"
	Name string `json:"name" cfn:"Name"`

	// An array of key-value pairs associated to the billing view being created.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`

	// An array of strings that define the billing view's source.
	SourceViews []string `json:"sourceViews" cfn:"SourceViews"`
}

// BillingBillingViewStatus is the observed state of AWS::Billing::BillingView.
type BillingBillingViewStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`

	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:Enum=PRIMARY;BILLING_GROUP;CUSTOM
	// +optional
	BillingViewType string `json:"billingViewType,omitempty" cfn:"BillingViewType"`

	// The time when the billing view was created.
	// Read-only: reported by AWS after creation.
	// +optional
	CreatedAt *float64 `json:"createdAt,omitempty" cfn:"CreatedAt"`

	// Read-only: reported by AWS after creation.
	// +optional
	OwnerAccountId string `json:"ownerAccountId,omitempty" cfn:"OwnerAccountId"`

	// The time when the billing view was last updated.
	// Read-only: reported by AWS after creation.
	// +optional
	UpdatedAt *float64 `json:"updatedAt,omitempty" cfn:"UpdatedAt"`
}

// BillingBillingView manages AWS::Billing::BillingView through the AWS Cloud Control API. A billing view is a
// container of cost & usage metadata.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BillingBillingView struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BillingBillingViewSpec   `json:"spec,omitempty"`
	Status BillingBillingViewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BillingBillingViewList contains a list of BillingBillingView.
type BillingBillingViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BillingBillingView `json:"items"`
}

func (o *BillingBillingView) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *BillingBillingView) CloudControlTypeName() string  { return "AWS::Billing::BillingView" }
func (o *BillingBillingView) CloudControlSpec() interface{} { return &o.Spec }
func (o *BillingBillingView) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BillingBillingView) CloudControlObserved() interface{} { return &o.Status }

// BillingBillingViewDataFilterExpression is a nested property type of AWS::Billing::BillingView.
type BillingBillingViewDataFilterExpression struct {
	// +optional
	Dimensions *BillingBillingViewDataFilterExpressionDimensions `json:"dimensions,omitempty" cfn:"Dimensions"`

	// +optional
	Tags *BillingBillingViewDataFilterExpressionTags `json:"tags,omitempty" cfn:"Tags"`

	// +optional
	TimeRange *BillingBillingViewDataFilterExpressionTimeRange `json:"timeRange,omitempty" cfn:"TimeRange"`
}

// BillingBillingViewDataFilterExpressionDimensions is a nested property type of AWS::Billing::BillingView.
type BillingBillingViewDataFilterExpressionDimensions struct {
	// +kubebuilder:validation:Enum=LINKED_ACCOUNT
	// +optional
	Key string `json:"key,omitempty" cfn:"Key"`

	// +optional
	Values []string `json:"values,omitempty" cfn:"Values"`
}

// BillingBillingViewDataFilterExpressionTags is a nested property type of AWS::Billing::BillingView.
type BillingBillingViewDataFilterExpressionTags struct {
	// +kubebuilder:validation:MaxLength=1024
	// +optional
	Key string `json:"key,omitempty" cfn:"Key"`

	// +optional
	Values []string `json:"values,omitempty" cfn:"Values"`
}

// BillingBillingViewDataFilterExpressionTimeRange is a nested property type of AWS::Billing::BillingView.
type BillingBillingViewDataFilterExpressionTimeRange struct {
	// +optional
	BeginDateInclusive string `json:"beginDateInclusive,omitempty" cfn:"BeginDateInclusive"`

	// +optional
	EndDateInclusive string `json:"endDateInclusive,omitempty" cfn:"EndDateInclusive"`
}

func init() {
	SchemeBuilder.Register(&BillingBillingView{}, &BillingBillingViewList{})
}
