/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// BackupFrameworkSpec is the desired state of AWS::Backup::Framework.
type BackupFrameworkSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The unique name of a framework. This name is between 1 and 256 characters, starting with a letter, and
	// consisting of letters (a-z, A-Z), numbers (0-9), and underscores (_).
	// +kubebuilder:validation:MaxLength=256
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	FrameworkName string `json:"frameworkName,omitempty" cfn:"FrameworkName"`

	// An optional description of the framework with a maximum 1,024 characters.
	// +kubebuilder:validation:MaxLength=1024
	// +optional
	FrameworkDescription string `json:"frameworkDescription,omitempty" cfn:"FrameworkDescription"`

	// Contains detailed information about all of the controls of a framework. Each framework must contain at least
	// one control.
	FrameworkControls []BackupFrameworkFrameworkControl `json:"frameworkControls" cfn:"FrameworkControls"`

	// Metadata that you can assign to help organize the frameworks that you create. Each tag is a key-value pair.
	// +optional
	FrameworkTags []CFNTag `json:"frameworkTags,omitempty" cfn:"FrameworkTags"`
}

// BackupFrameworkStatus is the observed state of AWS::Backup::Framework.
type BackupFrameworkStatus struct {
	CloudControlStatus `json:",inline"`

	// An Amazon Resource Name (ARN) that uniquely identifies Framework as a resource
	// Read-only: reported by AWS after creation.
	// +optional
	FrameworkArn string `json:"frameworkArn,omitempty" cfn:"FrameworkArn"`

	// The deployment status of a framework. The statuses are: `CREATE_IN_PROGRESS | UPDATE_IN_PROGRESS |
	// DELETE_IN_PROGRESS | COMPLETED | FAILED`
	// Read-only: reported by AWS after creation.
	// +optional
	DeploymentStatus string `json:"deploymentStatus,omitempty" cfn:"DeploymentStatus"`

	// The date and time that a framework is created, in ISO 8601 representation. The value of CreationTime is
	// accurate to milliseconds. For example, 2020-07-10T15:00:00.000-08:00 represents the 10th of July 2020 at 3:00
	// PM 8 hours behind UTC.
	// Read-only: reported by AWS after creation.
	// +optional
	CreationTime string `json:"creationTime,omitempty" cfn:"CreationTime"`

	// A framework consists of one or more controls. Each control governs a resource, such as backup plans, backup
	// selections, backup vaults, or recovery points. You can also turn AWS Config recording on or off for each
	// resource. The statuses are: `ACTIVE` when recording is turned on for all resources governed by the framework.
	// `PARTIALLY_ACTIVE` when recording is turned off for at least one resource ...
	// Read-only: reported by AWS after creation.
	// +optional
	FrameworkStatus string `json:"frameworkStatus,omitempty" cfn:"FrameworkStatus"`
}

// BackupFramework manages AWS::Backup::Framework through the AWS Cloud Control API. Contains detailed
// information about a framework. Frameworks contain controls, which evaluate and report on your backup events
// and resources. Frameworks generate daily compliance results.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupFramework struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupFrameworkSpec   `json:"spec,omitempty"`
	Status BackupFrameworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupFrameworkList contains a list of BackupFramework.
type BackupFrameworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupFramework `json:"items"`
}

func (o *BackupFramework) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *BackupFramework) CloudControlTypeName() string  { return "AWS::Backup::Framework" }
func (o *BackupFramework) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupFramework) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupFramework) CloudControlObserved() interface{} { return &o.Status }

// BackupFrameworkFrameworkControl is a nested property type of AWS::Backup::Framework.
type BackupFrameworkFrameworkControl struct {
	// The name of a control. This name is between 1 and 256 characters.
	ControlName string `json:"controlName" cfn:"ControlName"`

	// A list of ParameterName and ParameterValue pairs.
	// +optional
	ControlInputParameters []BackupFrameworkControlInputParameter `json:"controlInputParameters,omitempty" cfn:"ControlInputParameters"`

	// The scope of a control. The control scope defines what the control will evaluate. Three examples of control
	// scopes are: a specific backup plan, all backup plans with a specific tag, or all backup plans.
	// +optional
	ControlScope *BackupFrameworkFrameworkControlControlScope `json:"controlScope,omitempty" cfn:"ControlScope"`
}

// BackupFrameworkControlInputParameter is a nested property type of AWS::Backup::Framework.
type BackupFrameworkControlInputParameter struct {
	ParameterName string `json:"parameterName" cfn:"ParameterName"`

	ParameterValue string `json:"parameterValue" cfn:"ParameterValue"`
}

// BackupFrameworkFrameworkControlControlScope is a nested property type of AWS::Backup::Framework.
type BackupFrameworkFrameworkControlControlScope struct {
	// The ID of the only AWS resource that you want your control scope to contain.
	// +optional
	ComplianceResourceIds []string `json:"complianceResourceIds,omitempty" cfn:"ComplianceResourceIds"`

	// Describes whether the control scope includes one or more types of resources, such as `EFS` or `RDS`.
	// +optional
	ComplianceResourceTypes []string `json:"complianceResourceTypes,omitempty" cfn:"ComplianceResourceTypes"`

	// Describes whether the control scope includes resources with one or more tags. Each tag is a key-value pair.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// BackupLegalHoldSpec is the desired state of AWS::Backup::LegalHold.
type BackupLegalHoldSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The title of the legal hold.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="title is immutable"
	Title string `json:"title" cfn:"Title"`

	// The description of the legal hold.
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="description is immutable"
	Description string `json:"description" cfn:"Description"`

	// The criteria to assign a set of resources, such as resource types or backup vaults.
	// Create-only in AWS: changing it requires replacing the resource.
	RecoveryPointSelection BackupLegalHoldRecoveryPointSelection `json:"recoveryPointSelection" cfn:"RecoveryPointSelection"`

	// Optional tags to include.
	// +optional
	Tags []BackupLegalHoldTagsItem `json:"tags,omitempty" cfn:"Tags"`
}

// BackupLegalHoldStatus is the observed state of AWS::Backup::LegalHold.
type BackupLegalHoldStatus struct {
	CloudControlStatus `json:",inline"`

	// The Amazon Resource Name (ARN) of the legal hold.
	// Read-only: reported by AWS after creation.
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`

	// The ID of the legal hold.
	// Read-only: reported by AWS after creation.
	// +optional
	LegalHoldId string `json:"legalHoldId,omitempty" cfn:"LegalHoldId"`

	// The status of the legal hold.
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:Enum=CREATING;ACTIVE;CANCELING;CANCELED
	// +optional
	Status string `json:"status,omitempty" cfn:"Status"`

	// The time when the legal hold was created.
	// Read-only: reported by AWS after creation.
	// +optional
	CreationDate string `json:"creationDate,omitempty" cfn:"CreationDate"`
}

// BackupLegalHold manages AWS::Backup::LegalHold through the AWS Cloud Control API. Creates a legal hold on
// recovery points (backups). A legal hold prevents backups from being deleted while under hold.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupLegalHold struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupLegalHoldSpec   `json:"spec,omitempty"`
	Status BackupLegalHoldStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupLegalHoldList contains a list of BackupLegalHold.
type BackupLegalHoldList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupLegalHold `json:"items"`
}

func (o *BackupLegalHold) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *BackupLegalHold) CloudControlTypeName() string  { return "AWS::Backup::LegalHold" }
func (o *BackupLegalHold) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupLegalHold) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupLegalHold) CloudControlObserved() interface{} { return &o.Status }

// BackupLegalHoldRecoveryPointSelection is a nested property type of AWS::Backup::LegalHold.
type BackupLegalHoldRecoveryPointSelection struct {
	// The names of the vaults in which the selected recovery points are contained.
	// +optional
	VaultNames []string `json:"vaultNames,omitempty" cfn:"VaultNames"`

	// The resources included in the resource selection.
	// +optional
	ResourceIdentifiers []string `json:"resourceIdentifiers,omitempty" cfn:"ResourceIdentifiers"`

	// A date range for filtering recovery points.
	// +optional
	DateRange *BackupLegalHoldRecoveryPointSelectionDateRange `json:"dateRange,omitempty" cfn:"DateRange"`
}

// BackupLegalHoldRecoveryPointSelectionDateRange is a nested property type of AWS::Backup::LegalHold.
type BackupLegalHoldRecoveryPointSelectionDateRange struct {
	// The beginning date, inclusive. ISO 8601 date-time.
	FromDate string `json:"fromDate" cfn:"FromDate"`

	// The end date, inclusive. ISO 8601 date-time.
	ToDate string `json:"toDate" cfn:"ToDate"`
}

// BackupLegalHoldTagsItem is a nested property type of AWS::Backup::LegalHold.
type BackupLegalHoldTagsItem struct {
	// The key name of the tag.
	Key string `json:"key" cfn:"Key"`

	// The value for the tag.
	Value string `json:"value" cfn:"Value"`
}

// BackupLogicallyAirGappedBackupVaultSpec is the desired state of AWS::Backup::LogicallyAirGappedBackupVault.
type BackupLogicallyAirGappedBackupVaultSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// +kubebuilder:pruning:PreserveUnknownFields
	// +optional
	AccessPolicy apiextensionsv1.JSON `json:"accessPolicy,omitempty" cfn:"AccessPolicy"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="backupVaultName is immutable"
	BackupVaultName string `json:"backupVaultName" cfn:"BackupVaultName"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="minRetentionDays is immutable"
	MinRetentionDays int64 `json:"minRetentionDays" cfn:"MinRetentionDays"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="maxRetentionDays is immutable"
	MaxRetentionDays int64 `json:"maxRetentionDays" cfn:"MaxRetentionDays"`

	// +optional
	BackupVaultTags map[string]string `json:"backupVaultTags,omitempty" cfn:"BackupVaultTags"`

	// +optional
	Notifications *BackupLogicallyAirGappedBackupVaultNotificationObjectType `json:"notifications,omitempty" cfn:"Notifications"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	EncryptionKeyArn string `json:"encryptionKeyArn,omitempty" cfn:"EncryptionKeyArn"`

	// +optional
	MpaApprovalTeamArn string `json:"mpaApprovalTeamArn,omitempty" cfn:"MpaApprovalTeamArn"`
}

// BackupLogicallyAirGappedBackupVaultStatus is the observed state of AWS::Backup::LogicallyAirGappedBackupVault.
type BackupLogicallyAirGappedBackupVaultStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	BackupVaultArn string `json:"backupVaultArn,omitempty" cfn:"BackupVaultArn"`

	// Read-only: reported by AWS after creation.
	// +optional
	VaultState string `json:"vaultState,omitempty" cfn:"VaultState"`

	// Read-only: reported by AWS after creation.
	// +optional
	VaultType string `json:"vaultType,omitempty" cfn:"VaultType"`
}

// BackupLogicallyAirGappedBackupVault manages AWS::Backup::LogicallyAirGappedBackupVault through the AWS Cloud
// Control API. Resource Type definition for AWS::Backup::LogicallyAirGappedBackupVault
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupLogicallyAirGappedBackupVault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupLogicallyAirGappedBackupVaultSpec   `json:"spec,omitempty"`
	Status BackupLogicallyAirGappedBackupVaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupLogicallyAirGappedBackupVaultList contains a list of BackupLogicallyAirGappedBackupVault.
type BackupLogicallyAirGappedBackupVaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupLogicallyAirGappedBackupVault `json:"items"`
}

func (o *BackupLogicallyAirGappedBackupVault) GetProviderRef() *ProviderRef {
	return o.Spec.ProviderRef
}
func (o *BackupLogicallyAirGappedBackupVault) CloudControlTypeName() string {
	return "AWS::Backup::LogicallyAirGappedBackupVault"
}
func (o *BackupLogicallyAirGappedBackupVault) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupLogicallyAirGappedBackupVault) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupLogicallyAirGappedBackupVault) CloudControlObserved() interface{} { return &o.Status }

// BackupLogicallyAirGappedBackupVaultNotificationObjectType is a nested property type of AWS::Backup::LogicallyAirGappedBackupVault.
type BackupLogicallyAirGappedBackupVaultNotificationObjectType struct {
	BackupVaultEvents []string `json:"backupVaultEvents" cfn:"BackupVaultEvents"`

	SNSTopicArn string `json:"snsTopicArn" cfn:"SNSTopicArn"`
}

// BackupReportPlanSpec is the desired state of AWS::Backup::ReportPlan.
type BackupReportPlanSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The unique name of the report plan. The name must be between 1 and 256 characters, starting with a letter, and
	// consisting of letters (a-z, A-Z), numbers (0-9), and underscores (_).
	// +kubebuilder:validation:MaxLength=256
	// Create-only in AWS: changing it requires replacing the resource.
	// +optional
	ReportPlanName string `json:"reportPlanName,omitempty" cfn:"ReportPlanName"`

	// An optional description of the report plan with a maximum of 1,024 characters.
	// +kubebuilder:validation:MaxLength=1024
	// +optional
	ReportPlanDescription string `json:"reportPlanDescription,omitempty" cfn:"ReportPlanDescription"`

	// Metadata that you can assign to help organize the report plans that you create. Each tag is a key-value pair.
	// +optional
	ReportPlanTags []CFNTag `json:"reportPlanTags,omitempty" cfn:"ReportPlanTags"`

	// A structure that contains information about where and how to deliver your reports, specifically your Amazon S3
	// bucket name, S3 key prefix, and the formats of your reports.
	ReportDeliveryChannel BackupReportPlanReportDeliveryChannel `json:"reportDeliveryChannel" cfn:"ReportDeliveryChannel"`

	// Identifies the report template for the report. Reports are built using a report template.
	ReportSetting BackupReportPlanReportSetting `json:"reportSetting" cfn:"ReportSetting"`
}

// BackupReportPlanStatus is the observed state of AWS::Backup::ReportPlan.
type BackupReportPlanStatus struct {
	CloudControlStatus `json:",inline"`

	// An Amazon Resource Name (ARN) that uniquely identifies a resource. The format of the ARN depends on the
	// resource type.
	// Read-only: reported by AWS after creation.
	// +optional
	ReportPlanArn string `json:"reportPlanArn,omitempty" cfn:"ReportPlanArn"`
}

// BackupReportPlan manages AWS::Backup::ReportPlan through the AWS Cloud Control API. Contains detailed
// information about a report plan in AWS Backup Audit Manager.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupReportPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupReportPlanSpec   `json:"spec,omitempty"`
	Status BackupReportPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupReportPlanList contains a list of BackupReportPlan.
type BackupReportPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupReportPlan `json:"items"`
}

func (o *BackupReportPlan) GetProviderRef() *ProviderRef  { return o.Spec.ProviderRef }
func (o *BackupReportPlan) CloudControlTypeName() string  { return "AWS::Backup::ReportPlan" }
func (o *BackupReportPlan) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupReportPlan) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupReportPlan) CloudControlObserved() interface{} { return &o.Status }

// BackupReportPlanReportDeliveryChannel is a nested property type of AWS::Backup::ReportPlan.
type BackupReportPlanReportDeliveryChannel struct {
	// A list of the format of your reports: CSV, JSON, or both. If not specified, the default format is CSV.
	// +optional
	Formats []string `json:"formats,omitempty" cfn:"Formats"`

	// The unique name of the S3 bucket that receives your reports.
	S3BucketName string `json:"s3BucketName" cfn:"S3BucketName"`

	// The prefix for where AWS Backup Audit Manager delivers your reports to Amazon S3. The prefix is this part of
	// the following path: s3://your-bucket-name/prefix/Backup/us-west-2/year/month/day/report-name. If not
	// specified, there is no prefix.
	// +optional
	S3KeyPrefix string `json:"s3KeyPrefix,omitempty" cfn:"S3KeyPrefix"`
}

// BackupReportPlanReportSetting is a nested property type of AWS::Backup::ReportPlan.
type BackupReportPlanReportSetting struct {
	// Identifies the report template for the report. Reports are built using a report template. The report templates
	// are: `BACKUP_JOB_REPORT | COPY_JOB_REPORT | RESTORE_JOB_REPORT`
	ReportTemplate string `json:"reportTemplate" cfn:"ReportTemplate"`

	// The Amazon Resource Names (ARNs) of the frameworks a report covers.
	// +optional
	FrameworkArns []string `json:"frameworkArns,omitempty" cfn:"FrameworkArns"`

	// The list of AWS accounts that a report covers.
	// +optional
	Accounts []string `json:"accounts,omitempty" cfn:"Accounts"`

	// The list of AWS organization units that a report covers.
	// +optional
	OrganizationUnits []string `json:"organizationUnits,omitempty" cfn:"OrganizationUnits"`

	// The list of AWS regions that a report covers.
	// +optional
	Regions []string `json:"regions,omitempty" cfn:"Regions"`
}

// BackupRestoreTestingPlanSpec is the desired state of AWS::Backup::RestoreTestingPlan.
type BackupRestoreTestingPlanSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	RecoveryPointSelection BackupRestoreTestingPlanRestoreTestingRecoveryPointSelection `json:"recoveryPointSelection" cfn:"RecoveryPointSelection"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="restoreTestingPlanName is immutable"
	RestoreTestingPlanName string `json:"restoreTestingPlanName" cfn:"RestoreTestingPlanName"`

	ScheduleExpression string `json:"scheduleExpression" cfn:"ScheduleExpression"`

	// +optional
	ScheduleExpressionTimezone string `json:"scheduleExpressionTimezone,omitempty" cfn:"ScheduleExpressionTimezone"`

	// +optional
	StartWindowHours *int64 `json:"startWindowHours,omitempty" cfn:"StartWindowHours"`

	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// BackupRestoreTestingPlanStatus is the observed state of AWS::Backup::RestoreTestingPlan.
type BackupRestoreTestingPlanStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	RestoreTestingPlanArn string `json:"restoreTestingPlanArn,omitempty" cfn:"RestoreTestingPlanArn"`
}

// BackupRestoreTestingPlan manages AWS::Backup::RestoreTestingPlan through the AWS Cloud Control API. Definition
// of AWS::Backup::RestoreTestingPlan Resource Type
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupRestoreTestingPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupRestoreTestingPlanSpec   `json:"spec,omitempty"`
	Status BackupRestoreTestingPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupRestoreTestingPlanList contains a list of BackupRestoreTestingPlan.
type BackupRestoreTestingPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupRestoreTestingPlan `json:"items"`
}

func (o *BackupRestoreTestingPlan) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *BackupRestoreTestingPlan) CloudControlTypeName() string {
	return "AWS::Backup::RestoreTestingPlan"
}
func (o *BackupRestoreTestingPlan) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupRestoreTestingPlan) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupRestoreTestingPlan) CloudControlObserved() interface{} { return &o.Status }

// BackupRestoreTestingPlanRestoreTestingRecoveryPointSelection is a nested property type of AWS::Backup::RestoreTestingPlan.
type BackupRestoreTestingPlanRestoreTestingRecoveryPointSelection struct {
	// +kubebuilder:validation:Enum=LATEST_WITHIN_WINDOW;RANDOM_WITHIN_WINDOW
	Algorithm string `json:"algorithm" cfn:"Algorithm"`

	// +optional
	SelectionWindowDays *int64 `json:"selectionWindowDays,omitempty" cfn:"SelectionWindowDays"`

	RecoveryPointTypes []string `json:"recoveryPointTypes" cfn:"RecoveryPointTypes"`

	IncludeVaults []string `json:"includeVaults" cfn:"IncludeVaults"`

	// +optional
	ExcludeVaults []string `json:"excludeVaults,omitempty" cfn:"ExcludeVaults"`
}

// BackupRestoreTestingSelectionSpec is the desired state of AWS::Backup::RestoreTestingSelection.
type BackupRestoreTestingSelectionSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	IamRoleArn string `json:"iamRoleArn" cfn:"IamRoleArn"`

	// +optional
	ProtectedResourceArns []string `json:"protectedResourceArns,omitempty" cfn:"ProtectedResourceArns"`

	// +optional
	ProtectedResourceConditions *BackupRestoreTestingSelectionProtectedResourceConditions `json:"protectedResourceConditions,omitempty" cfn:"ProtectedResourceConditions"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="protectedResourceType is immutable"
	ProtectedResourceType string `json:"protectedResourceType" cfn:"ProtectedResourceType"`

	// +optional
	RestoreMetadataOverrides map[string]string `json:"restoreMetadataOverrides,omitempty" cfn:"RestoreMetadataOverrides"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="restoreTestingPlanName is immutable"
	RestoreTestingPlanName string `json:"restoreTestingPlanName" cfn:"RestoreTestingPlanName"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="restoreTestingSelectionName is immutable"
	RestoreTestingSelectionName string `json:"restoreTestingSelectionName" cfn:"RestoreTestingSelectionName"`

	// +optional
	ValidationWindowHours *int64 `json:"validationWindowHours,omitempty" cfn:"ValidationWindowHours"`
}

// BackupRestoreTestingSelectionStatus is the observed state of AWS::Backup::RestoreTestingSelection.
type BackupRestoreTestingSelectionStatus struct {
	CloudControlStatus `json:",inline"`
}

// BackupRestoreTestingSelection manages AWS::Backup::RestoreTestingSelection through the AWS Cloud Control API.
// Resource Type definition for AWS::Backup::RestoreTestingSelection
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupRestoreTestingSelection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupRestoreTestingSelectionSpec   `json:"spec,omitempty"`
	Status BackupRestoreTestingSelectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupRestoreTestingSelectionList contains a list of BackupRestoreTestingSelection.
type BackupRestoreTestingSelectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupRestoreTestingSelection `json:"items"`
}

func (o *BackupRestoreTestingSelection) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *BackupRestoreTestingSelection) CloudControlTypeName() string {
	return "AWS::Backup::RestoreTestingSelection"
}
func (o *BackupRestoreTestingSelection) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupRestoreTestingSelection) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupRestoreTestingSelection) CloudControlObserved() interface{} { return &o.Status }

// BackupRestoreTestingSelectionProtectedResourceConditions is a nested property type of AWS::Backup::RestoreTestingSelection.
type BackupRestoreTestingSelectionProtectedResourceConditions struct {
	// +optional
	StringEquals []CFNTag `json:"stringEquals,omitempty" cfn:"StringEquals"`

	// +optional
	StringNotEquals []CFNTag `json:"stringNotEquals,omitempty" cfn:"StringNotEquals"`
}

// BackupTieringConfigurationSpec is the desired state of AWS::Backup::TieringConfiguration.
type BackupTieringConfigurationSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="tieringConfigurationName is immutable"
	TieringConfigurationName string `json:"tieringConfigurationName" cfn:"TieringConfigurationName"`

	BackupVaultName string `json:"backupVaultName" cfn:"BackupVaultName"`

	ResourceSelection []BackupTieringConfigurationResourceSelection `json:"resourceSelection" cfn:"ResourceSelection"`

	// +optional
	TieringConfigurationTags map[string]string `json:"tieringConfigurationTags,omitempty" cfn:"TieringConfigurationTags"`
}

// BackupTieringConfigurationStatus is the observed state of AWS::Backup::TieringConfiguration.
type BackupTieringConfigurationStatus struct {
	CloudControlStatus `json:",inline"`

	// Read-only: reported by AWS after creation.
	// +optional
	TieringConfigurationArn string `json:"tieringConfigurationArn,omitempty" cfn:"TieringConfigurationArn"`

	// Read-only: reported by AWS after creation.
	// +optional
	CreationTime string `json:"creationTime,omitempty" cfn:"CreationTime"`

	// Read-only: reported by AWS after creation.
	// +optional
	LastUpdatedTime string `json:"lastUpdatedTime,omitempty" cfn:"LastUpdatedTime"`
}

// BackupTieringConfiguration manages AWS::Backup::TieringConfiguration through the AWS Cloud Control API.
// Resource Type definition for AWS::Backup::TieringConfiguration
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type BackupTieringConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupTieringConfigurationSpec   `json:"spec,omitempty"`
	Status BackupTieringConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupTieringConfigurationList contains a list of BackupTieringConfiguration.
type BackupTieringConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupTieringConfiguration `json:"items"`
}

func (o *BackupTieringConfiguration) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *BackupTieringConfiguration) CloudControlTypeName() string {
	return "AWS::Backup::TieringConfiguration"
}
func (o *BackupTieringConfiguration) CloudControlSpec() interface{} { return &o.Spec }
func (o *BackupTieringConfiguration) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *BackupTieringConfiguration) CloudControlObserved() interface{} { return &o.Status }

// BackupTieringConfigurationResourceSelection is a nested property type of AWS::Backup::TieringConfiguration.
type BackupTieringConfigurationResourceSelection struct {
	Resources []string `json:"resources" cfn:"Resources"`

	TieringDownSettingsInDays int64 `json:"tieringDownSettingsInDays" cfn:"TieringDownSettingsInDays"`

	ResourceType string `json:"resourceType" cfn:"ResourceType"`
}

func init() {
	SchemeBuilder.Register(&BackupFramework{}, &BackupFrameworkList{})
	SchemeBuilder.Register(&BackupLegalHold{}, &BackupLegalHoldList{})
	SchemeBuilder.Register(&BackupLogicallyAirGappedBackupVault{}, &BackupLogicallyAirGappedBackupVaultList{})
	SchemeBuilder.Register(&BackupReportPlan{}, &BackupReportPlanList{})
	SchemeBuilder.Register(&BackupRestoreTestingPlan{}, &BackupRestoreTestingPlanList{})
	SchemeBuilder.Register(&BackupRestoreTestingSelection{}, &BackupRestoreTestingSelectionList{})
	SchemeBuilder.Register(&BackupTieringConfiguration{}, &BackupTieringConfigurationList{})
}
