/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/gen-cloudcontrol/gen.py from the CloudFormation schema registry. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = apiextensionsv1.JSON{}

// CodeArtifactPackageGroupSpec is the desired state of AWS::CodeArtifact::PackageGroup.
type CodeArtifactPackageGroupSpec struct {
	// ProviderRef selects the AWSProvider (account/region) this resource is
	// reconciled against. Defaults to the namespace annotation, then the
	// default provider, then the operator's own credentials.
	// +optional
	ProviderRef *ProviderRef `json:"providerRef,omitempty"`

	// The name of the domain that contains the package group.
	// +kubebuilder:validation:MinLength=2
	// +kubebuilder:validation:MaxLength=50
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="domainName is immutable"
	DomainName string `json:"domainName" cfn:"DomainName"`

	// The 12-digit account ID of the AWS account that owns the domain.
	// +optional
	DomainOwner string `json:"domainOwner,omitempty" cfn:"DomainOwner"`

	// The package group pattern that is used to gather packages.
	// +kubebuilder:validation:MinLength=2
	// +kubebuilder:validation:MaxLength=520
	// Create-only in AWS: changing it requires replacing the resource.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="pattern is immutable"
	Pattern string `json:"pattern" cfn:"Pattern"`

	// The contact info of the package group.
	// +kubebuilder:validation:MaxLength=1000
	// +optional
	ContactInfo string `json:"contactInfo,omitempty" cfn:"ContactInfo"`

	// The text description of the package group.
	// +kubebuilder:validation:MaxLength=1000
	// +optional
	Description string `json:"description,omitempty" cfn:"Description"`

	// The package origin configuration of the package group.
	// +optional
	OriginConfiguration *CodeArtifactPackageGroupOriginConfiguration `json:"originConfiguration,omitempty" cfn:"OriginConfiguration"`

	// An array of key-value pairs to apply to the package group.
	// +optional
	Tags []CFNTag `json:"tags,omitempty" cfn:"Tags"`
}

// CodeArtifactPackageGroupStatus is the observed state of AWS::CodeArtifact::PackageGroup.
type CodeArtifactPackageGroupStatus struct {
	CloudControlStatus `json:",inline"`

	// The ARN of the package group.
	// Read-only: reported by AWS after creation.
	// +kubebuilder:validation:MaxLength=2048
	// +optional
	Arn string `json:"arn,omitempty" cfn:"Arn"`
}

// CodeArtifactPackageGroup manages AWS::CodeArtifact::PackageGroup through the AWS Cloud Control API. The
// resource schema to create a CodeArtifact package group.
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Identifier",type="string",JSONPath=".status.identifier"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CodeArtifactPackageGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CodeArtifactPackageGroupSpec   `json:"spec,omitempty"`
	Status CodeArtifactPackageGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CodeArtifactPackageGroupList contains a list of CodeArtifactPackageGroup.
type CodeArtifactPackageGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CodeArtifactPackageGroup `json:"items"`
}

func (o *CodeArtifactPackageGroup) GetProviderRef() *ProviderRef { return o.Spec.ProviderRef }
func (o *CodeArtifactPackageGroup) CloudControlTypeName() string {
	return "AWS::CodeArtifact::PackageGroup"
}
func (o *CodeArtifactPackageGroup) CloudControlSpec() interface{} { return &o.Spec }
func (o *CodeArtifactPackageGroup) CloudControlStatusRef() *CloudControlStatus {
	return &o.Status.CloudControlStatus
}
func (o *CodeArtifactPackageGroup) CloudControlObserved() interface{}   { return &o.Status }
func (o *CodeArtifactPackageGroup) SetProviderStatus(p *ProviderStatus) { o.Status.AWSProvider = p }

// CodeArtifactPackageGroupOriginConfiguration is a nested property type of AWS::CodeArtifact::PackageGroup.
type CodeArtifactPackageGroupOriginConfiguration struct {
	// The origin configuration that is applied to the package group.
	Restrictions CodeArtifactPackageGroupRestrictions `json:"restrictions" cfn:"Restrictions"`
}

// CodeArtifactPackageGroupRestrictions is a nested property type of AWS::CodeArtifact::PackageGroup.
type CodeArtifactPackageGroupRestrictions struct {
	// The publish restriction determines if new package versions can be published.
	// +optional
	Publish *CodeArtifactPackageGroupRestrictionType `json:"publish,omitempty" cfn:"Publish"`

	// The external upstream restriction determines if new package versions can be ingested or retained from external
	// connections.
	// +optional
	ExternalUpstream *CodeArtifactPackageGroupRestrictionType `json:"externalUpstream,omitempty" cfn:"ExternalUpstream"`

	// The internal upstream restriction determines if new package versions can be ingested or retained from upstream
	// repositories.
	// +optional
	InternalUpstream *CodeArtifactPackageGroupRestrictionType `json:"internalUpstream,omitempty" cfn:"InternalUpstream"`
}

// CodeArtifactPackageGroupRestrictionType is a nested property type of AWS::CodeArtifact::PackageGroup.
type CodeArtifactPackageGroupRestrictionType struct {
	// +kubebuilder:validation:Enum=ALLOW;BLOCK;ALLOW_SPECIFIC_REPOSITORIES;INHERIT
	RestrictionMode string `json:"restrictionMode" cfn:"RestrictionMode"`

	// +optional
	Repositories []string `json:"repositories,omitempty" cfn:"Repositories"`
}

func init() {
	SchemeBuilder.Register(&CodeArtifactPackageGroup{}, &CodeArtifactPackageGroupList{})
}
