{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: konfig-system
  labels:
    app.kubernetes.io/name: konfig-konector
    app.kubernetes.io/managed-by: Helm
{{- end }}
